### ISSUE TITLE
When i import complete project in unity it gives me bundle of errors related to classes

### ISSUE THREAD

**Issue by kitmek1** [asus4/tf-lite-unity-sample#100]
**Environment (please complete the following information):**
 - OS/OS Version: [Andoroid 8.1]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [ Unity 2020.1.10.f1]

**Describe the bug**
When i import complete project in unity it gives me bundle of errors
![error1](https://user-images.githubusercontent.com/78305321/106469123-4fc4f500-64b8-11eb-9daf-6ee8a4f3b176.PNG)
![error2](https://user-images.githubusercontent.com/78305321/106469128-50f62200-64b8-11eb-9908-488b3e23d1f0.PNG)

 like 42 errors and all are related to classes like i attach the screenshots you can check there. so please tell me how i solve this issue thanks.
using Unity.Mathematics;
using Cysharp.Threading.Tasks;
like when i open scripts these errors are there that it is unaccessable.

**Expected behavior**

**Screenshots**

![error1](https://user-images.githubusercontent.com/78305321/106469123-4fc4f500-64b8-11eb-9daf-6ee8a4f3b176.PNG)
![error2](https://user-images.githubusercontent.com/78305321/106469128-50f62200-64b8-11eb-9908-488b3e23d1f0.PNG)

**Comment by kitmek1** [comment]
what do you mean by UniTask UMP. can you help me to run this project completely i wamt to access bodypose detection through android device.. 
i will write errors here..
Error1:
 Assets\tf-lite-unity-sample-master\tf-lite-unity-sample-master\Assets\Samples\Common\Color32Extension.cs(18,23): error CS0246: The type or namespace name 'float4' could not be found (are you missing a using directive or an assembly reference?)
Error 2:

Assets\tf-lite-unity-sample-master\tf-lite-unity-sample-master\Assets\Samples\BlazePose\PoseDetect.cs(84,22): error CS0246: The type or namespace name 'UniTask<>' could not be found (are you missing a using directive or an assembly reference?)

**Comment by asus4** [comment]
How did you import it? it is not enough if you have just copied the Assets folder. You need to install dependencies from Unity Package Manager.

The error means the scripts are not imported by [Unity Package Manager: UPM](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html). Please check your package manager is working.

UniTask is declared in [UniTask package](https://github.com/Cysharp/UniTask)
float4 is also declared in [unity.mathematics package](https://docs.unity3d.com/Packages/com.unity.mathematics@1.0/manual/index.html)

**Comment by kitmek1** [comment]
Hi
thanks for your guidance now i import both packeges of unitask and mathematics and there is no error in console but when i run any project like hanktracking or blazepose or smart reply then i find runtime error that failed to create tensorflowlite model i will put a screenshot of the error kindly check that and help me in this issue thanks for your cooperation.

![newerror](https://user-images.githubusercontent.com/78305321/106575964-12af4000-6556-11eb-98b7-c4709978cf35.PNG)

**Comment by asus4** [comment]
I can't determine what kind of error from this information, I'm afraid. Various causes can be assumed.

**Comment by kitmek1** [comment]
can you solve this issue in my pc through Teamviewer because i dont know why this error comes i do every thing but still this error comes..?

**Comment by kitmek1** [comment]
How it works on your PC? 
Did you find any error while running the project like that?
this is runtime error in console when i press play button then it happens..

**Comment by asus4** [comment]
I am afraid I don't provide individual support beyond the scope of OSS.
I can undertake some work as a freelancer, please DM me if you are interested.

**Comment by kitmek1** [comment]
ok thanks for help..
