### ISSUE TITLE
FPS Defference On iOS

### ISSUE THREAD

**Issue by DeepvisionsKorea** [asus4/tf-lite-unity-sample#101]
**Environment:**
 - OS/OS Version: [iOS 14.4] (iPhone8)
 - Source Version: [e.g. master/v2.4.0]
 - Unity Version: [e.g. Unity 2019.4.5.f17]

**Describe the bug**
When I am using DeepLabSample CPU mode
On iOS, The FPS is chainging in range of 28 - 4 FPS.
FPS is 18 - 28 FPS in few second(10 - 20 seconds) and 4 - 6 FPS after that.

When I am using own tflite model In DeepLabSample
The FPS is also changing from 10 to 2 FPS.
FPS is 10 - 6 FPS in few second(10 - 40 seconds) and 2  - 4 FPS after that.
Do you Suggest some opinion for this?

Thank you, for Advice!

**Comment by asus4** [comment]
Hi @DeepvisionsKorea 

I'm not sure why the FPS slow down after few seconds. You might something if you look in the Unity and Xcode profilers.

One thing is clear: DeepLab is a GPU-optimised model, including post-processing - the GPU seems to be more than 3x faster than the CPU, so it would be a good idea to make a GPU-supported model.

![fig gpu-cpu](https://miro.medium.com/max/1225/1*Ir3AZDQj5eiexYnaLWKLPA.png)

https://medium.com/tensorflow/tensorflow-lite-now-faster-with-mobile-gpus-developer-preview-e15797e6dee7

**Comment by DeepvisionsKorea** [comment]
Thank you very much for your Advice.

I try to use GPU option on Android and it is more faster and not slow down.
However, on iOS, sadly, not working the GPU Option.
I should capture the message and open another issue.
