### ISSUE TITLE
PoseNet Multi-Person Pose Estimation

### ISSUE THREAD

**Issue by CSE-JS** [asus4/tf-lite-unity-sample#104]
Hello, would it be possible to use tf-lite to utilize PoseNet's Multi-Person Pose Estimation?
https://github.com/tensorflow/tfjs-models/tree/master/posenet

We have been using different kinds of skeleton tracking sdk's in the past, but I'm totally new to Tensorflow. Being able to utilize PoseNet's Multi-Person Pose Estimation in Unity could be a life-saver for us. Thank you in advance.

**Comment by asus4** [comment]
Hi @CSE-JS 
Actually, the model output contains the data for multi-person. But I’ve just made the post-process for the single-person in C#. If you rewrite the JS post-process code in C#, it should work in Unity.

**Comment by asus4** [comment]
@joykirat18 Please refer to the [TFJS implementation](https://github.com/tensorflow/tfjs-models/blob/ba8f84d901bcafed217c4f073b052d2295caad68/body-pix/src/multi_person/decode_multiple_poses.ts).

If you don't mind other models, [MoveNet](https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/movenet) might be faster and more accurate than PoseNet. You can compare them on the TFJS website.

**Comment by joykirat18** [comment]
Does Movenet also have multi pose detection, I wanted to implement only multi-pose detection

**Comment by asus4** [comment]
Yes, the MoveNet model / implementations for multi-pose detection are not included in this repo. 
But it looks much simpler than PoseNet's one.

https://github.com/tensorflow/tfjs-models/blob/ba8f84d901bcafed217c4f073b052d2295caad68/pose-detection/src/movenet/detector.ts#L201-L227

**Comment by joykirat18** [comment]
Okay, will have a look.

**Comment by joykirat18** [comment]
I have written the code to get multi pose detection, but the confidence score for all 6 detections are always coming out to be 0. The output is converted into array of size 6 * 56. These are the 2 function changes that I have done. Can you please have a look and tell me why the score is coming out to be 0. Thanks a lot.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/66181127/160181569-196afd21-0ac0-4950-8196-52354b1335b4.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/66181127/160181616-74ae1775-a18b-4b72-a676-52f8c696345c.png">

**Comment by asus4** [comment]
I have implemented an example for [MoveNet multi-pose](https://www.tensorflow.org/hub/tutorials/movenet) in #210
Probably it would be much simpler and faster than PoseNet.
