### ISSUE TITLE
New SSD version is slower than previous one

### ISSUE THREAD

**Issue by Roberto7766** [asus4/tf-lite-unity-sample#105]
**Environment:**
 - OS/OS Version: Andoroid 9
 - Source Version: master
 - Unity Version: Unity 2019.4.21.f1

**Describe the bug**
I tried SSD with the latest version but It is slower than the previous version I used (Dec 2020).
The previous one was without any evident delay, the display was very responsive to the camera. With this new version the display has an evident lag to the camera, it is not responsive. It seems like it is not using the GPU but the CPU.
Is there a way to do some investigation?
Thanks

**Comment by asus4** [comment]
Hi @Roberto7766,

I've disabled the GPU option in several samples due to the Metal delegate issue in TensorFlow r2.4.0.
I think you can enable the GPU option if you need to run it on only Android.

See #103 for more detail.

**Comment by asus4** [comment]
Updated the TensorFlow library to the master branch version. Hope this fixes the issue.
