### ISSUE TITLE
Camera does not work when build on android device

### ISSUE THREAD

**Issue by yugosaito4** [asus4/tf-lite-unity-sample#108]
**Environment (please complete the following information):**
 - OS/OS Version: android 9.0
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.0.f1]

**Describe the bug**
when built to the android device to test, a message prompts to use camera but doesnt work. 

**To Reproduce**
Build on android device and run the hand tracking scene . I built using ARM64

**Expected behavior**
Expected the device camera to work and be able to use the sample scenes

**Screenshots**

**Additional context**
Add any other context about the problem and error logs here.

**Comment by asus4** [comment]
@yugosaito4  Do you see any errors in adb log? Can you share it?
