### ISSUE TITLE
Separate the TFLite package into another repository.

### ISSUE THREAD

**Issue by nixon-voxell** [asus4/tf-lite-unity-sample#109]
Problem:
Hard to update for Package users

Solution
Is it possible that you separate the TFLite package into another repository and link it as a submodule of this repo? This way developers can easily clone, update, and contribute to the package whenever they want easily.

**Additional context**
Btw is GPU Delegate supported on Windows? And how do I use GPU Delegate on dynamic-sized tensors?
![image](https://user-images.githubusercontent.com/43715558/111057244-e4137600-84c0-11eb-9d6b-26736e68385a.png)

**Comment by asus4** [comment]
Thanks for the suggestion @nixon-voxell 

I would also like to separate the core TFLite package into a separate repository.
As a workaround, you can use [OpenUPM](https://openupm.com/packages/com.github.asus4.tflite/) to install the core library and able to choose the specific versions. Please use it for now.



And GPU Delegate is not supported on Windows. The only CPU mode is supported.

**Comment by nixon-voxell** [comment]
Thank you for your reply! Would appreciate a lot if you separate it. Cuz contributing it will also be a lot easier.

**Comment by nixon-voxell** [comment]
I created a pull request to solve this issue, no need to create separate TFLite package into another repository.
