### ISSUE TITLE
Build for Android ARMv7

### ISSUE THREAD

**Issue by marimomo00** [asus4/tf-lite-unity-sample#11]
Thanks for the sample project. It helps me a lot.

I'm new to building App on Unity. I'm really need help from you.
I'm trying to build the sample of Posenet for Android. I can build the Android App with ARM64, it works very well on my mobile. However, it doesn't work on my another android phone. So I tried to build with ARMv7 support. It built successfully but it runs with error. The error is,

<i>AndroidPlayer(ADB@127.0.0.1:34999)</i> DllNotFoundException: Unable to load DLL 'libtensorflowlite_gpu_delegate': The specified module could not be found.
  at TensorFlowLite.GpuDelegate.TfLiteGpuDelegateOptionsV2Default () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.GpuDelegate..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.BaseImagePredictor`1[T].CreateGpuDelegate () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.PoseNet..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
  at PoseNetSample.Start () [0x00000] in <00000000000000000000000000000000>:0 
 
What is the problem? Anything that I can do?

**Comment by asus4** [comment]
@marimomo00 Android plugin *.so files are built for Arm64 CPU for now. Could you try to rebuild the plugin with `android_arm` option instead of `android_arm64`?

```
# Configure the Android SDK path by running configure script at the repository root
./configure

# Build experimental
bazel build -c opt --cxxopt=--std=c++11 --config=android_arm //tensorflow/lite/experimental/c:libtensorflowlite_c.so

# Build GPU delegate
bazel build -c opt --config android_arm --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```

**Comment by marimomo00** [comment]
Thanks for your prompt reply.

I will have a try.

**Comment by gblue1223** [comment]
Hi @asus4 what version of tensorflow do you use?
I've tried to build with 1.15.2 and 'libtensorflowlite_c.so' built successfully but failed to build 'libtensorflowlite_gpu_delegate.so' with below error.
```
(base) greenblue@greenblue-ubuntu:~/Work/tensorflow-1.15.2$ bazel build -c opt --config android_arm --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/greenblue/Work/tensorflow-1.15.2/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --copt=-w --config=v1
INFO: Reading rc options for 'build' from /home/greenblue/Work/tensorflow-1.15.2/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/greenblue/miniconda3/bin/python --action_env PYTHON_LIB_PATH=/home/greenblue/miniconda3/lib/python3.7/site-packages --python_path=/home/greenblue/miniconda3/bin/python --config=xla --action_env ANDROID_NDK_HOME=/home/greenblue/Android/Sdk/ndk/20.1.5948944 --action_env ANDROID_NDK_API_LEVEL=18 --action_env ANDROID_BUILD_TOOLS_VERSION=29.0.3 --action_env ANDROID_SDK_API_LEVEL=29 --action_env ANDROID_SDK_HOME=/home/greenblue/Android/Sdk --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v1 in file /home/greenblue/Work/tensorflow-1.15.2/.bazelrc: --define=tf_api_version=1 --action_env=TF2_BEHAVIOR=0
INFO: Found applicable config definition build:xla in file /home/greenblue/Work/tensorflow-1.15.2/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file /home/greenblue/Work/tensorflow-1.15.2/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:android_arm in file /home/greenblue/Work/tensorflow-1.15.2/.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file /home/greenblue/Work/tensorflow-1.15.2/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
ERROR: Skipping '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': target 'libtensorflowlite_gpu_delegate.so' not declared in package 'tensorflow/lite/delegates/gpu' defined by /home/greenblue/Work/tensorflow-1.15.2/tensorflow/lite/delegates/gpu/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': target 'libtensorflowlite_gpu_delegate.so' not declared in package 'tensorflow/lite/delegates/gpu' defined by /home/greenblue/Work/tensorflow-1.15.2/tensorflow/lite/delegates/gpu/BUILD
INFO: Elapsed time: 0.287s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by manena** [comment]
I'm sorry I'm new to building so files.
I would like to build for android_arm. I'm working on MAC OS Catalina and have no idea if these are commands to run from the shell, what directory I should be in and what would I need to install in order to be able to build.

Can you give me some guidance?

Thanks in advance

**Comment by marimomo00** [comment]
@manena 
There are instruction on building tensorflow. 
https://www.tensorflow.org/install/source

However, I got lots of error when compiling on windows. I'm still struggling on building android_arm. I've opened another issue and hope someone could help.

https://github.com/tensorflow/tensorflow/issues/38525

@gblue1223 I've tried ''tensorflow-2.1.0" and ''bazel-0.29.1'', but with error. Do you build on Windows or MAC OS?

**Comment by gblue1223** [comment]
@marimomo00 I've built on Ubuntu. Since Tensorflow more familiar with Linux, you should try on Linux OS.

**Comment by manena** [comment]
Thanks @marimomo00 i’ll try.
In the meanwhile @gblue1223: would it be possible for you to share with us the .so files you have built? It would be very helpful!

Regards and I hope all of you and your families are fine!

**Comment by gblue1223** [comment]
@manena [Here](https://drive.google.com/open?id=1-EVoT21urEQrtos8_xoEZ6IWZNr3Jioa) is the .so files. Good luck~

**Comment by Freeverc** [comment]
I've built libtensorflowlite_c.so for ARMv7，but I can not use it in your samples. The  result on my phone is pure white with no images.How can I use it in ARMv7? I've changed the Target Architectures.

**Comment by emusiceducation123** [comment]
I built for ARMv7 as well. When it runs, log shows:
08-29 11:01:18.646  3872  4085 I tflite  : Initialized TensorFlow Lite runtime.
08-29 11:01:20.242  7703  7723 E Unity   : Unable to find libtensorflowlite_gpu_delegate
08-29 11:01:20.244  7703  7723 E Unity   : Unable to find tensorflowlite_gpu_delegate
08-29 11:01:20.259  7703  7723 E Unity   : Unable to find libtensorflowlite_c

**Comment by mathtasatlime** [comment]
Does anybody have a working build auf 2.4.0 for armv7 ?
