### ISSUE TITLE
MeetSegmentation crashes on iOS

### ISSUE THREAD

**Issue by EugenCondur** [asus4/tf-lite-unity-sample#111]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 14.4
 - Source Version: master
 - Unity Version: Unity 2019.4.19.f1
 - iPhone XR
 
**Describe the bug**
MeetSegmentation on iOS crashes with "Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (IOAF code 11)"

**To Reproduce**
Compile and run MeetSegmentation on iOS.

**Comment by asus4** [comment]
It looks like hanging up in the pre/post compute shader. 
https://forum.unity.com/threads/iphone-8-a11-gpu-hang-error-command-buffer.500549/

**Comment by asus4** [comment]
Fixed it!
