### ISSUE TITLE
SSD sample is very slow on android phone

### ISSUE THREAD

**Issue by poorya7** [asus4/tf-lite-unity-sample#113]
**Environment (please complete the following information):**
 - OS/OS Version: Andoroid 10
 - Source Version:  master, v 2.3.1
 - Unity Version: Unity 2019.4.20.f1

**Describe the bug**
I ran the SSD sample scene, made a build on the android phone (Galaxy S10) and it's very slow. The camera updates very slowly with movement and the whole app very slow in responding. 

**To Reproduce**
Make a build on an android phone from the SSD scene.

**Comment by asus4** [comment]
It’s running around 30fps on my Sony Xperia (Android 10). 
Could you send me the results of the profiler on  your mobile?

![a](https://user-images.githubusercontent.com/357497/111591207-7076af00-87c7-11eb-8a2e-00862fed08f5.png)

**Comment by poorya7** [comment]
Hi Koki

I couldn't attach it here (unsupported file type) so I put the profiler data on google drive : https://drive.google.com/file/d/13vD2tqEBdMbhNoP6kttxIRFfO0K4hR8U/view?usp=sharing

It's from a galaxy S10.

**Comment by poorya7** [comment]
Here's also a screen recording from running on the same phone: https://drive.google.com/file/d/10AIXplIzz1Bxbn1p6pOshQe-rtil9Hs1/view?usp=sharing

As you see it's very slow.

**Comment by poorya7** [comment]
@asus4 

Thanks again for looking into it. I was wondering, since I'm not that familiar with tensorflow, if there's an easy way to change to model to just tell me if an object is a book, or not a book? I don't care about any other objects. 

Maybe that simplification would also help reduce run-time calculations and make it run faster? 🤔

**Comment by FrankSpalteholz** [comment]
Hey Koki and Poorya7 ... there is a "new" TFlight model for object-detection available here https://github.com/google/mediapipe/blob/master/mediapipe/models/ssdlite_object_detection.tflite ... doc: https://google.github.io/mediapipe/solutions/object_detection.html ... @Koki have you already benchmarked this model against the coconet-version? The output-tensors are completely different though so @Poorya7 you can't just just plug this model in.

**Comment by poorya7** [comment]
Hi @FrankSpalteholz 

Thanks for the tips. Could you please tell me the steps to replace these models in the unity application? I don't know much about tensorflow, but you mentioned I can't just plug them in, so what would I need to do? 

Thanks a lot

**Comment by FrankSpalteholz** [comment]
I fear that's nothing you can write down like a quick "how-to" for several reasons. First the coco-ssd-net-implementation has been coded for the input and output tensors of this specific model. Koki provides model-infos in the console how the model has been setup (outputs and inputs -> array-sizes) But you will have to replace and change the ssd-class towards the "new" model i've mentioned. I'm working with this plugin now since a while and since this whole repo is (at lest for me) quite advanced i'm still in the learning and adapting process. Also each task and each model is quite different so i'd recommend to strip it down to its core -> defining the ssd-class with only the needed inputs and outputs -> then try to invoke (send your inputs to the tf-light-core) -> see if your outputs are making "sense" and also if it works with gpu-delegate(!) -> try to add functionality and logic and process the output-data. That will take a while but it will give a lot of understanding how this works in general. (correct me if made mistakes Koki)

**Comment by poorya7** [comment]
@FrankSpalteholz Thank you. I started with your instructions, but I'm afraid I need much more knowledge of tensorflow to get there.

**Comment by poorya7** [comment]
@asus4 Did you find anything related to why it runs slow? 
It's also slow on my PC, so it's not only a mobile thing. When I run the SSD Scene on my PC, it's very slow.

**Comment by asus4** [comment]
@poorya7 Sorry for the late reply, I looked at your S10 profile but couldn't see the problem. Have you tested the same model on the [official android sample](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)? 

Simplifying the model would make it faster, but taking 300ms to recognize it seems to be a different problem for me. To customize your model, please refer to [this article](https://www.tensorflow.org/lite/examples/object_detection/overview#how_to_choose_a_model_to_customize).

**Comment by asus4** [comment]
@FrankSpalteholz Thanks for your comment. I just tried it on my iPhone and the MediaPipe’s object detection is a bit faster than in the TensorFlow Lite model.

While the tflite model has a custom post-process ops (Non-max suppression ops) for object-detection, the MediaPipe model does not. So we need to add an NMS post-process in C#, similar to the BlazeFace example.

**Comment by poorya7** [comment]
Hi @asus4 
I spent some time learning a little bit of tensorflow, and finally managed to train my own model for book detection, convert it to .tflite and now I want to try that in your unity asset. 

I replaced the label map and tflite file with my own, but when I run the project, I get a tensorflow error: 

`Exception: TensorFlowLite operation failed.
TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:179)
TensorFlowLite.Interpreter.SetInputTensorData (System.Int32 inputTensorIndex, System.Array inputTensorData) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:97)
TensorFlowLite.SSD.Invoke (UnityEngine.Texture inputTex) (at Assets/Plugins/Tenserflow lite for Unity Samples/SSD/SSD.cs:32)
SSD_Changed.Update () (at Assets/Scripts/SSD_Changed.cs:63)
`

I've attached my label map here. and my .tflite model is here : https://drive.google.com/file/d/1WQEO9Pa-LKpkVQLCRBtpN7Oa4tIz9Jzc/view?usp=sharing

[my_label_map.txt](https://github.com/asus4/tf-lite-unity-sample/files/6255353/my_label_map.txt)

Should I replace some tensor input/output settings also in the script before replacing the model? If so, would  you please tell me what I need to change to make my model work with your asset? 

Thanks a alot

**Comment by FrankSpalteholz** [comment]
I know that's not helping you on Android @poorya7 but i can confirm that the TFlite SSD + Objectron + ARFoundation is capable of running 30fps on an iPhone12Pro (though) :D ...

**Comment by poorya7** [comment]
@FrankSpalteholz 
Yea since this is gonna be an app that runs on different phones, I need to make it fast on both android and ios. 
I finally trained a new model in tensorflow and exported it as .tflite, but when I plug it in, it gives exceptions, as I mentioned in my previous reply. Do you know an easy way to make my model and label map work with this asset? I don't even know where to start changing the code cause I don't have that much familiarity with tensorflow structure yet.

**Comment by FrankSpalteholz** [comment]
If you have trained your own model then you should be over total control/knowledge about your inputs and outputs (i assume) So start plugin your model and hit bruteforce-like "play" in the editor. Check console outputs. If your model was successfully loaded then you should see a log displaying the array-sizes of inputs and outputs (log comes from BaseImagePredictor-class ->  interpreter.LogIOInfo()) If you can see this output then life is good. Next steps are actually straight forward. By checking the SSD example you will see that there is a function for invoking the interpretor (SsdSample.cs->Invoke):

```
ToTensor(inputTex, input0); // 300x300 pixel rbg image
interpreter.SetInputTensorData(0, input0);
interpreter.Invoke();
interpreter.GetOutputTensorData(0, outputs0); // 10x4 tensor for 10 detected objects with x,y,width,height (boundingbox)
interpreter.GetOutputTensorData(1, outputs1); // 10x1 tensor for 1 class per object
interpreter.GetOutputTensorData(2, outputs2); // 10x1 tensor for detection score per object
```

(Choose the size of the input and output arrays accordingly to your custom model). One thing is that you should also check the second parameter in constructor of the BaseImagePrecitor. Set it to true-> asset will try to run in GPU-mode/delegate and false if you wish to run on CPU. If life is still good then you should be able to get your inference-data back from the interpretor. If so then the rest depends on your choice of prcessing the output-data. If you have the exact same output-structure like ssd_mobilenet.tflight (which this example is based on) then you should get appropriate results. If you have another layout then ofcourse you will have to process your outputs according to your specific design.

**Comment by rahul-nt** [comment]
@FrankSpalteholz 
Hi
Do you know how to change the input dimensions to the SSD, so for example to run some other tflite model with input dimensions being 400x400x3 ?
