### ISSUE TITLE
Body Mesh

### ISSUE THREAD

**Issue by peethamber** [asus4/tf-lite-unity-sample#114]
I am working on a project where I will have to draw a mesh for the detected points on the body very similar to the MediaPipe face mesh example. Can you suggest a way of doing this. I am using Unity 2020.

**Comment by asus4** [comment]
@peethamber I don't think of any tflite models that can detect the body mesh keypoint.
There are examples in TensorFlow and PyTorch, so you could try converting those to tflite.
