### ISSUE TITLE
Request for support for SELECT_TF_OPS

### ISSUE THREAD

**Issue by nixon-voxell** [asus4/tf-lite-unity-sample#116]
**Is your feature request related to a problem? Please describe.**
This feature request is related to [constant tensor not supported issue thread](https://github.com/asus4/tf-lite-unity-sample/issues/110)

and 

[conformer tflite model unusable in tensorflow c api thread](https://github.com/TensorSpeech/TensorFlowASR/issues/163)

according to the first thread, the current compiled c API does not support `SELECT_TF_OPS`

**Describe the solution you'd like**
I would like to request a build of this feature included. A solution was proposed from the second thread, stating that it can be solved if `SELECT_TF_OPS` is included in the C API.

You can do so by following this: https://stackoverflow.com/questions/58623937/how-to-build-tensorflow-lite-with-select-tensorflow-ops-for-x86-64-systems/58692079#58692079

**Comment by asus4** [comment]
@nixon-voxell I would prefer not to include select-ops options in this repository as it would increase the size of the library by many times. But you can build it yourself for all platforms. Please refer to the official TFlite documents and the build script that I used ↓
https://github.com/asus4/tf-lite-unity-sample/blob/c944c63df13a1dce7f62ccf4effc5b04befc7bb5/build_tflite.py

**Comment by nixon-voxell** [comment]
Oh thank you very much! Didn't noticed there is a code to build those apis!!

**Comment by chrisError** [comment]
so after trying to the build process above to add SELECT_TF_OPS, I am getting multiple warnings and a final fail (but with Build completed successfully also reported)

I have two warnings of unsuccesful downloads from
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/40548a2974f1aea06215272d9c2b47a14a24e556.tar.gz failed

and also the final copy file seems to fail too 
cp: /usr/local/Cellar/bazel/4.0.0/libexec/bin/Packages/com.github.asus4.tflite/Plugins/macOS/libtensorflowlite_c.dylib: No such file or directory

I am on Mac OS Catilina. Any help much appreciated.

**Comment by asus4** [comment]
@chrisError It seems to be a TensorFlow issue. Please make sure you can build TensorFlow first, and if you still get the error, please open an issue in TensorFlow's GitHub.
https://github.com/tensorflow/tensorflow

**Comment by chrisError** [comment]
I added -define=with_select_tf_ops=true to the bazel build command in build_mac, no errors reported now, but I still seem to be getting the following error

Interperter Warning: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

Any help / advice appreciated!

**Comment by asus4** [comment]
@chrisError Not sure, but I guess your model still contains the custom-ops 
https://github.com/tensorflow/tensorflow/blob/d310b4c2c91072d6285cf6e4ff3da2fb5782d0e6/tensorflow/lite/core/subgraph.cc#L871-L877
