### ISSUE TITLE
Regular TensorFlow ops are not supported by this interpreter.

### ISSUE THREAD

**Issue by chrisError** [asus4/tf-lite-unity-sample#119]
**Environment**
Mac OS 10.15.6 (Catalina)

**Issue**
We have created a custom TensorFlowLite model, that is working inside the Python runtime but when we try loading it into Unity we get the following error / warning 

**"Interperter Warning: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference."**

Any help or guidance on how to resolve this would be hugely appreciated, thanks!

**Comment by asus4** [comment]
@chrisError the Flex delegate is disabled in this repo. Please see #116 for further info.

**Comment by chrisError** [comment]
thanks, apologies for not knowing that was the same issue!
