### ISSUE TITLE
Creating ARAnchors

### ISSUE THREAD

**Issue by Kanyade** [asus4/tf-lite-unity-sample#120]
Is there a way to create ARAnchors at the detected objects with this project?
Like in this project: https://github.com/derenlei/Unity_Detection2AR
What I want to do is detecting just a few objects with a custom model and it would be a nice addition but don't know where to start. It is based on the "hit.pose" of an "ARRaycastHit hit".

**Comment by asus4** [comment]
@Kanyade 
I think it is possible in the same way as Unity_Detection2AR. May I ask why you don't use the Unity_Detection2AR?

**Comment by Kanyade** [comment]
@asus4 
I already did. It works well, I am just a curious being and want to compare perfomance and execution time as this project of yours works really well(speed and accuracy)
