### ISSUE TITLE
Hand tracking sample - run in background thread on real device

### ISSUE THREAD

**Issue by Sv9zIsT** [asus4/tf-lite-unity-sample#122]
Hello
Thanks for awesome work!

Hand Tracking Sample

**Environment (please complete the following information):**
 - OS/OS Version: [Andoroid 11]
 - Source Version: [e.g. master/v2.4.0]
 - Unity Version: [e.g. Unity 2019.4.23.f1]
 - Device: Google Pixel 2xl

**Describe the bug**
"run in background thread" feature on real device isn't working properly.

**To Reproduce**

I tried to use this example and stuck with issue
option "run backround" not working on real android device (tested on Pixel 2xl, don't have another... last 10 android)
in logcat (via ADB) it detects next issue:

2021.04.05 15:34:39.257 21092 21157 Error Unity Exception: TensorFlowLite operation failed.
2021.04.05 15:34:39.257 21092 21157 Error Unity at TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.257 21092 21157 Error Unity at TensorFlowLite.Interpreter.Invoke () [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.257 21092 21157 Error Unity at TensorFlowLite.PalmDetect+d__8.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.257 21092 21157 Error Unity at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2[TStateMachine,T].Run () [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.257 21092 21157 Error Unity at Cysharp.Threading.Tasks.SwitchToThreadPoolAwaitable+Awaiter.Callback (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.257 21092 21157 Error Unity at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.257 21092 21157 Error Unity at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.257 21092 21157 Error Unity at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <000000000 2021.04.05 15:34:39.268 21092 21157 Info chatty uid=10553(com.Sv9zIsT.handTracking) GC Finalizer identical 1 line 2021.04.05 15:34:39.275 21092 21157 Error Unity Exception: TensorFlowLite operation failed. 2021.04.05 15:34:39.275 21092 21157 Error Unity at TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.275 21092 21157 Error Unity at TensorFlowLite.Interpreter.Invoke () [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.275 21092 21157 Error Unity at TensorFlowLite.PalmDetect+<InvokeAsync>d__8.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 2021.04.05 15:34:39.275 21092 21157 Error Unity at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask2[TStateMachine,T].Run () [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.275 21092 21157 Error Unity at Cysharp.Threading.Tasks.SwitchToThreadPoolAwaitable+Awaiter.Callback (System.Object state) [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.275 21092 21157 Error Unity at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.275 21092 21157 Error Unity at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0
2021.04.05 15:34:39.275 21092 21157 Error Unity at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <000000000

could you please advice me what I do wrong or how to fix it
thanks in advance!

![HandTrackingIssue](https://user-images.githubusercontent.com/17169133/114168419-e7bbe080-9938-11eb-82fa-49e43a33b6c5.png)

Edited -> Android version was 11!!! not 10!!!

**Comment by asus4** [comment]
@Sv9zIsT  I have tested with the following environment: 

- OS/OS Version: Andoroid 10
- Source Version: master
- Build Unity Version: Unity 2019.4.24.f1
- Device: Sony Xperia XZ2

No errors are raised when the `runBackground` option is enabled.
It seems to be a device-specific error, it would be difficult to fix without having Pixel 2XL

**Comment by Sv9zIsT** [comment]
Thanks for your research!
Oh it looks like another specific pixel issue...
I will research from my side too now because I thought it's common Android issue...
If I will found something I let you know)

**Comment by Sv9zIsT** [comment]
I have researched this issue and below what I did:

I did a mistake when decribe bug report, I really did't know that my phone have Android 11, I wrote Android 10, my bad sorry :)

1) upgrade UniTask package to latest version to 2.2.5, issue not disapear, still not run in background thread
https://github.com/Cysharp/UniTask/releases

2) I have test on my friend's phone -> Redmi note 8T Android 10 and it really works on this android!!!

3) I research issue with android low light camera which I found in OpenCvFor unity Asset from asset store
https://forum.unity.com/threads/android-webcamtexture-in-low-light-only-some-models.520656/
https://forum.unity.com/threads/released-opencv-for-unity.277080/page-33#post-3445178
and considering this I tried to change resolution and FPS for Unity WebCamTexture
from         //webcamTexture = new WebCamTexture(cameraName, 1280, 720, 30);
to             webcamTexture = new WebCamTexture(cameraName, 640, 480, 15);

and it doen't help too...

So considering above I suppose it's issue appears on 11 Android (not sure now that it's a specific Pixel's phone bug)
and perhaps it's a problem with UniTask package because something happing in phone memory when application starts use background theads

I don't know how to research it next for now...

If you have any ideas or assumptions what may produce this issue...

if needs some feedback from my side let me know :)
