### ISSUE TITLE
BlazePose slow on device

### ISSUE THREAD

**Issue by AhmedAhres** [asus4/tf-lite-unity-sample#123]
Hello,

I have used the BlazePose full body model on iOS and it seems like the FPS is down to 12. 

Is there anything we can do to improve the performance?

Ahmed

**Comment by asus4** [comment]
@AhmedAhres There are several things we can do to improve it:
- Use quantized models
- Support binding the GPU buffer #23
- CPU with XNNPack might be faster than GPU in some case
