### ISSUE TITLE
Can .tflite loaded model be reused?

### ISSUE THREAD

**Issue by DanielDorDev** [asus4/tf-lite-unity-sample#124]
I am trying to create a producer\consumer system with tflite model prediction, 
if I decouple ``` FileUtil.LoadFile(modelPath)``` and pass it as a parameter to BaseImagePredictor constructor, will it work? or the loaded byte array needs to be copied and then pass the instance to the constructor

**Comment by asus4** [comment]
@DanielDorDev the byte[] array should be reused. it is copied in the interpreter.

https://github.com/asus4/tf-lite-unity-sample/blob/2186253231f7062b63b71a4eda363dd0ba3bb063/Packages/com.github.asus4.tflite/Runtime/Interpreter.cs#L59-L61

But I'm not sure if the actual instance of TfLiteModel can be reused or not. Please try it yourself.

**Comment by DanielDorDev** [comment]
> instance

Where is it copied in the interpreter? 
Does GCHandle.Alloc create an instance? or only prevent GC from collecting array

**Comment by asus4** [comment]
It is created in C API. Unity is just a wrapper of the C API.
Please check the original repository if you wanted to know more deeply.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h

**Comment by DanielDorDev** [comment]
> It is created in C API. Unity is just a wrapper of the C API.
> Please check the original repository if you wanted to know more deeply.
> 
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h

Thank you!
