### ISSUE TITLE
can we run in potrait mode

### ISSUE THREAD

**Issue by yugosaito4** [asus4/tf-lite-unity-sample#125]
i built the application to android unity , and the face mesh keypoint spawn in landscape while my application runs in portrait

**Comment by DanielDorDev** [comment]
> i built the application to android unity , and the face mesh keypoint spawn in landscape while my application runs in portrait

It is because the camera internal texture is landscape, possible solutions:
  - Rotate the image before passing it to the model
  - Rotate the results after you got the results from the model

**Comment by yugosaito4** [comment]
where do i rotate it?

**Comment by DanielDorDev** [comment]
> where do i rotate it?

In function\shader

**Comment by yugosaito4** [comment]
can we increase the view of the camera as well
