### ISSUE TITLE
Multi hand tracking

### ISSUE THREAD

**Issue by yugosaito4** [asus4/tf-lite-unity-sample#126]
HI! is there a way to allow multi hand tracking as the current only draws the joints on a single hand

**Comment by asus4** [comment]
Hi @yugosaito4 You just need to call `Invoke` for all palm results

https://github.com/asus4/tf-lite-unity-sample/blob/2186253231f7062b63b71a4eda363dd0ba3bb063/Assets/Samples/HandTracking/HandTrackingSample.cs#L95-L98

**Comment by yugosaito4** [comment]
tried it and it still only draw the hand joints on one hand

**Comment by TheBricktop** [comment]
Care to share the code?
