### ISSUE TITLE
Not working in portrait mode

### ISSUE THREAD

**Issue by Rajesh-Nadar** [asus4/tf-lite-unity-sample#127]
I am using Unity 2020.3.1f 

I tried building the example scene and install it in my android phone. It works fine in landscape mode but it starts shaking in portrait mode.

**Comment by asus4** [comment]
duplicated with #125

@Rajesh-Nadar  Does it work fine on iPhone?

**Comment by Rajesh-Nadar** [comment]
I don't have an iphone to test

**Comment by Rajesh-Nadar** [comment]
@asus4 As I heard the model expects a landscape image as input so it creates issues if we provide a portrait image and I don't know how to rotate the input.

**Comment by asus4** [comment]
Hi @Rajesh-Nadar 

I have tested with the following environment:
- OS/OS Version: Andoroid 10
- Source Version: master
- Build Unity Version: Unity 2019.4.24.f1
- Device: Sony Xperia XZ2

https://user-images.githubusercontent.com/357497/116009681-59737a00-a61b-11eb-9c8b-2255c43cf45d.mp4

It seems to be working normally with all orientations. Some Android might have the camera rotation issue, but it would be difficult to fix as I can not reproduce it.

**Comment by Rajesh-Nadar** [comment]
@asus4  This problem occurs when the videoRotationAngle is 270 degree and maybe only in facemesh example. Is was able to fix the detection problem in android by rotation the transformMat to 270 degree BUT the output (image a detection points) is still in landscape. I tried rotating the rect transfrom but the detection points just like to stay in its original rotation and just breaks everthing.

**Comment by Rajesh-Nadar** [comment]
@asus4 Well!!!! It worked my bad. It was a silly mistake made by me. This is how I fixed it.

In android may be not every device the the viewRotationAngle by default in portrait is 270 because of that default webcamTexture is rotated to 270 so I rotated a texture to 0 and then set the viewCam RawImage to rotated Texture in the update  function then everthing worked fine
