### ISSUE TITLE
palm detection model in this repo ist not the same one as in MediaPipe, why?

### ISSUE THREAD

**Issue by mathtasatlime** [asus4/tf-lite-unity-sample#129]
I just found out that the palm detection model in this repo is not the same one which is in the current [MediaPipe github](https://github.com/google/mediapipe/tree/master/mediapipe/modules/palm_detection). And espacially its not the one described in the model card in [here](https://drive.google.com/file/d/1yiPfkhb4hSbXJZaSq9vDmhz24XVZmxpL/view). 
@asus4 could you describe where you got exactly this model or whether you created it by yourself (quantization etc)? What would I have to change when I want to use the official palm model from the MediaPipe github. I already adapted the input size of the frame and the number of anchors because they differ between the models. But that was not enough since the model still throws error messages while using.
Many thanks for your help!

**Comment by asus4** [comment]
The MediaPipe model has recently been updated to estimate the left or right of the hand. however, the model in this repo has not updated yet.

**Comment by mathtasatlime** [comment]
[FOUND SOLUTION] 
And as I found out it also updated the palm detection model from an 256x256 input image to an 128x128 image. however they changed to order of the output tensors. To use the up-to-date (much faster) model you have to apply some changes to the PalmDector:

1. private float[] output0 = new float[896];
    private float[,] output1 = new float[896, 18];

2. var options = new SsdAnchorsCalculator.Options()
            {
                inputSizeWidth = 128,
                inputSizeHeight = 128,
    ....
3. interchange the output tensors:
         interpreter.GetOutputTensorData(1, output0);
         interpreter.GetOutputTensorData(0, output1);

After these changes, the detecion worked again without errors.
