### ISSUE TITLE
Meet segmention mask

### ISSUE THREAD

**Issue by Ivan547-arnus** [asus4/tf-lite-unity-sample#133]
Hi how could i show only segmentation area?

**Comment by asus4** [comment]
Hi @Ivan547-arnus 

https://github.com/asus4/tf-lite-unity-sample/blob/f3e41a53db7968114ce27eedfc88e2e8533009f2/Assets/Samples/MeetSegmentation/LabelToTex.compute#L12-L14

Green: human area
Red: background area

You can use it in your shader or customize the compute shader.
