### ISSUE TITLE
SSD false detections after update

### ISSUE THREAD

**Issue by d-lay** [asus4/tf-lite-unity-sample#140]
Hi,

After finally updating to the newest version of  tf-lite-unity-sample i frequently get false detections, especially if the object is not on screen. Now i get false detections with a confidence score above 0.5 even if the object is not visible. On such a false detection i also get a bounding box size of 0,0 or even negative. The object is still detected most of the time fine, but every few frames i get this false detection. When i was using an older version of this tool (from 24.04.2020 or earlier) everything was working as intended without those false detections. 

This issue does not occur with the models provided in this repo. So the problem must be within my model. The model i use is [ssd_mobilenet_v1_0.75_depth_coco](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md), transfer learned on custom data. Quantized for UINT8 with the toco converter in tf1.15. If any additional info is required just let me know. 

More Info:
OS: Android 8.1+
This repo from 24.04.2020 (working)
This repo from 24.04.2020 (problem with false detections)
Unity version 2019.4.24f1

Any help i appreciated very much!  Thank you

**Comment by asus4** [comment]
Hi, @d-lay 

I enabled the GPU delegate in the commit below,
https://github.com/asus4/tf-lite-unity-sample/commit/df0f4468f7c7424de64cff4737e7fd9d953ff112#diff-3b0e9a33b1440225e1df83742b1656868af316c0f02155956caa2f0fd55becfdR22

Can you try disabling it on your model?

**Comment by d-lay** [comment]
Thank you for your quick reply @asus4!

I set "useGpu" to false and i do not get wrong bounding boxes anymore. But i am also now running on only 5fps. In the old version from 24.04.2020 i was using the gpu delegate without the false detections.

Do you know how to proceed from here to still get fast inference without false detections?

**Comment by asus4** [comment]
I guess there's something wrong with the delegate options, please try modifying the options in GpuDelegateV2.

↓ Pass the delegate options here,
https://github.com/asus4/tf-lite-unity-sample/blob/0e29581b13bf8a523632f318d243b489fd350def/Packages/com.github.asus4.tflite/Runtime/InterpreterOptions.cs#L94-L95

For options description, please take a look at the comment in the tflite original code, Sorry for no documentation in the C# code.
https://github.com/tensorflow/tensorflow/blob/9929dd2386f0decaf75b7b1cc9d751d0b581d418/tensorflow/lite/delegates/gpu/delegate.h#L64

**Comment by d-lay** [comment]
Thank you!

**Comment by d-lay** [comment]
Thank You again @asus4 !

So far i have tried  all possible values for _isPrecisionLossAllowed_,  _inferencePreference_ and _experimentalFlags_, as i found them to be the more  promising options. 
I noticed no differences yet, it seems to not matter what values i use. If i use an invalid value then the detection does not work, but that's all the reaction i got so far. 

I assume the following options would be preferable and those are actually also the default options if i am not mistaken.

```
#if UNITY_ANDROID && !UNITY_EDITOR
    return new GpuDelegateV2(new GpuDelegateV2.Options()
    {
        isPrecisionLossAllowed = 0,
        inferencePreference = 0,
        inferencePriority1 = 1,
        inferencePriority2 = 0,
        inferencePriority3 = 0,
        experimentalFlags = GpuDelegateV2.ExperimentalFlags.EnableQuant,
        maxDelegatedPartitions = 1,
    });
```

Am i missing something? Is the cause of my problem maybe a different one?

**Comment by asus4** [comment]
@d-lay, the options look correct. So I don't have any ideas now without seeing your model. It might come from mismatching between your model and the TensorFlow version. Can you open the issue on TensorFlow's repository?

**Comment by d-lay** [comment]
Thank you i will try that. 
Your plugin works with any model trained in any TF version correct (as long as they match)? Or do i need to use TF 2.4 as recommended?
