### ISSUE TITLE
Please Add MediaPipe Objectron 3D detection 

### ISSUE THREAD

**Issue by nenenkosi** [asus4/tf-lite-unity-sample#142]
The repo does not provide an easy way to use objection on the application it would be super nice to have the objectron example on the repo as it would provide a nice and easy way to integrate your on custom mode with objectron.

This feature would allow developers to do more than what the repo providers it will also help in understanding how 3D is used in mediapipe to Draw and understand the bounding boxes of a 2D image into 3D image.

**Comment by asus4** [comment]
Hi @nenenkosi ,

The output of the Objectron model is 2D keypoints. In MediaPipe, they use [Eigen library to convert 2D keypoints to 3D](https://github.com/google/mediapipe/blob/master/mediapipe/modules/objectron/calculators/decoder.cc).

![objectron_network_architecture](https://google.github.io/mediapipe/images/objectron_network_architecture.png)
https://google.github.io/mediapipe/solutions/objectron

And I hesitate to install such a big library for just using PnP solver in this sample project.

If you just need 2d keypoints, [this Objectron implementation in Barracuda](https://github.com/Kazuhito00/Unity-Barracuda-Objectron-WebGL) might be helpful.

**Comment by nenenkosi** [comment]
Thanks for the reply if it happens that you decide to include it please let us know coz it would make our life much easy thanks

**Comment by olokobayusuf** [comment]
Hey @asus4 @nenenkosi  , I'm also looking at adding Objectron support to [NatML](https://github.com/natsuite/NatML). Would you be interested in collaborating to implement the EPnP algorithm with just C# (and maybe the Burst compiler)?

**Comment by nenenkosi** [comment]
@olokobayusuf I don’t mind if you would do such you would be helping the community a lot and I would be highly appreciated

**Comment by asus4** [comment]
@olokobayusuf Yes, would be nice to have a PnP solver library for Unity!

**Comment by asus4** [comment]
The OpenCV for Unity plugin also has a PnP solver method. So would it be a good starting point to make an example with it?

**Comment by olokobayusuf** [comment]
> The OpenCV for Unity plugin also has a PnP solver method. So would it be a good starting point to make an example with it?

I explicitly don't want to add an OpenCV dependency, because it's massive and quite expensive. We can probably find a barebones EPnP implementation and port it over to C#

**Comment by nenenkosi** [comment]
@olokobayusuf if you need any kind of help or even someone to test I am available and if you run into any kind of problems I think you can feel free to ask @asus4 to assist coz he once did the EPnP implementation but it was for work so he might be able to assist you to solve bugs faster

**Comment by olokobayusuf** [comment]
Just wanted to update this thread. Objectron is almost implemented (using NatML instead of TFLite)
<img width="459" alt="Screen Shot 2021-09-18 at 1 55 05 PM" src="https://user-images.githubusercontent.com/17663473/133898117-cb2f3be8-d559-4254-b073-3ba18e2e1c50.png">
:

All that's left is lifting the 2D points to 3D using EPnP.

**Comment by nenenkosi** [comment]
@olokobayusuf thanks for the update a quick question is NatML better than TFLite in terms of speed and accuracy ?

And when do you think it will be available for testing coz am very excited to try it out and thanks for updating us on this thread
