### ISSUE TITLE
Apple Silicon, will not compile - unknown-unsupported file format 

### ISSUE THREAD

**Issue by lloydhooson** [asus4/tf-lite-unity-sample#144]
**Environment (please complete the following information):**
 - Mac, BigSur, 11.4 - Apple Silicon M1 macbook pro. 
 - Master branch as of 21/06/2021
 - Unity 2020.3.10f1

**Describe the bug**
Project built on Apple silicone mac will not compile with linker errors due to the following : 

ignoring file ../Frameworks/com.github.asus4.tflite/Plugins/iOS/TensorFlowLiteC.framework/TensorFlowLiteC, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )

and 

ignoring file ../Frameworks/com.github.asus4.tflite/Plugins/iOS/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )

Then a 30 errors similar to this of course:
Undefined symbol: _TFLGpuDelegateCreate
Undefined symbol: _TfLiteInterpreterOptionsAddDelegate
.........
Undefined symbol: _TfLiteInterpreterOptionsSetErrorReporter

**To Reproduce**
Steps to reproduce the behaviour:
Get Apple Silicon mac
Build unity, 
Build in Xcode 

**Expected behaviour**
To Build and run. 

**Additional context**
I have the same project on intel macbook pro and with same versions(expect OS 10.15) of all the project builds, and deploys to device no problems. 
I believe that upgrading to TenserFlow 4 with Apple silicone support may fix this issue.

**Comment by asus4** [comment]
Yes, it's actually an issue. But I can't test it right now as I'm waiting to buy an M1 mac until Apple releases 32GB memory model ;)

Any PRs to the [build script](https://github.com/asus4/tf-lite-unity-sample/blob/master/build_tflite.py) are appreciated.

**Comment by lloydhooson** [comment]
Further investigation, for iOS on apple silicon has lead me to have issues with LFS (big sur permissions), and therefore I had mangled tensorflow.so files making this issue.  After manually updating these files from this repo, XCode and iOS built and ran.
