### ISSUE TITLE
Mnist result not update

### ISSUE THREAD

**Issue by pp2015jp** [asus4/tf-lite-unity-sample#146]
Got the same problem
on WIndows 10, Tensorflow already installed

_Originally posted by @pp2015jp in https://github.com/asus4/tf-lite-unity-sample/issues/98#issuecomment-874486745_

It works on mobile devices. On has a problem on Windows

photo: https://ibb.co/dDPSp7z

Name: tensorflow
Version: 2.5.0

**Comment by asus4** [comment]
@pp2015jp Do you see any error logs? 
Does it occur on both Windows 10 Standalone and Unity Editor?

**Comment by pp2015jp** [comment]
Yes. Same result on both.

I found something that might a the cause.

It works on Android, iOS, Mac. But not Windows 10
This PC is laptop.
I tested on some PC of normal user (not programmer), it worked.
So I think it might be some hardware or GPU problem. I just guess.

**Comment by pp2015jp** [comment]
Standalone built on Windows also error with this

Exception: Unity.IL2CPP.Building.BuilderFailedException: tflite_unity_helper.cpp

tf-lite-unity-sample-master\Library\Il2cppBuildCache\Windows\x64\il2cppOutput\tflite_unity_helper.cpp(10): error C3861: 
tf-lite-unity-sample-master\Library\Il2cppBuildCache\Windows\x64\il2cppOutput\tflite_unity_helper.cpp(12): error C3861: 'va_end': identifier not found

**Comment by asus4** [comment]
Sorry for the late reply, 

Disabling `tflite_unity_helper.cpp` on windows would fix this kind of error. will commit it later

**Comment by asus4** [comment]
seems to be fixed in #156
