### ISSUE TITLE
Using OCR TFLite models

### ISSUE THREAD

**Issue by me-Stoffel** [asus4/tf-lite-unity-sample#147]
Hey,

first of all great work, image classification with TFLite models works great with this implementation in Unity. I'm currently trying to also do some OCR and wanted to try the converted models from here:
https://github.com/tulasiram58827/ocr_tflite

I have them set up using the BaseImagePredictor (with float as input), which works fine for the other models I trained for image classification. For these ones however I can't get it to work correctly. The LogIOInfo returns e.g.

intput 0: name: serving_default_input:0, type: Float32, dimensions: [1,31,200,1], quantizationParams: {scale: 0 zeroPoint: 0}
output 0: name: StatefulPartitionedCall:0, type: Float32, dimensions: [1,48,37], quantizationParams: {scale: 0 zeroPoint: 0}

Which makes me suspect that it expects grayscale images? Is there by chance already a way to pass the Texture from Unity using the ToTensor method so that it fits to that? 

Thanks and best regards
Stoffel

**Comment by asus4** [comment]
https://colab.research.google.com/github/tulasiram58827/ocr_tflite/blob/main/colabs/KERAS_OCR_TFLITE.ipynb#scrollTo=rkGs7BDWf6dm&line=9&uniqifier=1

![Screen Shot 2021-07-06 at 18 37 00](https://user-images.githubusercontent.com/357497/124636825-438afc80-de89-11eb-8943-c40de760e0a3.png)

Exactly, the input should be 
width: 200 
height: 31
channels: 1 (grayscale)

And TextureToTensor class only accepts RGB images at the moment. You need to tweak it for the grayscale input
