### ISSUE TITLE
Error loading native libraries when building on Linux for Android

### ISSUE THREAD

**Issue by Kalrog** [asus4/tf-lite-unity-sample#148]
**Environment :**
 - OS/OS Version: Pop!_OS(Linux)
 - Target: Android
 - Unity Version: Unity 2019.4.24f1

**Describe the bug**
When compiling for Android on Linux, native libraries do not load correctly.

**To Reproduce**
Compile to Android from Linux.

**Additional Notes:**
The same setup compiles correctly on a windows machine 

**Errors:**
07-08 14:49:38.354 27724 30923 D Unity   : Failed to load native plugin: Unable to load library '/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libnnapi_delegate.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "TfLiteDelegateCreate" referenced by "/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libnnapi_delegate.so"...'

07-08 14:49:38.359 27724 30923 D Unity   : Failed to load native plugin: Unable to load library '/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libtensorflowlite_gpu_delegate.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libtensorflowlite_gpu_delegate.so" has bad ELF magic: 76657273'

07-08 14:49:38.366 27724 30923 D Unity   : Failed to load native plugin: Unable to load library '/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libtensorflowlite_c.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~wCCPS4IuICH3lHQa8Py_2A==/com.asus4.tfliteunitysample-DqbBzBtBGHlj58yL6NW6Vg==/lib/arm64/libtensorflowlite_c.so" has bad ELF magic: 76657273'

Any ideas on how to fix this.

**Comment by asus4** [comment]
Can you confirm that your build setting is arm64 && il2cpp?
The error `has bad ELF magic`seems to be a kind of linker error. But not sure why it happens only on Linux build.

**Comment by Kalrog** [comment]
I have set the build settings to arm64 & il2cpp. It seems to be fixed now, but I don't know why. I changed the build settings to .NET 4.X and it seems to work now. Hope this helps someone at some point. Thank you for trying to help.
