### ISSUE TITLE
Fail to run my own sample after build.

### ISSUE THREAD

**Issue by guoguoguilai** [asus4/tf-lite-unity-sample#15]
The sample from this repo work perfect on Both Unity Editor and my Android phone. 
I am working on my own PoseNet by modifying some architecture and inputs(I don't think that matters). It works perfectly well in Unity Editor, but after build it just fails. 
At the beginning, I thought it might be the path issue. But I am sure that the .tflite file was placed in StreamingAssets folder. Then I dive into the logs from adb, I found those below:
`04-24 20:31:36.370: D/Unity(16500): Unable to lookup library path for 'libtensorflowlite_gpu_delegate', native render plugin support disabled.
04-24 20:31:36.370: E/Unity(16500): Unable to find libtensorflowlite_gpu_delegate
04-24 20:31:36.373: D/Unity(16500): Unable to lookup library path for 'libtensorflowlite_c', native render plugin support disabled.
04-24 20:31:36.374: E/Unity(16500): Unable to find libtensorflowlite_c`

But It occurs both in your samples and my code, so I don't think it is the main issue.
Then I found:
`04-24 20:31:39.215: I/Unity(16500): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-24 20:31:39.615: E/Unity(16500): Exception: Failed to create TensorFlowLite Interpreter
04-24 20:31:39.615: E/Unity(16500):   at TensorFlowLite.Interpreter..ctor (System.Byte[] modelData, TensorFlowLite.Interpreter+Options options) [0x00000] in <00000000000000000000000000000000>:0 
04-24 20:31:39.615: E/Unity(16500):   at TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) [0x00000] in <00000000000000000000000000000000>:0 
04-24 20:31:39.615: E/Unity(16500):   at PoseNet2..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
04-24 20:31:39.615: E/Unity(16500):   at MyPoseScript.Start () [0x00000] in `

I spent almost two days, trying to solve this problem but failed. Could you give me some advice? Any help will be appreciated.

**Comment by asus4** [comment]
The error shows that it failed to load native plugins `libtensorflowlite_c.so` and `libtensorflowlite_gpu_delegate.so`.  The native android plugins are built for only ARM64 CPU for now. It doesn't support ARMv7 refs #11

Or it might also help to test if Posenet model works on the official Android sample.
https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android

**Comment by guoguoguilai** [comment]
> The error shows that it failed to load native plugins `libtensorflowlite_c.so` and `libtensorflowlite_gpu_delegate.so`. The native android plugins are built for only ARM64 CPU for now. It doesn't support ARMv7 refs #11
> 
> Or it might also help to test if Posenet model works on the official Android sample.
> https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android

Thanks for your quick response! 
The CPU of my Android phone is ARM64-v8a. And I am also wondering why the sample from this repo works well in my phone even though throwed such error.

**Comment by guoguoguilai** [comment]
I am new to Tflite. I might make a stupid mistake. The privious tflite model cames from pb without quantization. After converting my pb model with a quantization option, the second error disappears. But the first error remains, which is strange.

**Comment by asus4** [comment]
sorry, I was misunderstood. In that case, I think the generated tflite model is not supported. If the model works on the official Android sample, you might want to try updating *.so library.

**Comment by justinw-fun** [comment]
> sorry, I was misunderstood. In that case, I think the generated tflite model is not supported. If the model works on the official Android sample, you might want to try updating *.so library.

But why this sample works well even though throw that error？ 
Maybe every time this error just occurs. The reason why nobody noticed that is no one look into adb log because their models work just fine.

**Comment by guoguoguilai** [comment]
> sorry, I was misunderstood. In that case, I think the generated tflite model is not supported. If the model works on the official Android sample, you might want to try updating *.so library.

But why this sample works well even though throw that error？
Maybe every time this error just occurs. The reason why nobody noticed that is no one look into adb log because their models work just fine.

**Comment by kaiquesacchi** [comment]
I've got the same problem. Adding my own model and scripts to the project provided by this repository works as expected, both in Windows and Android, but things go wrong when I try to start from a new Unity project and add the Tensorflow Lite package. Although it still works on Windows, I couldn't get it to work on Android. I got the following from the adb logcat:

```
11-11 14:57:24.089  2824  2841 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3679mb
11-11 14:57:24.089  2824  2841 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
11-11 14:57:24.089  2824  2841 I Unity   : ApplicationInfo com.DefaultCompany.Teste version 0.1 build 2b1208cc-4178-4be1-9df1-4beef7e8c6da
11-11 14:57:24.089  2824  2841 I Unity   : Built from '2019.4/staging' branch, Version '2019.4.13f1 (518737b1de84)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
11-11 14:57:24.239  2824  2841 E Unity   : Unable to find libtensorflowlite_gpu_delegate
11-11 14:57:24.239  2824  2841 E Unity   : Unable to find tensorflowlite_gpu_delegate
11-11 14:57:24.239  2824  2841 E Unity   : Unable to find libtensorflowlite_c
11-11 14:57:24.240  2824  2841 E Unity   : Unable to find tensorflowlite_c
11-11 14:57:24.240  2824  2841 E Unity   : Unable to find libnnapi_delegate
11-11 14:57:24.241  2824  2841 E Unity   : Unable to find nnapi_delegate
11-11 14:57:27.505  2824  2841 E Unity   : DllNotFoundException: libtensorflowlite_c
11-11 14:57:27.505  2824  2841 E Unity   :   at (wrapper managed-to-native) TensorFlowLite.InterpreterOptions.TfLiteInterpreterOptionsCreate()
11-11 14:57:27.505  2824  2841 E Unity   :   at TensorFlowLite.InterpreterOptions..ctor () [0x00006] in <459f6653717e4d59a43309de2f1a7b4d>:0
11-11 14:57:27.505  2824  2841 E Unity   :   at ImageClassificationScript.StartInterpreter () [0x00000] in <b45b00a36119449a939f993bc3151cc5>:0
11-11 14:57:27.505  2824  2841 E Unity   :   at ImageClassificationScript.Start () [0x00016] in <b45b00a36119449a939f993bc3151cc5>:0
```

**Comment by kaiquesacchi** [comment]
#77 
I had a similar problem, the solution provided by @ganaware might help you:

> I have had a similer problem.
> The cause of the problem is that Mono is the default scripting backend for a new unity project for Android.
> Unfortunately, Mono can run only for the ARMv7 architecture.
> 
> So my solution is that:
> 
> Project Settings > Player > Android > Other Settings > Configuration
> Select IL2CPP for Scripting Backend
> Uncheck ARMv7 and check ARM64 for Target Architectures
> Or, build my own TFLite library for ARMv7
> libnnapi_delegate.so, libtensorflowlite_c.so, libtensorflowlite_gpu_delegate.so
> They worked fine for me.
