### ISSUE TITLE
Exception: Failed to create TensorFlowLite Interpreter

### ISSUE THREAD

**Issue by YashNin** [asus4/tf-lite-unity-sample#151]
Exception: Failed to create TensorFlowLite Interpreter
TensorFlowLite.Interpreter..ctor (System.Byte[] modelData, TensorFlowLite.InterpreterOptions options) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:66)
TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) (at Packages/com.github.asus4.tflite.common/Runtime/BaseImagePredictor.cs:47)
TensorFlowLite.SSD..ctor (System.String modelPath) (at Assets/Samples/SSD/SSD.cs:22)
SsdSample.Start () (at Assets/Samples/SSD/SsdSample.cs:27)

Scene: SSD

Steps to reproduce: Train model and replace with default model in the scene "SSD"
[Feet Model.zip](https://github.com/asus4/tf-lite-unity-sample/files/7074872/Feet.Model.zip)

**Comment by asus4** [comment]
You can see the following warning on Editor:

```
TFLite Warning: Following operations are not supported by GPU delegate:
BROADCAST_TO: Operation is not supported.
CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
155 operations will run on the GPU, and the remaining 144 operations will run on the CPU.
```

This means BROADCAST_TO ops is not supported on GPU delegate. Disable GPU delegate.

And you need to change the output format as the outputs of the model are 4 floats
