### ISSUE TITLE
BlazePose tracking quality is not as good as the latest web demo

### ISSUE THREAD

**Issue by sonnybsj** [asus4/tf-lite-unity-sample#158]
**Environment:**
 - OS/OS Version: macOS, iOS, Windows
 - Source Version: master
 - Using the "Full" landmark model (but the issue should be applicable to the "lite" model as well.)
 
**Describe the bug**

While the BlazePose sample tracking works fairly well, it is not quite as good as the official web demos such as:

https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=blazepose
[Note: this demo currently does not run well on macOS Safari (use Chrome instead) or on iOS Safari (switch to tfjs-webgl)]

It is a bit worse in terms of tracking robustness and pose pick-up speed in certain cases.

For example, while BlazePose documentation states that the user's face must be visible, the web demo is able to maintain tracking even if the user's face is partially/mostly cut off, even as the user gets closer to the camera.

The Unity BlazePose sample scene does this to a certain extent, but it loses tracking much earlier than the web demo.

This is just one example. There are other cases where the web demo does a better job at tracking the pose (though they are harder to reproduce compared to my first example). For example, I've found that the pose is often slower to be picked up if the user is walking into the camera view from the sides.

**Additional context**

I will likely be looking more into this issue soon as it is important for the UX in my app's use case for the tracking to be as robust as possible, even if the user is only partially in the camera FoV.

I have already tried updating to the latest TFLite using `build_tflite.py`, as well as using the latest BlazePose pose detect model and pose landmark models.

For my next steps, I am trying to better understand all the pieces of the project to try to understand how it differs from the web demo.

I saw some minor differences in `BlazePoseSample.cs` as well as `PoseDetect.cs` compared to the [mediapipe pose_detection .pbtext files](https://github.com/google/mediapipe/tree/master/mediapipe/modules/pose_detection). For example, there are some threshold value differences and the commented out `NonMaxSuppression` method. But so far I haven't found anything that makes a significant difference to tracking robustness.

I would appreciate any hints as to where else I should look. (I am thinking about looking deeper at the code in `Packages/com.github.asus4.tflite` and `Packages/com.github.asus4.tflite.common`. and maybe at the web demo code itself.)

**Comment by asus4** [comment]
Adjusting some hard-coded parameters that refer to the old blazepose model can improve quality.
Parameters such as 
https://github.com/asus4/tf-lite-unity-sample/blob/bf61e938a48650e2ce1f14a18cb34e7f8260f7d2/Assets/Samples/BlazePose/BlazePoseSample.cs#L45-L46

https://github.com/asus4/tf-lite-unity-sample/blob/bf61e938a48650e2ce1f14a18cb34e7f8260f7d2/Assets/Samples/BlazePose/BlazePoseSample.cs#L89-L90
