### ISSUE TITLE
Can someone help me with portrait export? ANDROID

### ISSUE THREAD

**Issue by EmilioSantillana** [asus4/tf-lite-unity-sample#161]
Hi asus4, first of all let me say thank you for this samples using mediapipe in unity, they are helping me a lot.

Well the problem in cuestion is that i am  trying to compile into my phone the meet segmentation sample but when i do that the scene in my cellphone is very pixeled and with a weird zoom so i moved a little bit the code and with landscape mode works perfectly but when i put portrait mode the image does not rotate or it doesn't work as well...

I see that you post a solution script called "WebCam Input" but i don't know how it works or if that scripts will help me with that problem.

**Comment by asus4** [comment]
Hi @EmilioSantillana 

I have been migrating my examples to the `WebCamInput` version one by one. Please check `SSDSample,` which seems to be an easy example to understand its usage.
