### ISSUE TITLE
BlazePose WebCam canvas is extremely zoomed in on iOS devices

### ISSUE THREAD

**Issue by PriteshBooth** [asus4/tf-lite-unity-sample#172]
**Environment (please complete the following information):**
 - OS/OS Version: [e.g. iOS 11.0]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2021.15.1.f1]

**Describe the bug**

The camera view is extremely zoomed in both on unity and iOS. This wasnt the case before a few months ago, but the canvas on iOS is small and if scaled up, the camera is zoomed heavily on iOS devices. PLease suggest if there is a fix. I tried many things such as adjusting main camera to perspective or hardcoding the focus, nothing worked. All help appreciated. Thank you

**To Reproduce**
1. Clone repo, open Blazepose scene
2. Change buildsettings to iOS
3. Enlarge Canvas by scaling it 2x

**Comment by PriteshBooth** [comment]
This wasnt the case before a few months ago, but the canvas on iOS is small and if scaled up, the camera is zoomed heavily on iOS devices. PLease suggest if there is a fix. I tried many things such as adjusting main camera to perspective or hardcoding the focus, nothing worked. All help appreciated. Thank you

**Comment by asus4** [comment]
@PriteshBooth I didn't find that issue on my iPhoneXS (iOS 14.8). Does this also happen on the latest iOS devices? It might be a device or iOS version specific issue.

The WebCamInput component toggles the camera input each time you tap the top-left button; Please note that the active input is not the `Telephoto`.
