### ISSUE TITLE
BlazePose Sample Scene crashes Unity when Play Button is clicked

### ISSUE THREAD

**Issue by Ayush-0801** [asus4/tf-lite-unity-sample#176]
**Environment (please complete the following information):**
 - OS/OS Version: macOS 12.0.1
 - Source Version: master/v2.2.0
 - Unity Version: Unity 2020.3.22.f1

**Describe the bug**
Unity crashes instantaneously whenever the Blazepose Sample Scene is executed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Samples/BlazePose
2. Click on BlazePose Unity Scene
4. See error: Unity Crashes

**Expected behaviour**
The game should run smoothly with pose detection algorithms running in the background.

**Comment by asus4** [comment]
@Ayush-0801 Thanks for reporting. It seems to be running without any crash on my mac.

- macOS 12.0.1
- Unity 2020.3.11.f1

Can you share your Unity Editor log here?

![editor_log](https://user-images.githubusercontent.com/357497/141273629-323326ac-d4fa-44e9-9073-1cdf2b75bfe9.png)

**Comment by Ayush-0801** [comment]
@asus4 Fixed.

**Comment by asus4** [comment]
@Ayush-0801 Would you mind writing here how you figured out the error and fixed it for the community?
