### ISSUE TITLE
MoveNet Sample not working upon building the Unity App on iOS/Android

### ISSUE THREAD

**Issue by Ayush-0801** [asus4/tf-lite-unity-sample#177]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 15.0/Andoroid 11.1/macOS 12.0.1]
 - Source Version: Latest Commit
 - Unity Version: Unity 2020.3.22f1

**Describe the bug**
The Movenet library works well in the unity editor, but shows no detection after building the same in iOS as well as Android.

**Expected behavior**
Atleast, skeleton drawing in the app after building the Movenet Sample

**Comment by sonnybsj** [comment]
See [my comment](https://github.com/asus4/tf-lite-unity-sample/issues/145#issuecomment-978399236) in #145 as it could be related to your issue.

I recommend trying out #183.
