### ISSUE TITLE
Attempting to replace SSD tflite model. 

### ISSUE THREAD

**Issue by DaveSeidman** [asus4/tf-lite-unity-sample#178]
**Environment (please complete the following information):**
 - OS/OS Version: MacOS Big Sur
 - Source Version: Master
 - Unity Version: Unity 2020.3.14

**Describe the bug**
Apologies in advance, I'm new to this and hoping for guidance on how to swap a new tflite model into the SSD scene. I created a model following this code lab: https://www.tensorflow.org/lite/tutorials/model_maker_object_detection
and it's format is _similar_ but not the exactly the same as `coco_ssd_mobilenet_quant.tflite`
 
Here are both models' properties as shown in Netron (original on left, new on right): 
<img width="1003" alt="models" src="https://user-images.githubusercontent.com/975822/141683609-fdaccd5e-4bb2-4a14-ad65-1fff868e93b3.png">

`interpreter.Invoke();` works without error, but then 
`interpreter.GetOutputTensorData(0, outputs0);` throws an error: `Exception: TensorFlowLite operation failed.` 

Which I _think_ makes sense as the new outputs have different names, locations and properties from the original. My question is whether I can work with this new model as is, or if I need to re-export it and change some parameters during that process. Really enjoying this repo so thanks in advance for any help!

**To Reproduce**
Replace the original .tflite model in the SSD scene with a new one. 

**Expected behavior**
SSD would run the same as it does with the original model but getting output tensors would return labels from my new model.

**Comment by asus4** [comment]
@DaveSeidman You can find the actual output data structure in the Unity console. Please make sure it is the same as your mode. The count of outputs is 10 in the default but may be different in the custom model.

![output_size](https://user-images.githubusercontent.com/357497/141754083-34c6cfc2-4efb-4f88-afac-e64a231da367.png)

**Comment by Jokonut** [comment]
Hi @asus4, I tried to integrate the new SSD model from the official colab by modifying the ssd sample. It works well but impossible to retrieve the class id. The problem may come from the signature? Does anyone have a clue?
By the way, love this repo. Thank you for doing this !

**Comment by asus4** [comment]
@Jokonut Thanks for using this repository. 

Which colab file did you try? Also would be easy to reproduce it if you could share the tflite file.

https://www.tensorflow.org/lite/models/modify/model_maker/object_detection
https://github.com/tensorflow/models/tree/master/research/object_detection/colab_tutorials

**Comment by Jokonut** [comment]
I tried this [link] (https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb), with the tflite file produce by this collab [tflite file](https://www.dropbox.com/s/a6ddijear7qdmuj/lite-model_efficientdet_lite0_int8_2.tflite?dl=1 ) Thank again for being so responsive !

**Comment by Jokonut** [comment]
I found the solution by replacing the lines         
```
ToTensor(inputTex, inputTensor);
interpreter.SetInputTensorData(0, inputTensor);
interpreter.Invoke();
interpreter.GetOutputTensorData(0, outputs0);
interpreter.GetOutputTensorData(1, outputs1);
interpreter.GetOutputTensorData(2, outputs2);
```
by
```
ToTensor(inputTex, inputTensor);
runner.SetSignatureInputTensorData(IMAGE_INPUT_NAME, inputTensor);
runner.Invoke();

runner.GetOutputTensorData(0, outputs1);
runner.GetOutputTensorData(1, outputs0);
runner.GetSignatureOutputTensorData((string)runner.GetSignatureOutputName(2), outputs2);
```
and referring to the videoclassification script for the signature integration.

**Comment by asus4** [comment]
Good to hear you fixed it. 

In this case, probably it runs without the new signature API. The signature API is a feature that allows the TFLite model to have multiple entry points and name the I/O. If the model has a single entry point, `BaseImagePredictor.cs` should work.

**Comment by asus4** [comment]
@Jokonut  Confirmed the similar error with the default SSD model. It looks like TensorFlow's Metal delegate error.

Opened a new issue here -> #234

**Comment by lakpa-tamang9** [comment]
I had the same issue but my output dimensions are null. How is this possible? 
<img width="845" alt="Screen Shot 2023-01-09 at 11 37 27 AM" src="https://user-images.githubusercontent.com/54692758/211233192-c80bc606-aeba-461e-9dd3-7896f468e4d3.png">
