### ISSUE TITLE
Using multiple dimensions as input tensor

### ISSUE THREAD

**Issue by twister11211** [asus4/tf-lite-unity-sample#179]
Is there a way to use a multi dimensional array as the input of a model I managed to get it to work with a onnx model in C# like this
using System.Numerics.Tensors; 
int[] dimensions2D = {1,24};
int[] input0 = new int[] {57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148};
Tensor<int> T_input0 = new DenseTensor<int>(input0, dimensions2D);

when I run interpreter.SetInputTensorData(0, T_input0);
I get the error:     cannot convert from 'System.Numerics.Tensors.Tensor<int>' to 'System.Array'

I have also tried 
int[][] arrayA = new int[1][];
arrayA[0] = new int[] {57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148};
but when I set input tensor  I get the error ArgumentException: Object must be an array of primitives.

I can run the tflite model in python using numpy.expand_dims(input0, axis=0) which expands the dimensions of a array in this case 
from [57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148]
to [[57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148]]

**Comment by asus4** [comment]
[Jagged Array](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/jagged-arrays) won't able to use as input. Can you try using [Multidimensional Arrays](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays) instead?

```c#
// Multidimensional array
int[] input = new int[1, 24] {{57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148}};

// or simple array might work in this case
int[] input = new int[24] {57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148};
```

**Comment by twister11211** [comment]
// Multidimensional array
int[,] input = new int[1, 24] {{57, 45, 46, 56, 11, 46, 56, 11, 38, 11, 57, 42, 56, 57, 11, 56, 42, 51, 57, 42, 51, 40, 42, 148}};

Has got my array formatted correctly thank you
