### ISSUE TITLE
Crash on Android [Samsung Galaxy S10]

### ISSUE THREAD

**Issue by bawahakim** [asus4/tf-lite-unity-sample#180]
**Environment (please complete the following information):**
 - OS/OS Version: Samsung Galaxy S10 SM-G9730 Android  v11
 - Source Version: [master/v2.4.0]
 - Unity Version: [Unity 2020.3.11.f1]

**Describe the bug**
Android app crashes using Blaze Pose sample scene from the project.

**To Reproduce**

    1. Clone this repo
    2. Make sure the only scene in build is Samples/BlazePose/BlazePose
    3. Install `Android Logcat` package from Unity to monitor the log (optional)
    4. Make sure Target CPU architecture is set to ARM64 (uncheck ARMv7)
    5. Make sure backend scripting is set to IL2CPP
    4. Make an Android build and run

I've also tried building the latest Tensorflow for Android but the same issue happens. Works for me in Editor, Standalone and iOS

**Expected behavior**
It should not crash.

Crash Log attached
[crash-log.txt](https://github.com/asus4/tf-lite-unity-sample/files/7543185/crash-log.txt)

**Comment by asus4** [comment]
Thanks for reporting it. I will check on my Android later. @bawahakim It would be helpful if you could check whether it reproduces with another Android.

**Comment by Gulfick** [comment]
Very strange error, at first everything worked. Now it reproduces all the time. Crashes in PoseDetect, on the call:
public async UniTask<Result> InvokeAsync(Texture inputTex, CancellationToken cancellationToken, PlayerLoopTiming timing = PlayerLoopTiming.Update) 
On the first line:
await ToTensorAsync(inputTex, input0, cancellationToken);
And in this line:
interpreter.Invoke();
If you commit the lines, the application doesn't crash.

And the error is reproduced in certain projects. I have three projects that are exactly the same in PoseDetect logic. One is just copied from the guitar - it crashes, the second - a little sample was changed, but the call order is the same - it doesn't crash, the third - sample was changed a little bit stronger, but the call order is not changed - it crashes.

**Comment by bawahakim** [comment]
Tried on Samsung Galaxy S20 SM-G981N, same error, but I think there's one more line in the crash: 
`2021-11-17 18:27:51.103 3637 4519 Error libc Access denied finding property "ro.vendor.gfx.32bit.target"`

[crash-galaxy-s20.txt](https://github.com/asus4/tf-lite-unity-sample/files/7553411/crash-galaxy-s20.txt)

**Comment by IlyaKrotov** [comment]
@asus4 I got the same problem. Any ideas?

**Comment by asus4** [comment]
I assume this crash is introduced by GCHandle changes in #175.
Could you try to see if this solves your crashes?
@IlyaKrotov @bawahakim @Gulfick

**Comment by Gulfick** [comment]
@asus4 Thanks! Tested on two phones - everything works

**Comment by asus4** [comment]
Thanks @Gulfick,  Merged it now

**Comment by bawahakim** [comment]
Works for me as well, thanks @asus4! :)

**Comment by bawahakim** [comment]
Did more test, although blaze pose is working, this change is somehow breaking our own implementation of our model. Unfortunately I cannot share the project, but from my tests it looks like the `output0` is always constant from the first frame picked up, and then does not update. This happens in the editor as well, while previously it worked.

**Comment by sonnybsj** [comment]
@bawahakim maybe you can try reverting parts of the new change to isolate the issue?

Note that your findings with reverting to pre #174 and #175 is consistent with my findings in https://github.com/asus4/tf-lite-unity-sample/issues/145#issuecomment-978399236

i haven’t had any issues with the latest change, but I’ll report if something comes up.
