### ISSUE TITLE
SIGSEGV signal w/ external camera

### ISSUE THREAD

**Issue by antoineheseque** [asus4/tf-lite-unity-sample#181]
**Environment:**
 - OS/OS Version: Windows 10
 - Source Version: master
 - Unity Version: Unity 2020.3.22f1

**Describe the bug**
In play mode, Unity crash after a few seconds (~20s) when using my external camera (Logitech C922 Pro) instead of the integrated HD one in my laptop. I tried it in the MoveNet demo scene and a personal one (based on MoveNet too).

**To Reproduce**
1. Go to the MoveNet demo scene.
2. Click on MoveNet sample and change the editor camera name to the external one.
3. Press Play and wait 20s ~.

**Additional context**
It does work perfectly when building the project.

[filtered_Editor.log](https://github.com/asus4/tf-lite-unity-sample/files/7545508/Editor.log)

**Comment by sonnybsj** [comment]
See [my comment](https://github.com/asus4/tf-lite-unity-sample/issues/145#issuecomment-978399236) in #145 as it could be related to your issue.

I recommend trying out #183.
