### ISSUE TITLE
MoveNet Draws Skeleton on the Edge of the Screen on iOS Device

### ISSUE THREAD

**Issue by cagri-beep** [asus4/tf-lite-unity-sample#182]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 14.7.1 (iPhone 11 Pro)
 - Source Version: master/2.4.0
 - Unity Version: 2020.3.11f

**Describe the bug**
MoveNetSinglePose sample behaviour is different in iOS than it is in the editor. The skeleton is drawn on the edge of the screen instead of on detected person's body/face.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone master repo.
2. Open with Unity 2020.3.11f with target set to iOS
3. Navigate to Samples > MoveNet > MoveNetSinglePose and open the scene. 
4. Click File > Build Settings (Switch target to iOS if it is different)
5. Select All scenes  in build settings and delete them.
6. Add MoveNetSinglePose scene to build settings (by clicking add open scenes button).
7. Build and run the sample on iPhone.
8. Accept camera permissions (it'll crash because of the camera permissions)
9. Close the app
10. Open the app again

**Expected behaviour**
Skeleton drawing on detected body instead of at the edge of the screen.

**Screenshots**

Expected Behaviour (In Unity Editor Screen Shot)
<img width="287" alt="Screenshot 2021-11-17 at 15 31 11" src="https://user-images.githubusercontent.com/81677078/142222306-0feb2bba-84a3-40a1-96b7-2c0ccdedbd04.png">

Buggy Behaviour (iOS Device iPhone 11 Pro  Screen Shot) Drawn line is visible at the lower right corner.
![img_0277 (1)](https://user-images.githubusercontent.com/81677078/142225379-e06e2727-4d2e-4417-bab3-d492d49f9204.jpg)

**Additional context**
Lines are drawn regardless if there is a body/face in camera feed or not.

**Comment by sonnybsj** [comment]
See [my comment](https://github.com/asus4/tf-lite-unity-sample/issues/145#issuecomment-978399236) in #145 as it could be related to your issue.

I recommend trying out #183.

**Comment by cagri-beep** [comment]
Yep, #183 fixed the issue. Thanks for notifying me @sonnybsj
