### ISSUE TITLE
Unitty Webgl build 

### ISSUE THREAD

**Issue by anshulAgarrwal** [asus4/tf-lite-unity-sample#188]
Hello I am using unity version 2020.3.14
I want to build this library for webgl but getting this issue.

To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking
  | printErr | @ | TF_Car.loader.js:1
-- | -- | -- | --
  | abort | @ | TF_Car.framework.js:2
  | _dlopen | @ | TF_Car.framework.js:2
  | $func48335 | @ | TF_Car.wasm:0xfceb3f
  | $func48333 | @ | TF_Car.wasm:0xfceaa3
  | $func49673 | @ | TF_Car.wasm:0x1007d5a
  | $func47290 | @ | TF_Car.wasm:0xf9c43b
  | $func47289 | @ | TF_Car.wasm:0xf9c3d2
  | $func47286 | @ | TF_Car.wasm:0xf9c2d9
  | $func27025 | @ | TF_Car.wasm:0xbafb35
  | $func27835 | @ | TF_Car.wasm:0xbdfe7d
  | $func42537 | @ | TF_Car.wasm:0xeae230
  | $func42541 | @ | TF_Car.wasm:0xeaeec3
  | $func24493 | @ | TF_Car.wasm:0xb68bde
  | $dynCall_iiiii | @ | TF_Car.wasm:0x104ad97
  | (anonymous) | @ | TF_Car.framework.js:2
  | invoke_iiiii | @ | TF_Car.framework.js:2
  | $func48839 | @ | TF_Car.wasm:0xfe59f2
  | $func48283 | @ | TF_Car.wasm:0xfcd555
  | $func4293 | @ | TF_Car.wasm:0x19dc9a
  | $func4291 | @ | TF_Car.wasm:0x19d96a
  | $func8273 | @ | TF_Car.wasm:0x2ff783
  | $func8271 | @ | TF_Car.wasm:0x2fe6a4
  | $func10325 | @ | TF_Car.wasm:0x3c2a0b
  | $func8507 | @ | TF_Car.wasm:0x31973c
  | $func10748 | @ | TF_Car.wasm:0x3f1adf
  | $func10427 | @ | TF_Car.wasm:0x3cc28b
  | $func10427 | @ | TF_Car.wasm:0x3cc2a0
  | $func10422 | @ | TF_Car.wasm:0x3cbe25
  | $func10415 | @ | TF_Car.wasm:0x3ca22e
  | $dynCall_v | @ | TF_Car.wasm:0x104afc7
  | (anonymous) | @ | TF_Car.framework.js:2
  | browserIterationFunc | @ | TF_Car.framework.js:2
  | runIter | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2
  | requestAnimationFrame (async) |   |  
  | requestAnimationFrame | @ | TF_Car.framework.js:2
  | Browser_mainLoop_scheduler_rAF | @ | TF_Car.framework.js:2
  | Browser_mainLoop_runner | @ | TF_Car.framework.js:2

DllNotFoundException: Unable to load DLL 'libtensorflowlite_c': The specified module could not be found.
Please help me with this

**Comment by asus4** [comment]
Hi @anshulAgarrwal
This library depends on many platform-dependent native codes, so it seems difficult to support WebGL.

Consider using [Unity Barracuda](https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/index.html) or [TensorFlow JS](https://www.tensorflow.org/js)

See similar issue #165

**Comment by AnshulGoyalCooee** [comment]
@asus4 thank you for this help

**Comment by anshulAgarrwal** [comment]
@asus4 Thanks for you help.
