### ISSUE TITLE
Custom Ops Support

### ISSUE THREAD

**Issue by ragavendranbala** [asus4/tf-lite-unity-sample#19]
Hi ,I need to know does this plugin support custom ops. I tried to load https://github.com/google/mediapipe/blob/master/mediapipe/models/hair_segmentation.tflite file in intepreter it showed error. I tried to load in tensorflow it showed custom ops are not supported. I'm struck here. Can you help me to load this tflite model in Unity?

Thanks in advance

**Comment by asus4** [comment]
Hi @ragavendranbala, I am also interested in supporting MediaPipe. This does not support the custom ops. but it could work if these APIs were implemented.

https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/lite/c/c_api_experimental.h

https://www.tensorflow.org/lite/guide/ops_custom

**Comment by ragavendranbala** [comment]
Hi @asus4 it's need to fixed by tensorflow? by ourselves ?

**Comment by asus4** [comment]
@ragavendranbala I think it’s better to implement it ourselves since the TFLite team isn't active in updating UnityPlugin.
