### ISSUE TITLE
Does Posenet Model Port allows Multi-Pose Detection in this repository? if yes, then how?

### ISSUE THREAD

**Issue by Ayush-0801** [asus4/tf-lite-unity-sample#191]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 11.0
 - Source Version: Latest Release
 - Unity Version: Unity 2020.27.1.f1

**Describe the bug**
No multi pose detection is posenet model

**Comment by asus4** [comment]
Hi @Ayush-0801, it is not implemented in this repository yet. Please refer to #104 for more.
