### ISSUE TITLE
no example for audio classification? 

### ISSUE THREAD

**Issue by kotran88** [asus4/tf-lite-unity-sample#194]
I was inspired by tflite's sample's audio classification but can't find it on unity version...
on the repo too don't have audio classification but image..
can anyone do that?

**Comment by asus4** [comment]
Yeah, it would be nice to have an example for audio.

Probably this sample works on Unity as well.
https://www.tensorflow.org/lite/examples/audio_classification/overview

I don't have much time to do it now, but I will try when I have spare time.
