### ISSUE TITLE
DllNotFoundException: libtensorflowlite_c

### ISSUE THREAD

**Issue by kotran88** [asus4/tf-lite-unity-sample#195]
when I run on unity editor, it says

DllNotFoundException: libtensorflowlite_c
and when I run it on my android device, 
it works but 
it stuck with 
 var options = new InterpreterOptions()

what may be the problem ? 

I saw https://github.com/asus4/tf-lite-unity-sample/issues/77

and try change IL2CPP for scripting Backend and check arm64. 
but it remain same. 
I'm Mac m1 MacBook

**Comment by asus4** [comment]
Please follow the issue template. We need detailed information about your PC's environment, Editor Version to identify the issue.

**Comment by kotran88** [comment]
@asus4  it works for me just update latest version of unity editor to 2021 version.
