### ISSUE TITLE
The example on Youtube doesn't run well

### ISSUE THREAD

**Issue by ChenYiyangSJTU** [asus4/tf-lite-unity-sample#197]
**Environment (please complete the following information):**
 - OS/OS Version: Windows10
 - Source Version: master
 - Unity Version: Unity 2021.1.26f1c1

**Describe the bug**
I followed instructions on https://www.youtube.com/watch?v=s42RTgKSXis&t=580s to make a simple linear regressor. First click gives correct response in Debug, but later clicks just lead to 0s as output. I wonder if the problem is due to the tensorflow version.

**I provide the C# code used in the video, FirstPrediction.cs, right below, to facilitate your check*

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TensorFlowLite;
using UnityEngine.UI;

public class FirstPrediction : MonoBehaviour
{
    [SerializeField] string FileName = "linearPred.tflite";
    [SerializeField] Text outputTextView = null;
    [SerializeField] Button button = null;
    [SerializeField] InputField InputField = null;

    Interpreter interpreter;
  
    void Start()
    {
        var options = new InterpreterOptions()
        { threads = 4, };
        interpreter=new Interpreter(FileUtil.LoadFile(FileName),options);
        
        interpreter.AllocateTensors();
        button.onClick.AddListener(OnbuttonClick);
    }

 

    private void OnDestroy()
    {
        interpreter.Dispose();
    }

    public void OnbuttonClick()
    {
        doInference(InputField.text);
     
    }

    public void doInference(string val)
    {
        float[] input = new float[1];
        input[0] = float.Parse(val);
        Debug.Log(input[0]);
        float[] output = new float[1];
        

        interpreter.SetInputTensorData(0, input);
        interpreter.Invoke();
        interpreter.GetOutputTensorData(0, output);
        for(int i = 0; i < output.Length; i++)
        {
            Debug.Log(output[i]);
            outputTextView.text = output[i].ToString();
        }

       
    }
}

**Screenshots**
![image](https://user-images.githubusercontent.com/96412435/156355727-a56f328e-e9c4-4a8b-925e-15a859578f60.png)

**Comment by asus4** [comment]
@ChenYiyangSJTU Can you provide the model and the collab link you trained?

**Comment by ChenYiyangSJTU** [comment]
Surely! Here I attach the exported models and the ipython file. You may check it in colab.

Best!
















--

________________________________________________

Chen Yiyang
Technician

East China Normal University
Cellphone: 086-15800967390








At 2022-03-02 20:15:11, "Koki Ibukuro" ***@***.***> wrote:

@ChenYiyangSJTU Can you provide the model and the collab link you trained?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChenYiyangSJTU** [comment]
Colab link

https://colab.research.google.com/drive/1RR5z9UCY8P1QeJeQ_rnCE5uY7OhBnvfM?usp=sharing

Thank you for your opinion.
