### ISSUE TITLE
DllNotFoundException: libtensorflowlite_c

### ISSUE THREAD

**Issue by yashkhandelwal2006** [asus4/tf-lite-unity-sample#199]
**Environment (please complete the following information):**
 - OS/OS Version: MacOS version 12.2.1
 - Source Version: Master
 - Unity Version: 2020.3.30f1

**Describe the bug**
I am constantly getting the following error logs: 
    DllNotFoundException: libtensorflowlite_c
    TensorFlowLite.InterpreterOptions..ctor () (at Packages/com.github.asus4.tflite/Runtime/InterpreterOptions.cs:60)
    TensorFlowLite.Bert..ctor (System.String modelPath, System.String vocabText) (at Assets/Samples/Bert/Bert.cs:82)
    BertSample.Start () (at Assets/Samples/Bert/BertSample.cs:47)

Please let me know how should I fix this issue, as I can clearly see "libtensorflowlite_c" file inside packages but keep getting the above error.

**Comment by bawahakim** [comment]
This is generally an issue with dependencies. Are you running a M1 mac by any chance?

**Comment by yashkhandelwal2006** [comment]
@bawahakim I am using an Intel Mac

**Comment by asus4** [comment]
@yashkhandelwal2006 
When you start playing UnityEditor, is there anything on your `System Preferences / Security & Privacy / General` tab?
If so, please click "Allow" and restart Editor. And I would appreciate it if you could capture that screen. It didn't reproduce on my mac.

<img width="668" alt="Screenshot 2022-03-04 at 09 21 44" src="https://user-images.githubusercontent.com/357497/156726474-41d1c8b3-4fee-4e83-9317-7356c10a5cc2.png">

**Comment by yashkhandelwal2006** [comment]
@asus4 Please check this out, Nothing in the system preferences.
<img width="1792" alt="Screenshot 2022-03-04 at 2 13 10 PM" src="https://user-images.githubusercontent.com/48640007/156729835-3b946897-458e-4bfd-913f-e7be772165e1.png">

**Comment by asus4** [comment]
Thanks, Have you checked out with `git-lfs`? If so, no ideas for fixes. Could not reproduce that on my Editor.

**Comment by yashkhandelwal2006** [comment]
@asus4  thanks for helping. I cloned with git-lfs installed but the problem was I had to run the following command separately inside the repository. After running this command everything looks fine.

`git lfs install`

**Comment by sonnybsj** [comment]
@tinkertailorsoldierspy I had a similar issue in my project but I wasn't able to reproduce it on the latest version of this repo. If you're not on the latest version, try updating your project.

You may find it useful to test with the Intel 64-bit [target architecture build option](https://docs.unity3d.com/Manual/macos-building.html) and use that as a temporary workaround.

**Comment by asus4** [comment]
Thanks @sonnybsj. @tinkertailorsoldierspy The latest macOS `libtensorflowlite_c.dylib` and `libtensorflowlite_metal_delegate.dylib` are build as universal binary. I confirmed it runs with:
- M1 Max + Unity 2021.3.5f1 `SILICON` build
- M1 Max + Unity 2020.3.36f1 `INTEL` build

Please make sure that these dylibs in the path `Packages/com.github.asus4.tflite/Plugins/macOS/` have been installed correctly. file sizes are roughly 9.3MB and 4.9MB.
