### ISSUE TITLE
Regarding FaceMesh inference

### ISSUE THREAD

**Issue by pytholic** [asus4/tf-lite-unity-sample#209]
Hi. Thank you for the repo.

I am trying to convert your example [here](https://github.com/asus4/tf-lite-unity-sample/blob/master/Assets/Samples/FaceMesh/FaceMeshSample.cs) to use images from the directory instead of taking camera frames as input.

However, I am having difficulty converting the code and am not sure how to do it. Can you guide me a bit?

**Comment by asus4** [comment]
@pytholic You can pass your Texture2D images to `OnTextureUpdate` instead of texture from webcam.
