### ISSUE TITLE
Adding custom class in SSD object detection  

### ISSUE THREAD

**Issue by WizphysAi** [asus4/tf-lite-unity-sample#218]
Hey, thank you for providing such a great repo. 
I wanted to add a custom class in the SSD object detection project, can you please tell me exactly which model did you used for this project, I will use transfer learning on that, this way I will not need to make much changes in the current code.

**Comment by asus4** [comment]
Hi @WizphysAi,

Here's the link to the model that I used in this repo. Click "[Download starter model with Metadata](https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/1?lite-format=tflite)" on this page.
https://www.tensorflow.org/lite/examples/object_detection/overview

Also, there is some info about the model customizing and fine-tuning.

**Comment by WizphysAi** [comment]
Thanks
