### ISSUE TITLE
Blazepose Wrist and Ankle Angles

### ISSUE THREAD

**Issue by tolgak99** [asus4/tf-lite-unity-sample#223]
**Environment (please complete the following information):**
 - OS/OS Version: macOS 12.0.1
 - Source Version: master/v2.8.0
 - Unity Version: Unity 2021.3.3f1

**Describe the bug**
In BlazePose scene detection can not detect wrist and ankle angels clearly as MediaPipe Web Demo.

**To Reproduce**
1. Go to 'BlazePose Scene'
2. Import  'pose_landmark_heavy.tflite'
3. Try to see ankle and wrist angles

**Expected behavior**
I need to get ankle and wrist angles degree. 

**Additional context**
Thanks for this repo, examples are clear and works well. 

**Screenshots**
You can see difference between web demo and unity version.

**Unity Version**
![Screen Shot 2022-06-01 at 09 40 45](https://user-images.githubusercontent.com/47540955/171352364-4a40fcbb-5d56-4f34-b9c2-77beb41343fc.png)

**Web Demo**
![Screen Shot 2022-06-01 at 10 15 58](https://user-images.githubusercontent.com/47540955/171352385-1266b80e-9a6f-49c7-8823-b2cdf1355dae.png)

**Comment by asus4** [comment]
@tolgak99 Thanks for reporting. Can you please share the URL of the web-demo? will check it.

**Comment by asus4** [comment]
Reproduced it on my mac. And the following modifications did not fix it. it might be an issue in C# pre/post-processing.

- Disable quantization in MetalDelegate
https://github.com/asus4/tf-lite-unity-sample/blob/4ed29ea1642ef82f1da0a37e55ea2d7c0e4d7077/Packages/com.github.asus4.tflite/Runtime/InterpreterOptions.cs#L101

- Change Accelerator to `Accelerator.NONE`
https://github.com/asus4/tf-lite-unity-sample/blob/4ed29ea1642ef82f1da0a37e55ea2d7c0e4d7077/Assets/Samples/BlazePose/PoseLandmarkDetect.cs#L84
