### ISSUE TITLE
error when blaze pose sample is run with run background enabled

### ISSUE THREAD

**Issue by unitedevop** [asus4/tf-lite-unity-sample#225]
**Environment (please complete the following information):**
 - windows
 - latest master branch
 - Unity 2020.3.30f1

**Describe the bug**
when I run blaze pose sample with run background enabled then a error like this comes up
(UnityException: InternalSetData can only be called from the main thread.)

**exact error log**
UnityException: InternalSetData can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.ComputeBuffer.SetData (System.Array data) (at <3be1a7ff939c43f181c0a10b5a0189ac>:0)
TensorFlowLite.PoseSegmentation.GetTexture (UnityEngine.Texture inputTex, TensorFlowLite.TextureResizer+ResizeOptions resizeOptions, UnityEngine.Matrix4x4 cropMatrix, System.Single[,] data, System.Single sigmaColor) (at Assets/Samples/BlazePose/PoseSegmentation.cs:74)
TensorFlowLite.PoseLandmarkDetect.GetResult (UnityEngine.Texture inputTex) (at Assets/Samples/BlazePose/PoseLandmarkDetect.cs:238)
TensorFlowLite.PoseLandmarkDetect+<InvokeAsync>d__20.MoveNext () (at Assets/Samples/BlazePose/PoseLandmarkDetect.cs:155)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@9e2163616b/Runtime/CompilerServices/StateMachineRunner.cs:342)
TensorFlowLite.BlazePose+<InvokeAsync>d__19.MoveNext () (at Assets/Samples/BlazePose/BlazePose.cs:93)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@9e2163616b/Runtime/CompilerServices/StateMachineRunner.cs:342)
BlazePoseSample+<InvokeAsync>d__18.MoveNext () (at Assets/Samples/BlazePose/BlazePoseSample.cs:105)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Library/PackageCache/com.cysharp.unitask@9e2163616b/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.ExceptionHolder:Finalize() (at Library/PackageCache/com.cysharp.unitask@9e2163616b/Runtime/UniTaskCompletionSource.cs:66)

**additional information**
I also have a missing script on main camera it should not effect anything but curious why so??
by the way I have the camera texture background script on camera.

(love this project, thank you)

**Comment by unitedevop** [comment]
@asus4  can I get some help with issue

**Comment by asus4** [comment]
@unitedevop Segmentation with background thread is not supported at the moment. Disable the Segmentation option when running in bg-thread.
