### ISSUE TITLE
Ios don't build after update from 2.8.0 to 2.9.1

### ISSUE THREAD

**Issue by Gulfick** [asus4/tf-lite-unity-sample#236]
- OS/OS Version: don't build on iOS
 - Source Version: v2.9.1 from https://registry.npmjs.com
 - Unity Version: 2020.3.27f1

After upgrading from version 2.8.0 to 2.9.1, the ios build stopped building.
In Unity Cloud the following error:
`539: [2022-07-14T09:51:15Z - Unity]     com.github.asus4.mediapipe: Cannot connect to 'registry.npmjs.org' (error code: ECONNRESET). Verify your environment firewall policies allow connection to this host name. If your system is behind a proxy, verify your proxy environment variables (HTTP_PROXY and HTTPS_PROXY) are properly set.`

Android on v.2.9.2 builds good and there is no problem in editor. v2.8.0 builds fine on all platforms.

Found tip that "url": "https://registry.npmjs.com" can work only like that "url": "http://registry.npmjs.com". Tried that and had the same result.

1. Update to 2.9.1
2. Try to build on iOS through cloud build.
3. See error

**Comment by asus4** [comment]
Maybe you mean `v2.9.1` ?

I guess the npmjs error is not related to iOS's error. In this commit https://github.com/asus4/tf-lite-unity-sample/pull/233/commits/152351f3d343a537cc6d20119061d7f581973b82 , I fixed the Metal linker error, but it has not been released though. will make a patch release for iOS later.

**Comment by Gulfick** [comment]
Yes I'm sorry of course `v2.9.1`

It will be great if this patch will help us to build ios. I don't know how npmjs is related to Metal linker, but I will count on you :3

**Comment by asus4** [comment]
Hi, @Gulfick  Uploaded patch releases to the npm and succeeded in iOS build with this version. Would you mind trying this?

```json
"dependencies": {
    // Core TensorFlow Lite libraries
    "com.github.asus4.tflite": "2.9.1-p1",
    // Utilities for TFLite
    "com.github.asus4.tflite.common": "2.9.1-p1",
    // Utilities for MediaPipe
    "com.github.asus4.mediapipe": "2.9.1-p1",
    ...// other dependencies
  }
```

**Comment by Gulfick** [comment]
Thank you @asus4 ! ios built smoothly

**Comment by asus4** [comment]
🎉  Thanks for reporting this issue.
