### ISSUE TITLE
Custom Model : https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb

### ISSUE THREAD

**Issue by taeyeonlee** [asus4/tf-lite-unity-sample#237]
Environment (please complete the following information):
OS/OS Version: Windows
Source Version: master, v 2.9.1
Unity Version: Unity 2020.3.29.f1

Hi, 

When using the model.tflite which was generated in the (https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb),
your SSD Unity sample (tf-lite-unity-sample\Assets\Samples\SSD) doesn't run with the following error.

Could you please share how to make it work ?

Error log ------------------------------------------------------------------------------------------------------------------------
Exception: TensorFlowLite operation failed.
TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:221)
TensorFlowLite.Interpreter.SetInputTensorData (System.Int32 inputTensorIndex, System.Array inputTensorData) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:122)

Best regards,

**Comment by asus4** [comment]
Hi @taeyeonlee would you mind uploading the model here? I got an error running the ipynb on google collab, it is a bit outdated.

Also, please refer to similar issues such as #178 

I guess the input of the model is float32 or float16. the input of this example is quantized to int8.

**Comment by asus4** [comment]
The exported model's input type is `float32`. You need to use the same input/output types.
 
![Screenshot 2022-07-18 at 13 43 52](https://user-images.githubusercontent.com/357497/179504454-a2da6bf5-a875-4105-b32d-80432607aa61.png)

**Comment by taeyeonlee** [comment]
Hi @asus4,   
Could you please share how to use the same input/output types ?

**Comment by asus4** [comment]
no, please refer to similar issues such as #4 #7 #89 #178

**Comment by taeyeonlee** [comment]
Hi @asus4, thank you very much for your answer.
As you said,  I added the conversion (Post-training quantization) to use the same input/output types,  according to https://www.tensorflow.org/lite/performance/post_training_quantization.
It's working well.

**Comment by asus4** [comment]
Congrats! Now closing this issue. Feel free to reopen it if you get more issues.

**Comment by bertafmorena** [comment]
> Hi @asus4, thank you very much for your answer. As you said, I added the conversion (Post-training quantization) to use the same input/output types, according to https://www.tensorflow.org/lite/performance/post_training_quantization. It's working well.

Could you pls share how to do the conversion to use the same input/output types?

**Comment by great-energizer** [comment]
@taeyeonlee 
Could you pls share how to do the conversion to use the same input/output types?

안녕하세요. Input과 output type을 어느 옵션으로 양자화하셨는지요?

**Comment by tabatinga0x00** [comment]
>The exported model's input type is float32. You need to use the same input/output types.

What application is that?

**Comment by asus4** [comment]
@tabatinga0x00 
I'm using Netron to investigate the model.

https://netron.app/
https://github.com/lutzroeder/netron
