### ISSUE TITLE
TFlite UPM not working on macOS 12.4 + M1 Pro

### ISSUE THREAD

**Issue by vincedotjpeg** [asus4/tf-lite-unity-sample#238]
**Environment (please complete the following information):**
 - OS/OS Version: macOS 12.4 (M1 Pro)
 - Source Version: v2.9.1 (tried v2.8.0 too)
 - Unity Version: Unity 2021.3.3f1 (Apple Silicon)

**Describe the bug**
I'm trying to import said library in my Unity Project via the Package Manager, after tweaking the "manifest.json" as shown on the main page of this project, however when I try to run said project it doesn't work, as if the Interpreter cannot be created, returning this error:

System.DllNotFoundException: libtensorflowlite_c assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) TensorFlowLite.Interpreter.TfLiteModelCreate(intptr,int)
  at TensorFlowLite.Interpreter..ctor (System.Byte[] modelData, TensorFlowLite.InterpreterOptions options) [0x0004b] in /Users/vince/Downloads/TFLite v2.9.1/tf-lite-unity-sample/Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:66 
  at TensorFlowLite.Interpreter..ctor (System.Byte[] modelData) [0x00000] in /Users/vince/Downloads/TFLite v2.9.1/tf-lite-unity-sample/Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:60 
  at Mediapipe.Unity.HandTracking.Gesture_Recognition.InitGestureRecognition () [0x0004e] in /Users/vince/Documents/Projects/Borsa/gesture-recognition-unity/Assets/Gesture_Recognition.cs:137 
UnityEngine.Debug:Log (object)
Mediapipe.Unity.HandTracking.Gesture_Recognition:InitGestureRecognition () (at Assets/Gesture_Recognition.cs:143)
Mediapipe.Unity.HandTracking.Gesture_Recognition:Start () (at Assets/Gesture_Recognition.cs:35)
Gestures:Start () (at Assets/Gestures.cs:16)

The following error is returned when I import the whole package as standalone project, Unity Version 2020.3.29f1 (Intel)

DllNotFoundException: libtensorflowlite_c
TensorFlowLite.InterpreterOptions..ctor () (at Packages/com.github.asus4.tflite/Runtime/InterpreterOptions.cs:60)
TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) (at Packages/com.github.asus4.tflite.common/Runtime/BaseImagePredictor.cs:38)
TensorFlowLite.PalmDetect..ctor (System.String modelPath) (at Assets/Samples/HandTracking/PalmDetect.cs:31)
HandTrackingSample.Start () (at Assets/Samples/HandTracking/HandTrackingSample.cs:37)

This happens for the v2.8.0 branch too (tested this one as it had support for Apple SIlicon too).

**Comment by asus4** [comment]
Hi @vincedotjpeg 

I've tested on the following environment:
- macOS 12.4
- M1 Max
- Unity 2021.3.5f1 - Silicon build

But it works well with the npm package (except iOS build #236). Here's my test project on M1 mac / npm
https://github.com/asus4/tflite-test-m1

If you still have issues, would you mind uploading a minimum unity project to reproduce this error?

**Comment by vincedotjpeg** [comment]
I actually found a reply you gave another user regarding the dimensions of the two .dylib files, so I went and checked mine, realizing their dimensions were only of few bytes, and not MB's as you were saying, so I recloned the repo using git lfs and now it seems to be working just fine ^^

**Comment by asus4** [comment]
Yeah, this repo requires Git LFS to pull big libraries 👍
