### ISSUE TITLE
Minimmum iOS version

### ISSUE THREAD

**Issue by lstewart9** [asus4/tf-lite-unity-sample#241]
Hello, what is the minimum iOS (and android) version required for MediaPipe Blaze Pose?

Thanks

**Comment by asus4** [comment]
TensorFlow Officially 

iOS 10.0

https://github.com/tensorflow/tensorflow/blob/0b71caa06c91d628aecb14255f19c0289db1da83/tensorflow/lite/ios/ios.bzl#L8-L9

Android 
> TFLite Java Library is built against NDK API 19. It may work for Android API levels below
    19, but is not guaranteed.

😅

https://github.com/tensorflow/tensorflow/blob/0b71caa06c91d628aecb14255f19c0289db1da83/tensorflow/lite/java/AndroidManifest.xml#L5-L8
