### ISSUE TITLE
The version v2.9.1-p1 seems apparently slower compared to the version from Apr 2020

### ISSUE THREAD

**Issue by rahul-nt** [asus4/tf-lite-unity-sample#243]
**Environment:**
 - OS/OS Version: Windows 11
 - Source Version: master/v2.9.1-p1 and another version (not sure which) from April 2020
 - Unity Version: 2020.3.36f1 and 2019.24.f1 respectively
 - Android Version: API Level 30
 - Phone model used for testing: Redmi Note 10S
 
**Description of the concern**
The version of the SSD Sample in the plugin from April 2020 apparently looks about twice as fast compared to the current v2.9.1-p1.

I ran Unity Profiler on the two versions of SSD Sample mentioned above, and the older version from April 2020 seems apparently faster than current v2.9.1-p1. The profiling was done on the same static scene where a static object was being detected. The tflite model for SSD is the same one that was already there in github repo.
The CPU usage ranges that I observed in the profiler are as follows:

v2.9.1-p1:
- Player Loop: 58 to 70+ ms (17 to 14 fps)
- Interpreter.Invoke(): 36 to 52 ms

Version from Apr 2020:
- Player Loop: 39 to 51 ms (25 to 19 fps)
- Interpreter.Invoke(): 18 to 37 ms

**Screenshots**
You can see this attached [screenshot ](https://1drv.ms/u/s!AotZH1JI33Z7jQYg71xZTgD3_BBf?e=q78QXj) of the comparison of the two profiling sessions. You can also download [profiling data for v2.9.1-p1](https://1drv.ms/u/s!AotZH1JI33Z7jQeN-hIAJpSVQY1d?e=4Bzz8m) and [profiling data for version from Apr 2020](https://1drv.ms/u/s!AotZH1JI33Z7jQg9V2XQdkFJwWWF?e=kcn3Il).

**Query**
The plugin is quite awesome and I have been working on quite a few applications using the SSD in the plugin version from Apr 2020.
I have been thinking of moving to the latest plugin version but given the currently collected profiling data, I am not so sure if I should move to the latest version of the plugin or not, since there are already gonna be other resource overheads in my applications, and I am planning to maintain a certain FPS level i.e. 25 fps.
Could you kindly provide some insights into what might be the cause of this and how can this situation be resolved?

**Comment by asus4** [comment]
Thanks for reporting it. Let me check.

**Comment by asus4** [comment]
@rahul-nt I looked into this issue today. 
But I could not reproduce that performance issue on my Sony Xperia XZ2 H8266. The latest `TFLit version 2.10.0` was faster than the Apr.2020's `TFLite Version 2.0.0`on my phone. 

Looking into further detail from the Unity profiler is impossible as `TfLiteInterpreterInvoke` (orange arrow) is TFLite's C API. However, you might see more detail using [TFLite profiler](https://www.tensorflow.org/lite/performance/measurement) with your phone.

![record-on-xperia](https://user-images.githubusercontent.com/357497/194590360-ac515dc5-ed4a-41c7-9984-9a835d5fc5f4.png)

**Comment by rahul-nt** [comment]
Hi Koki
Thank you so much for finding out the time to test this. After your reply, I also tested again on two different phone models.

**Phone models:**
1) Google Pixel 6
2) OPPO Reno 2

**Unity Version used:**
Unity 2020.3.36f1

**Plugins used for comparison:**
1) v2.10
2) the older version of your plugin to which I had previously referred in my OP as from "April 2020".
**_Some explanation here about the older version: I called it "the version from April 2020" because I don't exactly know the version number, but I called it from "April 2020" because some of the oldest created files on that version are from April 2020. However, now I doubt that it may not be from April 2020, or v2.0 or 2.2 etc. since your test comparison of v2.10 with v2.0 seem to show different results that I am getting on multiple phones consistently._** 
I am uploading the **[older version here ](https://onedrive.live.com/?authkey=%21AJc%2DRhN0vYntTBs&id=7B76DF48521F598B%211747&cid=7B76DF48521F598B)** so that you may be able to see and test which version exactly it may be.

**Results:**
The results however still show that the older version is faster as compared to v2.10.

I'm including the screenshots here for comparison:

**Google Pixel 6**

![Object Detection Unity Plugin NEW (v2 10) Pixel 6 (2020 3 36f1)](https://user-images.githubusercontent.com/17407874/200644962-53db1ca2-5ef8-4b1d-8549-cfafde5bd46f.png)
![Object Detection Unity Plugin OLD Pixel 6 (2020 3 36f1)](https://user-images.githubusercontent.com/17407874/200644969-5a228e8d-4ede-4dac-9bdd-ae96615f8b93.png)

************************************************************************

**OPPO Reno 2**
![Object Detection Unity Plugin NEW (v2 10) OPPO Reno 2 (2020 3 36f1)](https://user-images.githubusercontent.com/17407874/200645050-139689d0-32fd-4d8a-8468-1e83e3eeac57.png)
![Object Detection Unity Plugin OLD OPPO Reno 2 (2020 3 36f1)](https://user-images.githubusercontent.com/17407874/200645119-10a62455-41c4-4b1c-9875-635e0b24b698.png)

Furthermore, I am also including the link to **[the profiler data files here](https://onedrive.live.com/?authkey=%21AGFtBWHOe8ywe3A&id=7B76DF48521F598B%211746&cid=7B76DF48521F598B)** from Unity for the two versions tested on the two different phones.

A question here is: which Android SDK, NDK, and Gradle versions you are using.

It would be great if you can find the time to compare the v2.10 with the version of yours that I have provided as a [link](https://onedrive.live.com/?authkey=%21AJc%2DRhN0vYntTBs&id=7B76DF48521F598B%211747&cid=7B76DF48521F598B).

Looking forward to your reply.
Best Regards
And kudos for your great work!
