### ISSUE TITLE
Unable to find an entry point named 'TfLiteGpuDelegateV2BindInputBuffer'

### ISSUE THREAD

**Issue by stakemura** [asus4/tf-lite-unity-sample#245]
**Environment (please complete the following information):**
 - OS/OS Version: Android 11
 - Source Version: master/v2.9.1-p1 
 - Unity Version: Unity 2020.3.36f1 

**Describe the bug**

Logcat shows the following error on unity app with OpenCL delegate.
I confirmed OpenCL delegate works correctly *without* tensor bindings.

```
2022/08/28 17:43:53.141 10652 14851 Error Unity EntryPointNotFoundException: Unable to find an entry point named 'TfLiteGpuDelegateV2BindInputBuffer' in 'libtensorflowlite_gpu_jni.so'.
```

**Screenshots**

**Additional context**
I know `TfLiteGpuDelegateV2Bind***` requires your [tensorflow patch](https://github.com/asus4/tensorflow/commit/88ba52d1bd938bc14b87b389f6a210a8f377eb70).
Would you like to check if the native plugins include these entry points?

**Comment by asus4** [comment]
Right, I have forgotten to cherry-pick the patch to the latest release. Thanks.

**Comment by stakemura** [comment]
@asus4 
As for this issue,  `TfLiteGpuDelegateBindGlBufferToTensor` seems to be helpful to support tensor bindings.

https://github.com/tensorflow/tensorflow/blob/2.9.0/tensorflow/lite/delegates/gpu/cl/gpu_api_delegate.cc#L380

 I tried to call `TfLiteGpuDelegateBindGlBufferToTensor` like the following code.

```
        public bool BindBufferToOutputTensor(Interpreter interpreter, int index, ComputeBuffer buffer)
        {
            uint bufferID = (uint)buffer.GetNativeBufferPtr().ToInt32();
            var tensorIndex = interpreter.GetOutputTensorIndex(index);
            var dataType = interpreter.GetOutputTensorInfo(index).type;
            var status = TfLiteGpuDelegateBindGlBufferToTensor(Delegate, bufferID, tensorIndex, dataType, DataLayout.BHWC);
            return status == Status.Ok;
        }
        [DllImport(TensorFlowLibraryGPU)]
        private static extern Status TfLiteGpuDelegateBindGlBufferToTensor(
            TfLiteDelegate gpuDelegate, uint buffer, int tensor_index, Interpreter.DataType data_type, DataLayout data_layout);
```

However, logcat showed the `libtensorflowlite_gpu_jni.so` doesn't contain `TfLiteGpuDelegateBindGlBufferToTensor`.
Do you have any idea to support `TfLiteGpuDelegateBindGlBufferToTensor` on the native plugins?

**Comment by asus4** [comment]
@stakemura I haven't noticed there is another entry point in GPU delegate. `TfLiteGpuDelegateBindGlBufferToTensor` can not be invoked from `libtensorflowlite_gpu_delegate.so` as  the `gpu_api_delegate.h` is not linked to it.

So I tested adding a new build setting in `tensorflow/lite/delegates/gpu/BUILD`. such as below, `libtensorflowlite_gpu_api_delegate.so` includes `TfLiteGpuDelegateBindGlBufferToTensor` API. It requires another C# GPU delegate implementation to integrate it.

```shell
# build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --linkopt -s --strip always :libtensorflowlite_gpu_delegate.so
cc_binary(
    name = "libtensorflowlite_gpu_api_delegate.so",
    linkopts = [
        "-Wl,-soname=libtensorflowlite_gpu_delegate.so",
    ] + gpu_delegate_linkopts() + select({
        "//tensorflow:windows": [],
        "//conditions:default": [
            "-fvisibility=hidden",
        ],
    }),
    linkshared = 1,
    linkstatic = 1,
    tags = [
        "nobuilder",
        "notap",
    ],
    deps = ["//tensorflow/lite/delegates/gpu/cl:gpu_api_delegate"],
)
```
