### ISSUE TITLE
SSD with tensorflow object detection API

### ISSUE THREAD

**Issue by pervin0527** [asus4/tf-lite-unity-sample#247]
### Problem
i tried [SSD-mobilenetV2-320 model](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) with your's.
but it doesn't work... (attach the error log image.)
<img width="921" alt="스크린샷 2022-09-27 오후 1 46 58" src="https://user-images.githubusercontent.com/43873288/192434947-11ad31f2-45dc-4f77-a680-83ae9c389081.png">

i can't find the reason why this error occured...
- input : quantized uint8
- output : float32 4 outputs.(bboxes, scores, class_ids, num_detections)
- Acceleator : GPU
- OS : intel Macbook
- clone this repo with git-lfs
<img width="432" alt="스크린샷 2022-09-27 오후 1 59 16" src="https://user-images.githubusercontent.com/43873288/192435858-ccc1c440-fcc1-4fa1-a52d-ee63d0181494.png">
<img width="1010" alt="스크린샷 2022-09-27 오후 1 54 00" src="https://user-images.githubusercontent.com/43873288/192435415-72edb50e-3736-468b-8cfd-96b41c2eb758.png">

can you explain what's the reason?? please.

**Comment by asus4** [comment]
No ideas. Could you share the script that converts the saved-model in the model zoo to tflite and the actual tflite file?

**Comment by pervin0527** [comment]
> No ideas. Could you share the script that converts the saved-model in the model zoo to tflite and the actual tflite file?

### STEP1 : convert  graph to saved model command.
    python3 object_detection/export_tflite_graph_tf2.py \ 
    --pipeline_config_path=/home/jun/models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config \
    --trained_checkpoint_dir=/home/jun/models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint \
    --output_directory=/home/jun/models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 \

### STEP2 : convert saved model to tflite.
    import os
    import tensorflow as tf
    from glob import glob
    from tflite_support import flatbuffers
    from tflite_support import metadata as _metadata
    from tflite_support import metadata_schema_py_generated as _metadata_fb
    
    # GPU setup
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if len(gpus) > 1:
        try:
            print("Activate Multi GPU")
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
            strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
        except RuntimeError as e:
            print(e)
    
    else:
        try:
            print("Activate Sigle GPU")
            tf.config.experimental.set_memory_growth(gpus[0], True)
            strategy = tf.distribute.experimental.CentralStorageStrategy()
        except RuntimeError as e:
            print(e)
    
    def preprocess_image(images):
        image = tf.io.read_file(images)
        image = tf.image.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [320, 320])
        image = image / 127.5 - 1
        # image = image / 255.
    
        return image
    
    def representative_data_gen():
        images = sorted(glob("/data/Datasets/COCO2017/images/*"))
        idx = 0
        for input_value in tf.data.Dataset.from_tensor_slices(images).map(preprocess_image).batch(1).take(100):
            idx += 1
            
            yield [input_value]
    
    if __name__ == "__main__":
        graph_path = '/home/jun/models/ssd_mobilenet_v2_fpn_320x320_coco17_tpu-8'
        saved_model_dir = f"{graph_path}/saved_model"
        label_file_paths=f'{graph_path}/tflite_label_map.txt'
    
        converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
        converter.experimental_new_quantizer = True
        converter.representative_dataset = representative_data_gen
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.float32
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
        tflite_model = converter.convert()
    
        with tf.io.gfile.GFile(f'{graph_path}/custom.tflite', 'wb') as f:
            f.write(tflite_model)

### tflite model file
https://drive.google.com/drive/folders/1ikq9WolrAbrTa7lXVB5oFeaOhuHNXd6v?usp=sharing
