### ISSUE TITLE
SSD sample scene built to android doesn't run

### ISSUE THREAD

**Issue by MattPaterson985** [asus4/tf-lite-unity-sample#250]
**Environment
Built with windows 10
Unity version 2022.1.17f1 also tried Unity Version 2020.3.40f1
Android Version 12 ARM64

**Describe the bug**
When running the SSD scene on android device the screen is solid grey with a small frame box on screen and does not update or show video

**To Reproduce**
1. Open empty project
2. In package manager add UniTask and unity Mathematics
3. Drag Assets, Packages, ProjectSettings and UserSettings into Assets folder in unity
4. Change Scripting Backend to IL2CPP in project settings 
5. Build android app and run on device

**Expected behavior**
Open app and see camera playing on screen with objects detected

**Comment by asus4** [comment]
Confirmed it. It seems some ops in the SSD model causes crash on Android. Let me check

**Comment by asus4** [comment]
@MattPaterson985  Can you share your ADB log?

**Comment by MattPaterson985** [comment]
I don't know much about Logs but here are the error messages from LogCat in unity  it repeats until the application is closed 

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |  ArgumentException: Object must be an array of primitives.

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |   at System.Buffer.ByteLength (System.Array array) [0x00000] in <00000000000000000000000000000000>:0 

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |   at TensorFlowLite.Interpreter.SetInputTensorData (System.Int32 inputTensorIndex, System.Array inputTensorData) [0x00000] in <00000000000000000000000000000000>:0 

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |   at TensorFlowLite.SSD.Invoke (UnityEngine.Texture inputTex) [0x00000] in <00000000000000000000000000000000>:0 

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |   at SsdSample.Invoke (UnityEngine.Texture texture) [0x00000] in <00000000000000000000000000000000>:0 

2022/10/18 | 10:15:28.326 | 32318 | 32370 | Error | Unity |   at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00000] in <00000000000000000000000000000000>:0

**Comment by peripteraptos** [comment]
Its a bug in unity.
https://issuetracker.unity3d.com/issues/android-sbyte-type-is-considered-to-be-not-primitive-when-compiling-il2cpp-code

**Comment by asus4** [comment]
@peripteraptos Thanks, will try on the latest LTS
