### ISSUE TITLE
Z axis in BlazePose

### ISSUE THREAD

**Issue by cancaglar** [asus4/tf-lite-unity-sample#251]
Is there way to get Z axis in BlazePose? I mean yes blazePose landmarks return Z axis but its inconsistent. I just want to know how far human is from camera or I thought worldLandmarks does that but  when human walk forward or backward pose not moving.

**Comment by asus4** [comment]
Hi @cancaglar 

The BlazePose model outputs 2 different types of landmarks:
- Pose landmarks 
https://google.github.io/mediapipe/solutions/pose.html#pose_landmarks
> z: Represents the landmark depth with the depth at the midpoint of hips being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x.

- World landmarks 
https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks
> x, y and z: Real-world 3D coordinates in meters with the origin at the center between hips.


I understand that it is impossible to get the distance from the camera. so it looks like you have to calculate pseudo distance from the scale of the whole landmarks.
