### ISSUE TITLE
Google Teachable Machine incompatibility

### ISSUE THREAD

**Issue by Pacarius** [asus4/tf-lite-unity-sample#252]
Hi, I'm trying to use your sample to create a project, but it seems that the project has troubles running. Would you be able to help with this issue? Thanks in advance.

![Stroke](https://user-images.githubusercontent.com/112364954/198254787-596f9669-0a07-4915-84bd-bb062e3dc684.png)
[model_unquant.zip](https://github.com/asus4/tf-lite-unity-sample/files/9878237/model_unquant.zip)

**Comment by asus4** [comment]
The input type of the model exported from the Teachable Machine is `float32`. The SSD example in this repo accepts `sbyte` type. 
![Screenshot 2022-10-27 at 12 27 39](https://user-images.githubusercontent.com/357497/198261566-e4c701ce-b422-455e-9fca-4d3993591fdd.png)

You can modify the input type here ↓

https://github.com/asus4/tf-lite-unity-sample/blob/66985ac9836565b23e61c104f2fd589b748fab6a/Assets/Samples/SSD/SSD.cs#L9

Note: your model might be an "Object classification" model. There are no examples available for object classification in this repo. I hope to add samples when I have time, but for now, you will have to provide your own.
