### ISSUE TITLE
SmartReply example fails on Windows

### ISSUE THREAD

**Issue by BTakacs-Oxit** [asus4/tf-lite-unity-sample#254]
**Environment (please complete the following information):**
 - OS/OS Version: Windows 10
 - Source Version:  master
 - Unity Version: 202.3.36f1  same as in repo

**Describe the bug**
SmartReply example fails to run

**To Reproduce**
1 Open the SmartReply.unity demo after a fresh download.
2 press play i nEditor
3 See Error
Exception: TensorFlowLite operation failed.
TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:221)
TensorFlowLite.Interpreter.SetInputTensorData (System.Int32 inputTensorIndex, System.Array inputTensorData) (at Packages/com.github.asus4.tflite/Runtime/Interpreter.cs:122)
TensorFlowLite.SmartReply.Invoke (System.String text) (at Assets/Samples/SmartReply/SmartReply.cs:34)
SmartReplySample.Start () (at Assets/Samples/SmartReply/SmartReplySample.cs:21)

**Comment by asus4** [comment]
Thanks. Will try it on Windows later
