### ISSUE TITLE
Blazepose ghum

### ISSUE THREAD

**Issue by madhavarora2002** [asus4/tf-lite-unity-sample#257]
If i only change the tf lite model file to blazepose ghum (https://google.github.io/mediapipe/solutions/models.html#pose) from the provided blazepose tf lite file, will it work or do I have to make any code changes for z axis in ghum.

**Comment by asus4** [comment]
@madhavarora2002 I think the blazepose landmark model in this repo already contains the z-axis. However, some post-processes in MediaPipe are not fully implemented, so there is room for improvement.

**Comment by madhavarora2002** [comment]
Do you have time for a freelance project?
Would love to work on a custom model with you. Kindly mail me at madhavarora2002@gmail.com, let's take it from there?
