### ISSUE TITLE
build windows command build so file instead of dll

### ISSUE THREAD

**Issue by ragavendranbala** [asus4/tf-lite-unity-sample#26]
'bazel build -c opt --cxxopt=--std=c++11 tensorflow/lite/c:tensorflowlite_c'

command in buildwindows functions building so file instead of dll

**Comment by asus4** [comment]
Which version do you use? I tested it generates the dll file on `v2.2.0`. If not, please make an issue on the TensorFlow repository since it seems TensorFlow's matter.
