### ISSUE TITLE
BlazePose Running On Android Throws Size Error

### ISSUE THREAD

**Issue by karahanoguzhan** [asus4/tf-lite-unity-sample#269]
- OS/OS Version: Android 12
 - Source Version: master
 - Unity Version: 2021.3.11

When I run BlazePose model on my Huawei Mate20 Lite, it is working like a charm, not throwing an error but when I am trying to run it on my Samsung a52 phone, it throws the following "Input data size does not match expected size" error (Sorry for the bad quality):
![206906199-a4e27e74-6e3e-4449-a267-bb938b493d3b](https://user-images.githubusercontent.com/59538240/207402635-9f8a24f8-2a63-46e7-8a1a-3cd1ace1ea5b.jpeg)

What can I do to resolve the issue?

**Comment by asus4** [comment]
Hi, @karahanoguzhan Is this the same issue with #263? 
It would be helpful if you could check whether it works with 2020 LTS.

**Comment by asus4** [comment]
Cool, did it work on the Unity 2021LTS and just change the API level to 30?

**Comment by karahanoguzhan** [comment]
Hi @asus4, sorry for the late response, yes it works on the Unity 2021LTS Api Level 30.

**Comment by asus4** [comment]
Thank you for letting me know @karahanoguzhan!

**Comment by karahanoguzhan** [comment]
Hi @asus4, any updates on this?
