### ISSUE TITLE
[Upgrading npmjs of asus4 packages such that it is upto date with all issues resolved, including XNNPackDelegate fix]

### ISSUE THREAD

**Issue by SusheelNath** [asus4/tf-lite-unity-sample#273]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 11.0
 - Source Version: master
 - Unity Version: Unity 2021.3.13f1

**Describe the bug**
**asus4.tflite 2.10.0 UPM packages** does not have the fix for **XNNPackDelegate**.

**To Reproduce**
1. Pull asus4.tflite npmjs through UPM
2. Notice that XNNPackDelegate changes done in repository has not been reflected in UPM asus4.tflite core packages.

**Expected behavior**
XNNPackDelegate changes done in the local repository (master branch fixes) should be reflected in the npmjs asus4 packages. Creating a master commit with npmjs asus4 packages version to 2.11.0, and then publishing to npm so they now match both in content and versioning.

**Screenshots**
NA

**Additional context**
NA

**Comment by asus4** [comment]
Hi @SusheelNath 

I have released the version `2.10.0-p1` to the npm!
