### ISSUE TITLE
Is "ssd_mobilenet_v2_fpnlite" not supported?

### ISSUE THREAD

**Issue by Kim-Dae-Ho** [asus4/tf-lite-unity-sample#275]
Hello.
I converted the model into tflite after using it as follows and put it in Unity TensorFlow.

ssd_mobilenet_v2_quantized was only operated on TensorFlow 1.15, so I learned it.
This model works well in Unity TensorFlow even when converted to tflite.

ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 was only operated in the TensorFlow 2.x environment, so I learned it.
This model is converted to tflite, but when put into Unity Tensorflow, the console window displays "Failed TensorflowLite Operation" in red and object recognition behavior is not possible.

Is this tf-lite-unity-sample project file not supported for series named ssd_movilenet_v2_fpnlite, which is a model dedicated to TensorFlow 2.x?

**Comment by asus4** [comment]
Hi @Kim-Dae-Ho could you share the link to the model file?

Also please refer to the similar issues, such as 
https://github.com/asus4/tf-lite-unity-sample/issues/237#issuecomment-1187186458

The SSD sample only supports the quantized int8 model. You need to modify the code a bit to run the float16 or float32 model.

**Comment by Kim-Dae-Ho** [comment]
[fpnlite_info.zip](https://github.com/asus4/tf-lite-unity-sample/files/10455034/fpnlite_info.zip)
![fpnlite netron](https://user-images.githubusercontent.com/86465978/213395624-24c90a53-5dac-4405-a378-d2316644065f.png)

After converting ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 to tflite, I checked with Netron.
Both INPUTS and OUTPUTS came out as float32.
When converting to tflite, it seems that the type was forcibly converted to float32.
Does this model not support int8?

On the other hand, in the case of ssd_mobilenet_v2_quantized, INPUTS was unit8. The OUTPUTS came out as float32, but it works very well.

**Comment by asus4** [comment]
`int8` is hardcoded in the C# code here: You need to modify the code to support it
https://github.com/asus4/tf-lite-unity-sample/blob/4ae9930f2cc0eb80ab1de29c6fd40f538fa05a8d/Assets/Samples/SSD/SSD.cs#L9

**Comment by aptx4850** [comment]
After converting the OUTPUTS method of the tflite model differently and modifying the C# script source code for unity-tensorflowlite you told me, the functionality seems to have worked well on the SSD_mobilenet_v2 fpnlite 320 model.
Thank you.
Thanks to you, I was able to gain an understanding of the neural network structure of the model through this opportunity.
Have a pleasant time.

**Comment by lakpa-tamang9** [comment]
@aptx4850 could you please provide details of how you resolved the issue?

**Comment by brollsroyce** [comment]
> After converting the OUTPUTS method of the tflite model differently and modifying the C# script source code for unity-tensorflowlite you told me, the functionality seems to have worked well on the SSD_mobilenet_v2 fpnlite 320 model. Thank you. Thanks to you, I was able to gain an understanding of the neural network structure of the model through this opportunity. Have a pleasant time.

@aptx4850  @asus4  Yes, please what is the solution to that? What changes to the code are required?
