### ISSUE TITLE
DllNotFoundException: libtensorflowlite_c 

### ISSUE THREAD

**Issue by fredmouse** [asus4/tf-lite-unity-sample#276]
**Environment (please complete the following information):**
 - OS/OS Version: [macOS 11.6] intel Mac
 - Source Version: [master/v2.10.0-p1]
 - Unity Version: [Unity 2021.3.3.f1]

**Describe the bug**
Couldn't run any example as all prompts the same DllNotFoundException: libtensorflowlite_c  exception. I cloned the git with Git-LFS installed, which ended up with almost over 800mb and libtensorflowlite_c.dll of 3mb( I think I didn't miss any files). But I still get this exception on all the examples. Below you can find one of the exception message

DllNotFoundException: libtensorflowlite_c assembly:<unknown assembly> type:<unknown type> member:(null)
TensorFlowLite.InterpreterOptions..ctor () (at Packages/com.github.asus4.tflite/Runtime/InterpreterOptions.cs:62)
TensorFlowLite.BaseImagePredictor`1[T].CreateOptions (TensorFlowLite.BaseImagePredictor`1+Accelerator[T] accelerator) (at Packages/com.github.asus4.tflite.common/Runtime/BaseImagePredictor.cs:104)
TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, TensorFlowLite.BaseImagePredictor`1+Accelerator[T] accelerator) (at Packages/com.github.asus4.tflite.common/Runtime/BaseImagePredictor.cs:98)
TensorFlowLite.FaceDetect..ctor (System.String modelPath) (at Assets/Samples/FaceMesh/FaceDetect.cs:48)
FaceDetectionSample.Start () (at Assets/Samples/FaceMesh/FaceDetectionSample.cs:27)

**Comment by asus4** [comment]
@fredmouse Can you check this out? https://github.com/asus4/tf-lite-unity-sample/issues/199#issuecomment-1058950494

On the macOS, please confirm that dylibs are exists at `Packages/com.github.asus4.tflite/Plugins/macOS/*.dylib`.

**Comment by fredmouse** [comment]
I checked every post on this DllNotFoundException topic before posting this issue. I tried these methods like brew install git-lfs and git clone this repository. I also executed "git lfs install" in the cloned folder afterwards. On the other hand, I confirm I have libtensorflowlite_c.dylib and libtensorflowlite_metal_delegate.dylib at `Packages/com.github.asus4.tflite/Plugins/macOS/*.dylib`.

> @fredmouse Can you check this out? [#199 (comment)](https://github.com/asus4/tf-lite-unity-sample/issues/199#issuecomment-1058950494)
> 
> On the macOS, please confirm that dylibs are exists at `Packages/com.github.asus4.tflite/Plugins/macOS/*.dylib`.

**Comment by asus4** [comment]
Hmmm...then I have no idea to solve your error.

**Comment by fushikky** [comment]
I got same error. But I realise my mistake.
(My OS is intel Mac[macOS13.4].)

I opened the library in notepad.
(`Packages/com.github.asus4.tflite/Plugins/macOS/libtensorflowlite_c.dylib`)
In my case it was a reference file to the Git LFS.

I ran a command (git lfs pull) and the dll entity was dropped and worked fine.

I hope this helps you.

**Comment by qq908410202** [comment]
When I use Unity to build Android, DllNotFoundException: libtensorflowlite will appear_ JNI error;

Unity version: March 14, 2022

Android Level: 7

Il2cpp
