### ISSUE TITLE
Model must be re-instantiated after each call.

### ISSUE THREAD

**Issue by qlee01** [asus4/tf-lite-unity-sample#277]
**Environment (please complete the following information):**
 - OS/OS Version: [e.g. iOS 11.0/Andoroid 8.1/macOS 10.15.6]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.5.f1]

**Describe the bug**
I basically experience the exact behavior which is described by multiple users here:
https://github.com/asus4/tf-lite-unity-sample/issues/260
By using the library found here:
https://github.com/voxell-tech/UnityTTS

**To Reproduce**
Try the sample found in:
https://github.com/voxell-tech/UnityTTS

**Expected behavior**
output tensor should have values each time after "Invoke()". Currently it does only in the first run. Only a re-init does help.

**Screenshots**

**Additional context**
Same issue as reported here:
https://github.com/asus4/tf-lite-unity-sample/issues/260

**Comment by asus4** [comment]
Seems to be fixed in https://github.com/asus4/tf-lite-unity-sample/issues/260#issuecomment-1404928610
