### ISSUE TITLE
Runs extremely slow when both Vulkan and OpenGL ES 3.0 supports are added

### ISSUE THREAD

**Issue by WizphysAi** [asus4/tf-lite-unity-sample#282]
**Environment:**
 - OS/OS Version: [e.g. Andoroid 8 and above
 - Source Version: [e.g. master/v2.10.0]
 - Unity Version: [e.g. Unity 2020.3.43.f1]

**Describe the bug**
In order to make our app work on most Android devices, we are adding support to both Vulkan and OpenGL ES 3.1 and 3.2 graphics API. However, we observed that when we add both these supports, the app runs extremely slow on Samsung Galaxy M series devices and A series devices. When we remove the Vulkan support, then it works perfectly. But when we remove Vulkan support, TFLite simply does not work at all with the following error. 
**Error**
Exception: TensorFlowLite operation failed.
at TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) [0x00000] in <00000000000000000000000000000000>:0 
at TensorFlowLite.PoseDetect.Invoke (UnityEngine.Texture inputTex) [0x00000] in <00000000000000000000000000000000>:0 
at TensorFlowLite.BlazePose.Invoke (UnityEngine.Texture texture, System.Boolean StandingExercise) [0x00000] in <00000000000000000000000000000000>:0 

**Question:**
Is there any way to make BlazePose run on all device using only OpenGL ES 3.x support since all devices actually support it. If not, is there any particular combination of settings which will make sure that the app runs smoothly on all types of devices. We are targeting only ARM V8 devices with RAM more than 4 GB.

**To Reproduce**
1. Unity Settings: Build Settings->Player Settings->Other Settings->Graphics API->Select Vulkan and OpenGL ES3
2. Run the app on Samsung Galaxy M31 or equivalent device. The app will be noticeably slower. 
3. Run the same app on Samsung Galaxy S10 or equivalent device.  The app works as intended due to Vulkan support.
4. Remove Vulkan support from step 1. Run this new app on same device as in step 2. You'll notice that the performance is better.
5. Run this new app on same device as in step 3 again. Here, TFLite will throw an exception **Even though this device supports OpenGL ES 3.x and the same support is provided in Unity build settings**

**Screenshots**
Settings
![image (23)](https://user-images.githubusercontent.com/102574562/218470315-b4f865a4-dc2e-4b6f-a151-a8933960b329.png)

TFLite Exception
![image (24)](https://user-images.githubusercontent.com/102574562/218470406-57e1e1b5-0e1e-43c6-b753-2ee6d647534c.png)

**Comment by asus4** [comment]
Hi @WizphysAi,

To be clear, are the following results correct?

| Device | Graphics APIs | Result |
|---|---|---|
| Samsung Galaxy M31 | Vulkan and OpenGLES3 | Slow |
| Samsung Galaxy S10 | Vulkan and OpenGLES3 | OK |
| Samsung Galaxy M31 | OpenGLES3 | Better |
| Samsung Galaxy M31 | Vulkan | Crash |

I could not reproduce this error as I don't have any Samsung devices. So it's a guess, but it seems to fail to initialize 
 GpuDelegateV2. What if you specify GlDelegate instead of the GpuDelegateV2 delegate when initializing interpreter options?
