### ISSUE TITLE
Performance degradation on iPhone

### ISSUE THREAD

**Issue by peperunii** [asus4/tf-lite-unity-sample#285]
Hi, thank you very much for this project.
I have a problem when using the Metal delegate on IOS. At the beginning a model execution time is 0.04 seconds which is perfect and then over time it gets slower. After 1 minute is 0.06 seconds, after 2 minutes is 0.1 and at some point it gets stable when each execution takes 0.4 seconds. When I restart the App everything is back to normal again. 
I tried to reinitialize the Interpreter from the 'BaseImagePredictor' class when I detect the drop in performance - but it is not helping.
 Is that something I am doing wrong or a specific Unity setting that I have to do?
My unity editor version is 2021.3.15f and I am trying to run it on iPhone 13 mini -> with IOS 15.7

**Comment by asus4** [comment]
@peperunii Thanks for reporting it. Which example did you test?

**Comment by peperunii** [comment]
It is a custom TFLite model (Semantic segmentation network) that I generated - Accepting normalized image in float [,,] format and returning float[,,]

**Comment by asus4** [comment]
Okay, it could be thermal throttling or GC. But I probably cannot figure out the cause as I cannot test it on my end.
