### ISSUE TITLE
Unity fatal error when exiting play mode if webcam device was not connected.

### ISSUE THREAD

**Issue by ascoider** [asus4/tf-lite-unity-sample#286]
- Build Platform: Android
- Source Version: 2.10.0
- Unity Version: 2021.3.19.f1, 2021.3.16.f1

When leaving play mode, if a webcam was not previously connected, Unity crashes with an unknown error.

1. Enter Play mode without a camera/webcam connected to computer.
2. Stop Play mode.
3. Fatal error, Unity shut down.

This is the crash log:
![fatal error](https://user-images.githubusercontent.com/83346374/222687832-16b57eb9-1ac6-4a7d-b28d-e0b01c1214e6.png)

**Comment by asus4** [comment]
Thank you for reporting it. I could not reproduce it as all of my androids have cameras. Can you tell me what kind of Android you use for reference?
