### ISSUE TITLE
I need help mnist sample buffer setting 

### ISSUE THREAD

**Issue by jake09o** [asus4/tf-lite-unity-sample#29]
i created many different tensorflow lite model ( 3 channel or 56x56 or 150x150)
but this model is not good result
because i dont idea how to ComputeShader and ComputeBuffer Setting

Please let me know it
![ss](https://user-images.githubusercontent.com/34004748/85248551-16d99200-b48c-11ea-8510-b0f77099344f.PNG)

**Comment by asus4** [comment]
Hi @jake09o, This ComputeShader just flips Y. It might better that I rewrite in C# as the simple mnist example😄

When you use the model with inputs[56x56x1], it should run just replacing all `28` into `56` (includes `TextureToBuffer.compute` file).

**Comment by jake09o** [comment]
@asus4 Thank you
But i haven't solued the problem yet. TT
![캡처1](https://user-images.githubusercontent.com/34004748/86891919-80b79400-c13a-11ea-9b5b-431103bd66f0.PNG)
![캡처2](https://user-images.githubusercontent.com/34004748/86891922-81e8c100-c13a-11ea-9241-e7329aa963b1.PNG)

I can't understand why this is not
plz help my problem
