### ISSUE TITLE
When using BlazePose on some models of the Galaxy A series, the body recognition function does not work

### ISSUE THREAD

**Issue by ghtnql-kbi** [asus4/tf-lite-unity-sample#290]
**Environment (please complete the following information):**
 - OS Version : Android / Android 13, Macbook
 - Source Version : v2.9.1, v2.10.0
 - Unity Version: Unity 2022.1.0
 - Device : Galaxy A Quantam, Galaxy A51, Galaxy A31
 - 
**Describe the bug**
When using BlazePose on some models of the Galaxy A series, the body recognition function does not work.

**To Reproduce**
1. Upgrade OS Version 12 to 13.
2. Build Unity Project.
3. Open the BlazePose Scene.
4. See error.

**Expected behavior**
Recognizes the user's body part and marks the skeleton on that part.

**Screenshots**
![Screenshot_20230321_184658_tf-lite-unity-sample](https://user-images.githubusercontent.com/116695287/226570331-6bbe2812-2a21-4d0d-a541-346dcc51a12a.jpg)

**Additional context**
If you uncheck Graphic Api on Windows as well as on Mac, it will not be recognized..

**Comment by asus4** [comment]
- Can you share the error log in the adb logcat? My Andoirds seem to be working.
- Are you running it in the Background Thread? please refer to #263
