### ISSUE TITLE
how instal tensorlite

### ISSUE THREAD

**Issue by Osman-Kilic** [asus4/tf-lite-unity-sample#291]
how can i install tensor lite please help i couldn't find any article document.

**Comment by asus4** [comment]
@Osman-Kilic Do you want to install TensorFlowLite?

If so, please follow the [install section](https://github.com/asus4/tf-lite-unity-sample#install-tensorflow-lite-for-unity) in the README. Also, please refer to the [Unity Package Manager](https://docs.unity3d.com/Manual/upm-ui.html).

**Comment by Osman-Kilic** [comment]
thanks i just got it
