### ISSUE TITLE
How to calculate head euler angles from landmarks 

### ISSUE THREAD

**Issue by se7enXF** [asus4/tf-lite-unity-sample#293]
- I use two points "head top" and "jaw bottom" to calculate Z and X rotarion angles, and "eye right side" and  "eye left side" to 
calculate Y rotarion angle, with Vector3.SignedAngle in unity.  The angles are correct only in the case of a front face, and the angle error is very large after head rotation.
- I have searched the same issue in mediapipe and this [issue](https://github.com/google/mediapipe/issues/1912) is what I want. But no clear answer.  I alse read the related answers and [codes](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry/libs) but can't understand.  

Is there a good solution?

**Comment by asus4** [comment]
Hi @se7enXF, I am unfamiliar with this topic, and I am sure there are newer ways of doing this.

1. [Math.Atan2](https://docs.unity3d.com/ScriptReference/Mathf.Atan2.html) will be enough to get a rough angle from the vector of two keypoints.

I found an example using Atan2.
https://medium.com/@susanne.thierfelder/head-pose-estimation-with-mediapipe-and-opencv-in-javascript-c87980df3acb

3. MediaPipe seems to have [a solver class to estimate transform](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/procrustes_solver.h). Although Eigen library is required, probably this more robust way.

**Comment by se7enXF** [comment]
@asus4 Thanks for reply.  

As we already got the 3D point of landmarks, I do not think using solvePnp in cv2 is a good solution. And the mobile adaptation of the OpenCV library is another new issue.  

I tried the 3rd way you mentioned but failed. ProcrustesSolver in mediapipe requires a lot of dependencies libraries, in addition to Eigne. The key issue is that some libraries do not support multiple device adaptation.  

I am looking for a simple matrix solution.

**Comment by se7enXF** [comment]
Finally, I use Vector2.SignedAngle in Unity to calculate the angle. Here is my code, hoping to help those in need. 

```c#
// z
const int headTopIndex = 10;
const int jawBottomIndex = 152;
var to = Vector2.up;
var from = faceData[headTopIndex] - faceData[jawBottomIndex];
var angleZ = Vector2.SignedAngle(from, to);

// x
from = new Vector2(from.y, from.z);
to = Vector2.right;
float angleX = Vector2.SignedAngle(from, to);

// y
const int eyeRightSide = 33; 
const int eyeLeftSide = 263;
to = Vector2.left;
from = faceData[eyeRightSide] - faceData[eyeLeftSide];
from = new Vector2(from.x, from.z);
float angleY = Vector2.SignedAngle(from, to);
```
