### ISSUE TITLE
Load model from PersistentDataPath

### ISSUE THREAD

**Issue by BylKusOfficial** [asus4/tf-lite-unity-sample#294]
When you want to load a model from you need to use the path ""jar:file://" + Application.dataPath + "!/assets/""  due to the function "FileUtil.IsPathRooted" which checks "path.StartsWith("jar:file:")". 

How can I load from "PersistentDataPath" ?

**Comment by asus4** [comment]
hey @BylKusOfficial 

the interpreter provides a constructor with the `byte[]`. You can create the interpreter after loading the model from `PersistentDataPath` in your code.

https://github.com/asus4/tf-lite-unity-sample/blob/4ae9930f2cc0eb80ab1de29c6fd40f538fa05a8d/Packages/com.github.asus4.tflite/Runtime/Interpreter.cs#L62

**Comment by BylKusOfficial** [comment]
Thank you for your help.
I use abstract the class "BaseImagePredictor" and the "interpreter" is "readonly". 
It will be nice to have the choise to load from "PersistentDataPath" on the ctor.

Also if I remove all tflite from "StreamingAssets", there is an error because we can't choose file on the "modelPath" inspector variable.

**Comment by asus4** [comment]
I understand your point. Adding `byte[] modelData` constructor in the `BaseImagePredictor` would be a more versatile approach in this case.

**Comment by asus4** [comment]
Hey @BylKusOfficial, I've added a new constructor work with `byte[] modelData`. Let me know if you have any problems using it.
