### ISSUE TITLE
TextureToTensor GPU options

### ISSUE THREAD

**Issue by acornellier** [asus4/tf-lite-unity-sample#295]
I understand that there is no option for a GPU delegate in Windows. There is `XNNPack` available (although the readme doesn't seem to include it), but it still uses the CPU.
However, I see that in `TextureToTensor`, there are these functions that does some work with the GPU. I don't really understand what... Is this work separate than what the GPU delegates do? Also, is there a reason it's only implemented for `float`? My implementation uses `sbyte` and I'd like the performance benefit that this brings.
```
        public void ToTensor(RenderTexture texture, float[,,] inputs)
        {
            if (texture.width % 8 != 0 || texture.height % 8 != 0)
            {
                ToTensorCPU(texture, inputs);
            }
            else
            {
                ToTensorGPU(texture, inputs);
            }
        }

        private void ToTensorGPU(RenderTexture texture)
        {
            int width = texture.width;
            int height = texture.height;

            if (tensorBuffer == null || tensorBuffer.count != width * height)
            {
                DisposeUtil.TryDispose(tensorBuffer);
                tensorBuffer = new ComputeBuffer(width * height, sizeof(float) * 3);
            }
            int kernel = compute.FindKernel("TextureToFloatTensor");

            compute.SetTexture(kernel, InputTexture, texture);
            compute.SetBuffer(kernel, OutputFloatTensor, tensorBuffer);
            compute.SetInt(TextureWidth, width);
            compute.SetInt(TextureHeight, height);

            compute.Dispatch(kernel, width / 8, height / 8, 1);
        }

        private void ToTensorGPU(RenderTexture texture, float[,,] inputs)
        {
            ToTensorGPU(texture);
            tensorBuffer.GetData(inputs);
        }
```

**Comment by asus4** [comment]
The `ToTensorGPU` is not related to the TensorFlowLite's GPU delegate. It is a pre-processing written in Unity ComputeShader. And I have not implemented it for the `sbyte` yet. 

However, in my environment, fetching data from the GPU was a bottleneck and there was no such difference between GPU and CPU. If I rewrite it, I would try [Burst compiler](https://docs.unity3d.com/Packages/com.unity.burst@1.8/manual/index.html) for all data types.
