### ISSUE TITLE
CameraTextureBackground doesn't support Built-in Render Pipeline

### ISSUE THREAD

**Issue by Pypow** [asus4/tf-lite-unity-sample#311]
Environment 
 - OS: Windows 11 
 - Unity Version: Unity 2021.3.19f1

Describe the bug
When I click on play in the SSD sample Unity Scene,  I can see that my webcam is turning on, in the Unity game view I can see solid gray background and objects being detected (Green bounding box with label). I am not getting live camera feed from my webcam.
(I have tried to build it to Android device (Android:13, ARM64), but I experienced the same issue as above)

1. Download this repo and make changes to manifest file as below, delete packages-lock.json.
2. open SSD Sample Scene.
3. Play the scene.

Expected behavior
The bounding box of detected objects should appear with the camera live feed as the background.

Screenshots
![manifest_update](https://github.com/asus4/tf-lite-unity-sample/assets/66823273/5a3bb323-15ae-41f7-9b66-5f061d8a9c78)
![output](https://github.com/asus4/tf-lite-unity-sample/assets/66823273/11326b72-83cd-4546-8a2e-69a1c39d5f8d)

Additional context
Referred to similar issue: #250. Since my scene was getting updated I assumed unity version was not the problem.
Let me know if I have done anything wrong or if you need any additional information.
Great Repo! Thank you for your hard work.

**Comment by asus4** [comment]
I didn't reproduce this. Would you mind uploading a repro project to GitHub or somewhere?

**Comment by Pypow** [comment]
Sure, 
Project Repo: https://github.com/Pypow/TFLiteSetUp

When uploading the project to GitHub, I noticed I had a missing script on Main Camera, this may be the cause of my issue,
![screenshot missing script](https://github.com/asus4/tf-lite-unity-sample/assets/66823273/ba78c82d-2c4b-43d4-bd42-83fe2469ed0b)

Although I am not able to figure out the name of the missing script, I believe it was due to a compile error related to some missing package?

Here is a screenshot of my Package Manager, 
![image](https://github.com/asus4/tf-lite-unity-sample/assets/66823273/430dc7ce-eebd-451d-a649-589be62228de)

Thanks for your help!

**Comment by asus4** [comment]
@Pypow, this issue should have been fixed in #317. Please check it out.
