### ISSUE TITLE
Fails TFLite Android build on CircleCI

### ISSUE THREAD

**Issue by asus4** [asus4/tf-lite-unity-sample#318]
**Environment (please complete the following information):**
 - OS/OS Version: Linux 
 - Source Version: master/v2.3.0 or later

**Describe the bug**

CircleCI/Android build fails because of the Android build tools compatibility.

Please see [the CI log](https://app.circleci.com/pipelines/github/asus4/tf-lite-unity-sample/45/workflows/cec58173-b1c6-470d-9382-caf6a4f73ed8/jobs/209) for detail. Now, the TensorFlow Lite v2.3.0 requires `Android build tools 31`. However, it also requires deprecated dx.jar somewhere in the build process. To build it, I needed to copy from the old SDK. See [stackoverflow](https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted)

**To Reproduce**
1. Make a PR and see the CI result 

**Expected behavior**

Android CI build should pass without errors.

**Comment by asus4** [comment]
@stakemura, looks like it still fails with v2.14.0. Any ideas?

https://app.circleci.com/pipelines/github/asus4/tf-lite-unity-sample/54/workflows/89960eb4-221b-4328-9ccb-232343b4ed52/jobs/253

**Comment by stakemura** [comment]
@asus4 I see. I will try GitHub Actions.

**Comment by stakemura** [comment]
@asus4 
As the following link shows, I suceeded to build the cross-platform runtime on github actions.

TFLite v2.14.0 build workflow
https://github.com/stakemura/tflite-runtime-builder/actions/runs/6878796209 

TFLite v2.15.0 (today release!) build workflow
https://github.com/stakemura/tflite-runtime-builder/actions/runs/6878494940

Also this CI supports GitHub release and user can download the all runtimes from `tflite-runtime.zip`.
https://github.com/stakemura/tflite-runtime-builder/releases

TFLite v2.14.0 all runtimes
https://github.com/stakemura/tflite-runtime-builder/releases/download/v2.14.0/tflite-runtime.zip

I invited you as the collaborator of the repositry. Please use it for your convenience. 
Of course, I am ready to send PR here to replace CircleCI with Github Actions.
Could you please let me know your opinion?

**Comment by asus4** [comment]
Wow, @stakemura, that's cool and would allow us to catch up on the latest TensorFlow release quickly!

I feel that keeping repositories separated would be better since your GitHub Actions triggered by the new tag are simple enough. Anyway, let me try that binaries on my side.

**Comment by asus4** [comment]
Hi @stakemura, I have confirmed that the v2.14.0 and v2.15.0 binaries worked like a charm on this project. I've published NPM releases for these versions. Please let me know if you find any issues with new binaries.
