### ISSUE TITLE
deeplabv3_257_mv_gpu.tflite question

### ISSUE THREAD

**Issue by laitathei** [asus4/tf-lite-unity-sample#319]
I tried to implement deeplabv3_257_mv_gpu.tflite in my project, it has very good performance.
But I want to train with my custom dataset. Would you like to provide the information of how to train a new deeplabv3 model and export it into tflite format?

**Comment by asus4** [comment]
Hi @laitathei, here's a link to the official DeepLab model.
https://github.com/tensorflow/models/tree/master/research/deeplab

And I googled a [tutorial](https://medium.com/chowagiken-tech-blog/deeplab-image-segmentation-on-android-part-1-training-392abf24a7fc) that might be useful.

There may be a better way, as I have not tried fine-tuning it.
