### ISSUE TITLE
Error on "interpreter.AllocateTensors()" while using my own model

### ISSUE THREAD

**Issue by sarattha** [asus4/tf-lite-unity-sample#32]
First, I like to thank you for the tf-lite on the unity. I try to use my own model like the image below
![Annotation 2020-07-04 144913](https://user-images.githubusercontent.com/17222515/86507910-ef78b280-be05-11ea-8f7e-bae6e1208b10.jpg)

I try to load the model from your DeepLab and SSD example. Because my model is the SSD too. But I got error at the 
line "interpreter.AllocateTensors()" and "interpreter.ResizeInputTensor()". 

I think maybe this is because of my model input format. So, can I ask you about the workaround to load my model from your example source codes. Thank you.

**Comment by sarattha** [comment]
Right now I can load my model with out the above errors. But when I try to invoke the model from this line
![image](https://user-images.githubusercontent.com/17222515/86525693-b6e3e200-beb4-11ea-99f4-4afa23fd9958.png)
Unity program will close itself and ask me to report the bug every time. Can you suggest me the point that I should investigate? 
Thank you.

**Comment by asus4** [comment]
Added "Error Reporter" 5eef1a5c327bdcae4b9046bc841e7aa47fb16492, now you can see more detailed error in Unity.

error reporter log:
```
Following operations are not supported by GPU delegate:
DEPTHWISE_CONV_2D: Expected 1 runtime input tensor(s), but node has 2 runtime input(s).
DEQUANTIZE: Operation is not supported.
35 operations will run on the GPU, and the remaining 41 operations will run on the CPU.
```
