### ISSUE TITLE
Map the landmarks on BlazePose Sample into a 3D avatar: eg Unity Chan?

### ISSUE THREAD

**Issue by EzinwaTribes** [asus4/tf-lite-unity-sample#327]
Great work you have here.

I am new to Unity, and I Am just having difficulty mapping the landmark pose(BlazePose) into real-time 3D character movement.  I would be happy if that is included in a PR soon using the Unity Chan Avatar.

Thanks.

**Comment by asus4** [comment]
Hi @EzinwaTribes, thanks for the suggestion. It is on my Todo list but won't be done soon.

Here are similar 3D avatar projects. You may find what you want to do.

- [HolisticMotionCapture](https://github.com/creativeIKEP/HolisticMotionCapture): Using MediaPipe Holistic on Barracuda
- [VRigUnity](https://github.com/Kariaro/VRigUnity): Using [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) 
- [KalaidoKit](https://github.com/yeemachine/kalidokit): Using Web version MediaPipe

**Comment by EzinwaTribes** [comment]
Hi @asus4, Thanks for the swift reply and the reference suggested, they are quite helpful. Am just finding it hard to locate where those landmarks are located and accessed on your project.
