### ISSUE TITLE
using static image instead of WebCamTexture on BlazePose

### ISSUE THREAD

**Issue by cancaglar** [asus4/tf-lite-unity-sample#337]
I want to give a static image instead of a webcam, and in the blazeposesample script, I gave an image on the screen instead of a webcam in the invoke, but the landsmarks grow very large, for example, every time the image changes, I want landmarks to be created exactly according to the size of the image, how do I do this?

![image](https://github.com/asus4/tf-lite-unity-sample/assets/59360242/6127934b-9c00-4284-a480-f07ec0009054)

**Comment by asus4** [comment]
In the demo app, the viewport-landmarks (range of 0.0f to 1.0f) are scaled to the current camera space in BlazePoseDrawer.cs. Please implement custom scaling for the static image input.

https://github.com/asus4/tf-lite-unity-sample/blob/20742dea4845bed46dd40bfa1909e0fb62912098/Assets/Samples/BlazePose/BlazePoseDrawer.cs#L76C1-L83C1
