### ISSUE TITLE
Need FaceMesh / Blaze Face Example

### ISSUE THREAD

**Issue by Starsky-Synlitec** [asus4/tf-lite-unity-sample#34]
I'm very happy to see this plugin. We can do tensorflow in Unity and on GPUs !  :).

However, after running these examples, I found some difficulties.

I tried to implement facemesh and blazeface from Mediapipe, it worked but I found:

This plugin is very limited compared with Tensorflow Lite, we could not do any operations (such as slice, div ...) over tensor object (well, there is no tensor object in this plugin, only array of float numbers). I need to write these operations on CPU, or using computer shader, or shader + Graphics.Blit.

Anyway, I hope we could put more efforts on developping this plugin :).

**Comment by asus4** [comment]
@Starsky-Synlitec  Added FaceMesh / Blaze Face examples at #64 

There is still a bug of Matrix4x4 coordinate conversion but it would be helpful

**Comment by customlogic** [comment]
I think I found a fix for the FaceMesh positioning: #69

**Comment by asus4** [comment]
Now we have FaceMesh and BlazeFace example, enjoy!
