### ISSUE TITLE
libtensorflowlite_c.dll issue

### ISSUE THREAD

**Issue by victorx79** [asus4/tf-lite-unity-sample#39]
I got this error when i try to run. please let me know

Plugins: Failed to load 'Assets/plugins/Windows/libtensorflowlite_c.dll' because one or more of its dependencies could not be loaded.
TensorFlowLite.BaseImagePredictor`1:.ctor(String, Boolean) (at Assets/Samples/Common/BaseImagePredictor.cs:34)
TensorFlowLite.DeepLab:.ctor(String, ComputeShader) (at Assets/Samples/DeepLab/DeepLab.cs:51)
DeepLabSample:Start() (at Assets/Samples/DeepLab/DeepLabSample.cs:22)

**Comment by gblue1223** [comment]
see #11

**Comment by asus4** [comment]
Hmm, it seems to be a dependency error. but I couldn't reproduce it. Are there any other error messages? Can you share the UnityEditor's log?

**Comment by cyraxchel** [comment]
Hello. 
I got this same dependency issue. I decided to rebuild the tflite libraries myself. Prepared the build environment ... and after that the message about dependencies in Unity disappeared.

**Comment by asus4** [comment]
@cyraxchel  Thanks for your report. Just to clarify, Did the error disappear before you built the library yourself?

**Comment by cyraxchel** [comment]
> 
> 
> @cyraxchel Thanks for your report. Just to clarify, Did the error disappear before you built the library yourself?
I failed rebuild library (some error in VC). I keep using your library. :)

**Comment by SBeyer6** [comment]
I seem to get this issue as well; It works on two different PCs but on another PC it the plugin fails to load, with the same error.

**Comment by asus4** [comment]
Could you check which dependencies are missing using app like this.
https://kb.froglogic.com/misc/using-dependency-walker/

**Comment by SBeyer6** [comment]
Ok I checked, it seemed like the latest vc 2019 redistributable was installed.

**Comment by cwule** [comment]
Trying to build for Windows 10 UWP Arm64 application leads to the same error:
`Exception thrown at 0x00007FFDF75539EC in tf-lite-unity-sample.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x0000009FF8CFCA60.
DllNotFoundException: Unable to load DLL 'libtensorflowlite_c': The specified module could not be found.
  at TensorFlowLite.InterpreterOptions.TfLiteInterpreterOptionsCreate () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.InterpreterOptions..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.BaseImagePredictor1[T]..ctor (System.String modelPath, System.Boolean useGPU) [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.PoseNet..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
  at PoseNetSample.Start () [0x00000] in <00000000000000000000000000000000>:0 `

**Comment by vaibhav-suri** [comment]
Plugins: Failed to load 'V:/HandTracking/tflite/tf-lite-unity-sample-master/Packages/com.github.asus4.tflite/Plugins/Windows/libtensorflowlite_c.dll' because one or more of its dependencies could not be loaded.

Getting this error,any idea how to fix?

**Comment by SBeyer6** [comment]
@vaibhav-suri I managed to fix this error by installing both the x86 and x64 Visual C++ 2019 Redistributable.
Hope this works for you as well.

**Comment by vaibhav-suri** [comment]
@SBeyer6 Thanks a lot! That worked.

**Comment by Cipher-zzz** [comment]
@cwule got the same error when developing Hololens 2 App, did you solve that issue? Or if there is any idea to approach. Thanks in advance.

**Comment by cyraxchel** [comment]
> @cwule got the same error when developing Hololens 2 App, did you solve that issue? Or if there is any idea to approach. Thanks in advance.

Please, check corerct version VC installed. When I install VS 2019, it fix error. Before was VS 2017..  Sorry, I don't remember, which versions on both Visual Studio on.

**Comment by Cipher-zzz** [comment]
@cyraxchel Thanks for your response. I have tried both VS 2019 and VS 2022, with VC 2019 redistributable installed, same error:

```
DllNotFoundException: Unable to load DLL 'libtensorflowlite_c': The specified module could not be found.
  at TensorFlowLite.InterpreterOptions.TfLiteInterpreterOptionsCreate () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.InterpreterOptions..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.BaseImagePredictor`1[T]..ctor (System.String modelPath, System.Boolean useGPU) [0x00000] in <00000000000000000000000000000000>:0 
  at TensorFlowLite.SSD..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
  at SsdSample.Start () [0x00000] in <00000000000000000000000000000000>:0 
```

I think the reason for this error could be different from the one in the origin post. I checked the DLL file 'libtensorflowlite_c' in Unity, it seems only support x86 and x64. However, I am building the project into HoloLens 2 which is ARM64, which should be the reason why this happened. 

I don't have much experience in Unity development, I am not sure what does that DLL file is for and how to make it support ARM64 devices. I will appreciate that if you can give me some ideas. @asus4

**Comment by asus4** [comment]
I haven't tried building it. But I think you can cross-compile it by adding build options in bazel.
https://www.tensorflow.org/lite/guide/build_arm

To build a dll for Windows, please refer to the build script `build_tflite.py`
https://github.com/asus4/tf-lite-unity-sample/blob/0060d49735c7061c63063ca7a859f04306ae61f6/build_tflite.py#L50-L54

**Comment by Cipher-zzz** [comment]
@asus4 Thank you! I will have a try.

**Comment by siri-sinthawat** [comment]
@Cipher-zzz The same error is happening to me. Can it be fixed?

**Comment by Cipher-zzz** [comment]
@siri-sinthawat I am temporarily working on another project, haven't tried it yet. I will comment here if there is any update.

**Comment by fatlinlin** [comment]
the same error happen on my mac pro

**Comment by asus4** [comment]
Did you pull Git LFS files? All libs are in Git LFS.
