### ISSUE TITLE
WebCamTexture has wrong rotation in mobile phone

### ISSUE THREAD

**Issue by Necr034ncer** [asus4/tf-lite-unity-sample#41]
When I tried running the SSD sample on Windows the camera view works perfectly fine but on an android phone the camera view on the screen is upside down. How do I fix the orientation of the camera view?

**Comment by asus4** [comment]
A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.

https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48

**Comment by D3m0n92** [comment]
> A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> 
> https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48

I tried to change the various values, but it remains a very important problem. The recognition boxes have wrong positions. Probably because the transformations of the texture occur after carrying out the position calculations, creating a discrepancy between the texture and the calculated (old) positions.

**Comment by Necr034ncer** [comment]
> A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> 
> https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48

Thanks! Was able to get it fixed

**Comment by D3m0n92** [comment]
> > A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> > https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48
> 
> Thanks! Was able to get it fixed

Excuse me, do the recognition boxes also work? That is, are they in the right positions and sizes? Because in my case both the positions and the dimensions are wrong (like
if they needed a mirror).

**Comment by Necr034ncer** [comment]
> > > A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> > > https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48
> > 
> > 
> > Thanks! Was able to get it fixed
> 
> Excuse me, do the recognition boxes also work? That is, are they in the right positions and sizes? Because in my case both the positions and the dimensions are wrong (like if they needed a mirror).

It works perfectly fine for me.
![Screenshot_20200724-175155_SSD_sample 1](https://user-images.githubusercontent.com/68719607/88380457-363f4400-cdd7-11ea-8e57-20c5bc119d1c.jpg)

**Comment by D3m0n92** [comment]
> > > > A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> > > > https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48
> > > 
> > > 
> > > Thanks! Was able to get it fixed
> > 
> > 
> > Excuse me, do the recognition boxes also work? That is, are they in the right positions and sizes? Because in my case both the positions and the dimensions are wrong (like if they needed a mirror).
> 
> It works perfectly fine for me.
> ![Screenshot_20200724-175155_SSD_sample 1](https://user-images.githubusercontent.com/68719607/88380457-363f4400-cdd7-11ea-8e57-20c5bc119d1c.jpg)

Could you try to recognize a smaller object? For example by testing the recognition of a smartphone. The problem is evident only with objects from the "smaller" box

**Comment by Necr034ncer** [comment]
> > > > > A simple workaround is overriding `resizeOptions` in SSD.cs. But we need more tests on Andoird.
> > > > > https://github.com/asus4/tf-lite-unity-sample/blob/070e98b4a43ba264d3a0f94a9d66d8bdeb8e765f/Assets/Samples/Common/BaseImagePredictor.cs#L40-L48
> > > > 
> > > > 
> > > > Thanks! Was able to get it fixed
> > > 
> > > 
> > > Excuse me, do the recognition boxes also work? That is, are they in the right positions and sizes? Because in my case both the positions and the dimensions are wrong (like if they needed a mirror).
> > 
> > 
> > It works perfectly fine for me.
> > ![Screenshot_20200724-175155_SSD_sample 1](https://user-images.githubusercontent.com/68719607/88380457-363f4400-cdd7-11ea-8e57-20c5bc119d1c.jpg)
> 
> Could you try to recognize a smaller object? For example by testing the recognition of a smartphone. The problem is evident only with objects from the "smaller" box. Clearly with the orientation of the forced app in portrait mode

Still no issue for me.
![Screenshot_20200724-181430_SSD sample](https://user-images.githubusercontent.com/68719607/88381786-a6e76000-cdd9-11ea-8d5f-e5dcce41fa1f.jpg)

**Comment by D3m0n92** [comment]
I solved my problem. I was not using the WebCamTexture, but the video stream recovered through ARFoundation to join the two systems. By modifying the main flow and using the reported parameters I managed to correct everything.
