### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by Necr034ncer** [asus4/tf-lite-unity-sample#44]
How do I use my own custom model for the SSD sample?

**Comment by asus4** [comment]
If you follow the articles below, you can make a model that works on TFLite.

https://www.tensorflow.org/lite/models/object_detection/overview#customize_model
https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

**Comment by Necr034ncer** [comment]
> If you follow the articles below, you can make a model that works on TFLite.
> 
> https://www.tensorflow.org/lite/models/object_detection/overview#customize_model
> https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

I already have a tflite model. When I add it to the StreamingAssets and choose the model and labelmap in Unity, running the project I get a TensorFlowLite operation failed exception error

**Comment by asus4** [comment]
@Necr034ncer Added "ErrorReporter" on the master branch. 5eef1a5c327bdcae4b9046bc841e7aa47fb16492
Now you can see the more specific errors from TFLite in UnityEditor.

**Comment by Necr034ncer** [comment]
> @Necr034ncer Added "ErrorReporter" on the master branch. [5eef1a5](https://github.com/asus4/tf-lite-unity-sample/commit/5eef1a5c327bdcae4b9046bc841e7aa47fb16492)
> Now you can see the more specific errors from TFLite in UnityEditor.

![image](https://user-images.githubusercontent.com/68719607/89374068-e3da1d80-d71c-11ea-86be-33eec88dafb5.png)

Can no longer run the project due to those error

**Comment by Necr034ncer** [comment]
![image](https://user-images.githubusercontent.com/68719607/89489735-bd2feb80-d7dd-11ea-88ff-3cd087726c36.png)

When running the project the webcam does not turn on and there were those error

**Comment by asus4** [comment]
Hi @Necr034ncer, the error has been fixed in the following commit
https://github.com/asus4/tf-lite-unity-sample/commit/b5d578138a06157db72be81688c726d67d2d6e45
