### ISSUE TITLE
error: conflicting types for'printf'

### ISSUE THREAD

**Issue by LoganLxb** [asus4/tf-lite-unity-sample#48]
When packaging ssd, Xcode appears error: conflicting types for'printf'.

![WeChat7c855f7d956aaecdad39496b40a2558f](https://user-images.githubusercontent.com/52527895/89262416-238fff00-d662-11ea-8771-c11156db6894.png)

Please help me，
Thanks.

**Comment by asus4** [comment]
@LoganLxb Fixed it. Can you try it on iOS again?

**Comment by LoganLxb** [comment]
It's ready to use now, thanks
