### ISSUE TITLE
tensorflow_lite_gpu_framework missing architecture arm64?

### ISSUE THREAD

**Issue by borderlineinteractive** [asus4/tf-lite-unity-sample#5]
Hi, I tried to compile your example for iOS and get the following error:

.../tf-lite-unity-sample-master/ios_build/Frameworks/TensorFlowLite/Plugins/iOS/tensorflow_lite_gpu_framework.framework/tensorflow_lite_gpu_framework, file was built for archive which is not the architecture being linked (arm64)

I checked the architecture of the tensorflow_lite_gpu_framework with the command lipo -info tensorflow_lite_gpu_framework and get the following output:

Non-fat file: tensorflow_lite_gpu_framework is architecture: x86_64

in contrast, TensorFlowLiteC.framework looks fine. Maybe I am missing something?

Thanks a lot,

Leif

**Comment by asus4** [comment]
Hi, @borderlineinteractive thanks, I rebuilt the framework for ARM64 on `metal-delegate-arm64` branch. Could you test it?
https://github.com/asus4/tf-lite-unity-sample/tree/metal-delegate-arm64

**Comment by borderlineinteractive** [comment]
Thanks for looking into this. The framework now has the correct architecture, however, now I get a different linker error when I compile in Xcode:

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      tflite::gpu::metal::CreateComputeProgram(id<MTLDevice>, NSString*, NSString, NSDictionary<NSString, NSString>*, id<MTLComputePipelineState> __autoreleasing*) in tensorflow_lite_gpu_framework(common_5e90257ae3a0af5f3d8bf2af9e917acb.o)
 tflite::gpu::metal::GetGpuType() in tensorflow_lite_gpu_framework(environment_a03ef6e7ae5f2d40d80d624a313fe1be.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas?

Thanks a lot,

Leif

**Comment by asus4** [comment]
It looks like the XCode versions issue. Which version do you use? Could you try the latest XCode
https://forums.developer.apple.com/thread/123003
