### ISSUE TITLE
failed to build for iOS

### ISSUE THREAD

**Issue by ethanscho** [asus4/tf-lite-unity-sample#51]
**Environment (please complete the following information):**
 - OS: iOS
 - Version latest

**Describe the bug**
After building for iOS from Unity, while building the app from XCode, there are linker errors.

**Screenshots**
ld: warning: ignoring file /Users/seunghun/Desktop/ios/Frameworks/com.github.asus4.tflite/Plugins/iOS/tensorflow_lite_gpu_framework.framework/tensorflow_lite_gpu_framework, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
ld: warning: ignoring file /Users/seunghun/Desktop/ios/Frameworks/com.github.asus4.tflite/Plugins/iOS/TensorFlowLiteC.framework/TensorFlowLiteC, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture arm64:
  "_TFLGpuDelegateCreate", referenced from:
      _InterpreterOptions_CreateGpuDelegate_m9CF4B5134A4CA45B0D6930F21745584B965A948C in TensorFlowLite.o
      _MetalDelegate__ctor_m413ED5FE1CE943B2B30692F6792FE54F632B77F6 in TensorFlowLite.o
      _MetalDelegate_TFLGpuDelegateCreate_m4CA4AB8D8DD023BE7D39A7D101A9819BEEBD6B6E in TensorFlowLite.o
     (maybe you meant: _MetalDelegate_TFLGpuDelegateCreate_m4CA4AB8D8DD023BE7D39A7D101A9819BEEBD6B6E)
  "_TfLiteInterpreterOptionsSetErrorReporter", referenced from:
      _InterpreterOptions__ctor_mD75762A156970C68CF0CD31C42736CA2CF3B813E in TensorFlowLite.o
      _InterpreterOptions_TfLiteInterpreterOptionsSetErrorReporter_mBAEFDC811B5245633A6F21ED3718FB6096EE95D3 in TensorFlowLite.o
     (maybe you meant: _InterpreterOptions_TfLiteInterpreterOptionsSetErrorReporter_mBAEFDC811B5245633A6F21ED3718FB6096EE95D3)
  "_TfLiteTensorName", referenced from:
      _Interpreter_GetTensorName_m789E4ACB99A50F75B84681F8CC500287003FCB3B in TensorFlowLite.o
      _Interpreter_TfLiteTensorName_m45B4CF90530E0171F63BA303BB95444C18056218 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorName_m45B4CF90530E0171F63BA303BB95444C18056218)
  "_TfLiteTensorDim", referenced from:
      _Interpreter_GetTensorInfo_mA5E98D07988B26FF9926FF3802099B51F6C00CC8 in TensorFlowLite.o
      _Interpreter_TfLiteTensorDim_m694EDEC3C38A07E30B52F99375F6388F44C278BE in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorDim_m694EDEC3C38A07E30B52F99375F6388F44C278BE)
  "_TfLiteInterpreterGetInputTensorCount", referenced from:
      _Interpreter_GetInputTensorCount_m92ABB6CAD4F368066E5ECC80C60D5DA27A69E303 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterGetInputTensorCount_m7FFD7F21300E23D99D5E4CDE922C9E5951148E3A in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterGetInputTensorCount_m7FFD7F21300E23D99D5E4CDE922C9E5951148E3A)
  "_TfLiteInterpreterOptionsSetNumThreads", referenced from:
      _InterpreterOptions_set_threads_m56CE436B165FDDB99C3BB1ED481D51A839A3CE67 in TensorFlowLite.o
      _InterpreterOptions_TfLiteInterpreterOptionsSetNumThreads_mAFE3FC8181C0BFF2BED6A9CF06E64B100B3CD1C2 in TensorFlowLite.o
     (maybe you meant: _InterpreterOptions_TfLiteInterpreterOptionsSetNumThreads_mAFE3FC8181C0BFF2BED6A9CF06E64B100B3CD1C2)
  "_TfLiteInterpreterOptionsCreate", referenced from:
      _InterpreterOptions__ctor_mD75762A156970C68CF0CD31C42736CA2CF3B813E in TensorFlowLite.o
      _InterpreterOptions_TfLiteInterpreterOptionsCreate_m1502A66E89FFE410ADBB49E103DA3765AC84157A in TensorFlowLite.o
     (maybe you meant: _InterpreterOptions_TfLiteInterpreterOptionsCreate_m1502A66E89FFE410ADBB49E103DA3765AC84157A)
  "_TfLiteTensorQuantizationParams", referenced from:
      _Interpreter_GetTensorInfo_mA5E98D07988B26FF9926FF3802099B51F6C00CC8 in TensorFlowLite.o
      _Interpreter_TfLiteTensorQuantizationParams_mDF84C6660781360E49AA58A532F74A6B5333393C in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorQuantizationParams_mDF84C6660781360E49AA58A532F74A6B5333393C)
  "_TfLiteInterpreterGetOutputTensor", referenced from:
      _Interpreter_GetOutputTensorData_mC553A53E5016BA9A81FD061A85C1557714C622E5 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterGetOutputTensor_mF0D6705F26BE2D49C4CDFA59E5038B4C98B0836E in TensorFlowLite.o
      _Interpreter_GetOutputTensorInfo_mA1040095C912D1220F50B8BF9F1808E222C20ECF in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterGetOutputTensor_mF0D6705F26BE2D49C4CDFA59E5038B4C98B0836E, _Interpreter_TfLiteInterpreterGetOutputTensorCount_m2606C10C1C4D7DF41B561FBC88DEF679FA0F4437 )
  "_TFLGpuDelegateDelete", referenced from:
      _MetalDelegate_Dispose_m8DA638B035C3A79924DD4B53919BDBFD50A0DF5A in TensorFlowLite.o
      _MetalDelegate_TFLGpuDelegateDelete_m68AABE0EF59C7D31866CD51BDC5FA5AE9BBFCE7E in TensorFlowLite.o
     (maybe you meant: _MetalDelegate_TFLGpuDelegateDelete_m68AABE0EF59C7D31866CD51BDC5FA5AE9BBFCE7E)
  "_TfLiteTensorType", referenced from:
      _Interpreter_GetTensorInfo_mA5E98D07988B26FF9926FF3802099B51F6C00CC8 in TensorFlowLite.o
      _Interpreter_TfLiteTensorType_m5C720268382B76E918FE028B140BA3D6C91DE0FB in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorType_m5C720268382B76E918FE028B140BA3D6C91DE0FB)
  "_TfLiteInterpreterGetInputTensor", referenced from:
      _Interpreter_SetInputTensorData_m8E2595ECA226081E831D54C19B3035E86315604A in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterGetInputTensor_mCAADED55C4420901610DD5734D4AD3F5BA83DC0A in TensorFlowLite.o
      _Interpreter_GetInputTensorInfo_m057FCA64EF9DCF993358A9B508136FDE0BFB780A in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterGetInputTensorCount_m7FFD7F21300E23D99D5E4CDE922C9E5951148E3A, _Interpreter_TfLiteInterpreterGetInputTensor_mCAADED55C4420901610DD5734D4AD3F5BA83DC0A )
  "_TfLiteTensorNumDims", referenced from:
      _Interpreter_GetTensorInfo_mA5E98D07988B26FF9926FF3802099B51F6C00CC8 in TensorFlowLite.o
      _Interpreter_TfLiteTensorNumDims_m3B7B8BB15E5C8808CE4B430C571F8E975A4210B4 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorNumDims_m3B7B8BB15E5C8808CE4B430C571F8E975A4210B4)
  "_TfLiteTensorCopyToBuffer", referenced from:
      _Interpreter_GetOutputTensorData_mC553A53E5016BA9A81FD061A85C1557714C622E5 in TensorFlowLite.o
      _Interpreter_TfLiteTensorCopyToBuffer_m05FF7E7947B3D1936634A234254F2CE81F1551BF in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorCopyToBuffer_m05FF7E7947B3D1936634A234254F2CE81F1551BF)
  "_TfLiteInterpreterAllocateTensors", referenced from:
      _Interpreter_AllocateTensors_m87C3D29EA509021F9B6E30E3E717548BC0781DB3 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterAllocateTensors_m7BA0CBCECD65A1FC061ABD5B3D3DD1775499404A in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterAllocateTensors_m7BA0CBCECD65A1FC061ABD5B3D3DD1775499404A)
  "_TfLiteTensorCopyFromBuffer", referenced from:
      _Interpreter_SetInputTensorData_m8E2595ECA226081E831D54C19B3035E86315604A in TensorFlowLite.o
      _Interpreter_TfLiteTensorCopyFromBuffer_m214FACD0A3EA3896904B8B27F5E4B1A8CE13499A in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteTensorCopyFromBuffer_m214FACD0A3EA3896904B8B27F5E4B1A8CE13499A)
  "_TfLiteInterpreterGetOutputTensorCount", referenced from:
      _Interpreter_GetOutputTensorCount_m96463F4D302EA3D4B5C9563A968801B49BD1B7B8 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterGetOutputTensorCount_m2606C10C1C4D7DF41B561FBC88DEF679FA0F4437 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterGetOutputTensorCount_m2606C10C1C4D7DF41B561FBC88DEF679FA0F4437)
  "_TfLiteInterpreterInvoke", referenced from:
      _Interpreter_Invoke_m228B38FCA1CCEDE758CBA924CC325BC7C8732AA6 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterInvoke_mFB177A3C0D7EDF73045D8E952E051435BEF24CBF in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterInvoke_mFB177A3C0D7EDF73045D8E952E051435BEF24CBF)
  "_TfLiteInterpreterResizeInputTensor", referenced from:
      _Interpreter_ResizeInputTensor_mEA17BDF5F7ADE68652E3606CF4B744683AEA668A in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterResizeInputTensor_m307802B59A2200D95F48B17F40416578BF696968 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterResizeInputTensor_m307802B59A2200D95F48B17F40416578BF696968)
  "_TfLiteModelDelete", referenced from:
      _Interpreter_Dispose_mA3DB3B46FF7C3047FCFC47CC627D71488C8061B5 in TensorFlowLite.o
      _Interpreter_TfLiteModelDelete_m600AE3A0AA1FB351BD00F07417086A15815C5A60 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteModelDelete_m600AE3A0AA1FB351BD00F07417086A15815C5A60)
  "_TfLiteModelCreate", referenced from:
      _Interpreter__ctor_mF1E8928B8C931C4786E6D5302D200E7616B676D3 in TensorFlowLite.o
      _Interpreter_TfLiteModelCreate_m89DA4A8D9E41006AC6460276528DE61E1CA594C9 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteModelCreate_m89DA4A8D9E41006AC6460276528DE61E1CA594C9)
  "_TfLiteInterpreterOptionsDelete", referenced from:
      _InterpreterOptions_Dispose_m324112C3E24DC6FE78463DFFCEBD5EC38D022236 in TensorFlowLite.o
      _InterpreterOptions_TfLiteInterpreterOptionsDelete_m1932391AAF4EA1B7F387CF0B61A34D0B860BABAD in TensorFlowLite.o
     (maybe you meant: _InterpreterOptions_TfLiteInterpreterOptionsDelete_m1932391AAF4EA1B7F387CF0B61A34D0B860BABAD)
  "_TfLiteInterpreterOptionsAddDelegate", referenced from:
      _InterpreterOptions_AddGpuDelegate_m028C34BD98FB94386DCBAC1952494D5159D92893 in TensorFlowLite.o
      _InterpreterOptions_TfLiteInterpreterOptionsAddDelegate_m163B9B3951EC9F7B971426F9E4C24F91C1901134 in TensorFlowLite.o
     (maybe you meant: _InterpreterOptions_TfLiteInterpreterOptionsAddDelegate_m163B9B3951EC9F7B971426F9E4C24F91C1901134)
  "_TfLiteInterpreterDelete", referenced from:
      _Interpreter_Dispose_mA3DB3B46FF7C3047FCFC47CC627D71488C8061B5 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterDelete_mDBADEA03FF68E11454A0305C9C8F71744A5236F6 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterDelete_mDBADEA03FF68E11454A0305C9C8F71744A5236F6)
  "_TfLiteInterpreterCreate", referenced from:
      _Interpreter__ctor_mF1E8928B8C931C4786E6D5302D200E7616B676D3 in TensorFlowLite.o
      _Interpreter_TfLiteInterpreterCreate_m59679647837EBEADA0D889BF124811535293D1A5 in TensorFlowLite.o
     (maybe you meant: _Interpreter_TfLiteInterpreterCreate_m59679647837EBEADA0D889BF124811535293D1A5)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by asus4** [comment]
https://github.com/asus4/tf-lite-unity-sample#install-tensorflow-lite-for-unity

You need to install Git LFS to use the iOS frameworks

**Comment by ethanscho** [comment]
I already did.
