### ISSUE TITLE
Memory Leak on Android

### ISSUE THREAD

**Issue by ArthurAtlantico** [asus4/tf-lite-unity-sample#53]
The SSD sample scene contains a memory leak on Android and possibly other platforms too.

Steps to reproduce: load the SSD scene and leave it for a while. 

![Memory Leak](https://user-images.githubusercontent.com/63819531/90162133-8cfec480-dd6a-11ea-899a-66626564f0cc.PNG)

**Comment by ArthurAtlantico** [comment]
Downgraded to commit 4b3c8de ("Update android GPU delegate" 29 Nov 2019) and the problem is there too.

![Mempry Leak 2](https://user-images.githubusercontent.com/63819531/90164511-e0bedd00-dd6d-11ea-83ec-183ded2c32d0.PNG)

**Comment by asus4** [comment]
[Texture2D.GetPixels32](https://docs.unity3d.com/ScriptReference/Texture2D.GetPixels32.html) had spawned more than 300kb GC Allocations per frame. Replaced the API with [Texture2D.GetRawTextureData](https://docs.unity3d.com/2019.3/Documentation/ScriptReference/Texture2D.GetRawTextureData.html). This change also means that it will no longer work in old Unity versions (e.g. Unity 2017). However, performance improvement is expected.

__Before__
![before](https://user-images.githubusercontent.com/357497/90569340-0274f580-e1ae-11ea-8475-630f28df888a.png)

__After__
![after](https://user-images.githubusercontent.com/357497/90569358-0acd3080-e1ae-11ea-95f6-d5b3d770cbbc.png)

Thanks, @ArthurAtlantico !!

**Comment by ArthurAtlantico** [comment]
Tested the latest commit on a different device and the result is this:

![New Test](https://user-images.githubusercontent.com/63819531/90670740-fdee2280-e229-11ea-92cd-af725fc89b75.PNG)

Looks like it's stable now. GC is automatically working every 1.5 minutes or so, hence the wave-like graph. Great job and thank you very much!
