### ISSUE TITLE
[PoseNet]The camera's screen is upside down

### ISSUE THREAD

**Issue by heerangkim** [asus4/tf-lite-unity-sample#54]
**Environment (please complete the following information):**
 - OS/OS Version: macOS 10.15.6]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.5.f1]

**Describe the bug**
[PoseNet]The camera's screen is upside down

**Comment by asus4** [comment]
Hi @heerangkim,

This issue #41 would be helpful. But my environment (macOS 10.15.6, Unity 2019.4.5f1) is exactly the same, but I can't reproduce it. What is the rotation value of the webcam you're using?  `theWebcamTexture.videoRotationAngle`

**Comment by stevehadley** [comment]
I was about to create an issue regarding camera rotation but it might be better to just comment here. When I built to Android the camera is locked in landscape and there's a lot of rotations going on throughout the code so I was wondering the best place to change this. The value of webcamTexture.videoRotationAngle on Android is 90, on desktop it is 0. I notice there's some rotations going on in the resize shader as well as the base image predicter class. Where should I be modifying this rotation? Thanks in advance you're doing awesome work!

**Comment by stevehadley** [comment]
Oh and this is in the SSD example, sorry for not mentioning that.

**Comment by asus4** [comment]
At the commit 7a6136cb9bfd578686b3c3e9a26b13690800e0c8, I fixed the issue related with `WebcamTexture.videoRotationAngle` on mobile. This changes might fix this issue, can you test it again?

**Comment by heerangkim** [comment]
Oh, Thanks i try test next day!
Thank you.  : )

**Comment by DarraghB** [comment]
I'm trying to use a front facing camera and getting the same issue. When the phone is portrait the camera is mirrored, and when its landscape everything is upside down. I tried changing the Vector3 positions to Vector3.right, Vector3.down etc.
