### ISSUE TITLE
iOS linking error

### ISSUE THREAD

**Issue by ethanscho** [asus4/tf-lite-unity-sample#55]
**Environment (please complete the following information):**
 - OS/OS Version: iOS 13.5.1
 - Source Version: master/v2.2.0
 - Unity Version: 2019.4.5.f1

**Describe the bug**
- Linking error
- Git LFS already setup
- framework folders exists.

```
cd Frameworks/com.github.asus4.tflite/Plugins/iOS
ls
TensorFlowLiteC.framework
_TensorFlowLiteC.framework
tensorflow_lite_gpu_framework.framework
```

**To Reproduce**
1. build for iOS framework from Unity
2. open XCode and build & run

**Expected behavior**
Run iOS app without error.

**Screenshots**
![Screen Shot 2020-08-19 at 1 43 55 PM](https://user-images.githubusercontent.com/25470176/90593233-69cc8d00-e222-11ea-961b-ae2fa2a173a5.png)

**Comment by moecia** [comment]
Did you fix that? I have the same problem.

**Comment by puny-d** [comment]
I have the same problem, any update about it ?

**Comment by moecia** [comment]
> I have the same problem, any update about it ?

I fixed it by using the latest version.
