### ISSUE TITLE
DLL not found exception

### ISSUE THREAD

**Issue by dr804** [asus4/tf-lite-unity-sample#67]
- Android 10 (Google pixel 3a).
 - Source Version: 2.3.0.
 - Unity Version: Unity 2019.4.6.f1.

PoseNet not working on android. Logcat produces a DLL not found exception for libtensorflowlite_c.dll.

To reproduce, add package to a new unity project using openupm and use posenet on mobile.

**Comment by dr804** [comment]
I found the solution to this. In player settings, change scripting backend to IL2CPP and select Arm 64, not Arm v7. Perhaps this could be included in the readme to prevent future issues? Just a suggestion 😊

**Comment by asus4** [comment]
oh, the Android plugin only supports Arm64. Please re-build for Armv7 if you need it. I'll add these instructions to README. thanks for the suggestion.

**Comment by dr804** [comment]
No problem! 😊
