### ISSUE TITLE
Failed TensorflowLite Operation

### ISSUE THREAD

**Issue by Zumbalamambo** [asus4/tf-lite-unity-sample#7]
The input shape of my model is `[  1 256 256   3]`

I'm getting the following errror,

> Exception: TensorFlowLite operation failed.
> TensorFlowLite.Interpreter.ThrowIfError (System.Int32 resultCode)

How do I fix this?

I have invoked the Model as follows,

`        model.Invoke(background.texture);
`

background is the rawimage. I tried to save the raw image to png  image and ocourse,  it is not null.

Following is my Invoke function,

```
public override void Invoke(Texture inputTex)
        {
            ToTensor(inputTex, inputs);

            Debug.LogWarning(inputTex.height + " " + inputs.Length);
            interpreter.SetInputTensorData(0,  inputs);
            interpreter.Invoke();
        }
```

How do I fix this error?

**Comment by asus4** [comment]
I guess its the tensor format mismatching. you can check the input format with the following method. or [Netron](https://github.com/lutzroeder/netron) is a good GUI app.
```c#
var info = interpreter.GetInputTensorInfo(index)
```

or could you share the tflite file? It is difficult to identify this type of program w/o the model.

**Comment by Zumbalamambo** [comment]
i tried Netron. This is the input part of the graph.

`
![Capture](https://user-images.githubusercontent.com/24539006/75063081-6dd25900-54e4-11ea-88cd-95188e849c35.PNG)
`

**Comment by asus4** [comment]
Click input, then detailed information appears.
MNIST's input is float32, SSD is quantized to uint8.
![cap_mnist](https://user-images.githubusercontent.com/357497/75070174-01ab2180-54f3-11ea-80fd-a89e54403aa9.png)
![cap_ssd](https://user-images.githubusercontent.com/357497/75070184-053ea880-54f3-11ea-8739-33dd21c85eca.png)

**Comment by kasi-str8bat** [comment]
Hi, can i turnoff the quantization from the library?

**Comment by D3m0n92** [comment]
Same problem.

**Comment by JoochanKim-LTU** [comment]
> Hi, can i turnoff the quantization from the library? is it possible to import float32 model?

I'm also trying to solve this issue. Any luck yet?

**Comment by klauspa** [comment]
I can't quantized my SSD model, how do I modify the code so that my 32bit model can be loaded in this project? many thanks
