### ISSUE TITLE
Widescreen Option

### ISSUE THREAD

**Issue by SBeyer6** [asus4/tf-lite-unity-sample#71]
Hi

I tried to edit the palm detection so it supports a 16:9 aspect ratio, but it forces the anchor count to be 2944 so it throws an error because of that. Then it seems to get the width and height from the tf interpreter saying that the width and height must be 256x256. Is there a way to use a 16:9 ratio, or do I have to create a new model that supports that aspect ratio?

**Comment by asus4** [comment]
Hi, @SBeyer6  creating the TFLite model for 16:9 input is the most coherent way. But if you don't want to recreate it, please try the following option to scale the input image. (I only tested with AspectMode.Fill option, maybe you need to change the code a bit)  

`AspectMode.Fill` to `AspectMode.Fit`
https://github.com/asus4/tf-lite-unity-sample/blob/280bfcf45e5adf25bb320023b0ec62d7bbe5acd2/Assets/Samples/Common/BaseImagePredictor.cs#L55

![fit vs fill](https://i.stack.imgur.com/yewnN.png)
[image from stakcoverflow](https://stackoverflow.com/questions/37613780/set-image-height-in-aspect-fill-in-auto-layout-in-xcode/37614034)

**Comment by SBeyer6** [comment]
Okay, I decided to make the aspect fit for now, maybe in the future I will recreate it. Thanks for your help.
