### ISSUE TITLE
[Setup + Build] How to build a library tensorflowlite.dll

### ISSUE THREAD

**Issue by Jane-Tran** [asus4/tf-lite-unity-sample#72]
**Question ???**
You can describe the steps to build the library or tutorial YouTuBe

I would be very grateful for that <3

**Comment by asus4** [comment]
It would be better to open an issue on TensorFlow's GitHub. I'm afraid that I can not support the tutorial in this repo.

please refer [the official TensorFlow document](https://www.tensorflow.org/install/source_windows#configure_the_build). It is the document for TensorFlow, not for TFLite. But if you can build TensorFlow with Windows, you are also able to build TFLite easily.

**Comment by Jane-Tran** [comment]
@asus4  Thank you so much for responded
