### ISSUE TITLE
[posenet] poseNet.Invoke(webcamTexture) into another thread

### ISSUE THREAD

**Issue by tolotratlt** [asus4/tf-lite-unity-sample#74]
Sometimes poseNet.Invoke (webcamTexture) can be processing power heavy. But it seems that it is not possible to execute it in an external thread.
Unity isn't thread safe. poseNet.Invoke(webcamTexture) can only be executed in the main thread.
Is there a way to do it with Job system or managed multihtread?

**Comment by asus4** [comment]
Hi @tolotratlt, To keep examples simple, I don't add the multithreaded example in this repo. But it's better to run TFLite in the background thread in the practical project. and TFLite works with multithread.

As a side project, I have released [an app](https://mobile.twitter.com/asus4/status/1291282486622814208) that uses multithreaded TFLite with Unity. In the app, I used [UniTask](https://github.com/Cysharp/UniTask) library to manage the thread.

**Comment by tolotratlt** [comment]
Hi @asus4 thanks for advice. How do you use UniTask with Posenet? How do you passe webcam texture to Invoke function?
I'm thinking of using something like
```
async UniTask<PoseNet.Result> ProcessPosenet(WebCamTexture webcamTexture)
{
    await poseNet.Invoke(webcamTexture);
    results = poseNet.GetResults();
    return results ;
}
```

under update function but it doesn't seem to work. Or I don't know how to use it

**Comment by asus4** [comment]
All Unity APIs need to be called from the Unity main thread. You need to tweak inside PoseNet.cs to separate only the TFLite part into the thread. sorry, I cannot share my source code though.

**Comment by tolotratlt** [comment]
Thanks you for answers. I'll do some investigations

**Comment by TheBricktop** [comment]
@tolotratlt  How is the investigations going?

**Comment by tolotratlt** [comment]
@TheBricktop for now, I'm just using async task (that isn't multithread). I am still under investigation 
Last I noticed, asus4 just added "runBacktround" option in PoseNet  :)
