### ISSUE TITLE
Processing speedup

### ISSUE THREAD

**Issue by Roberto7766** [asus4/tf-lite-unity-sample#80]
Hi, I was able to implement a custom model based on TFlite. The issue is that it takes very long time to compute. Is there a way to increase performance?

Thanks

**Comment by asus4** [comment]
Hi @Roberto7766, I'm not a professional in optimization. So here are some links that might be helpful.

https://www.tensorflow.org/lite/performance/model_optimization
https://www.tensorflow.org/lite/performance/measurement
https://www.tensorflow.org/api_docs/python/tf/lite/Optimize
