### ISSUE TITLE
Error "The associated script cant be loaded. Please fix any compile errors and assign a valid script"

### ISSUE THREAD

**Issue by ZoofashanWaheed** [asus4/tf-lite-unity-sample#81]
when i try to run, it shows error "The associated script cant be loaded. Please fix any compile errors and assign a valid script". I am unable to find what's the problem.

**Comment by asus4** [comment]
Would you describe your environment more?
- OS
- Unity version
- Which scene
etc

**Comment by ZoofashanWaheed** [comment]
windows 10
unity version 2019.3.5f1
For all scenes it is giving same error

**Comment by asus4** [comment]
@ZoofashanWaheed  On Windows 10, you might need to install some dependencies. please follow the thread:

https://github.com/asus4/tf-lite-unity-sample/issues/39#issuecomment-719993074

**Comment by ZoofashanWaheed** [comment]
thanks it worked
