### ISSUE TITLE
Not working on Motorola Moto E6s smartphone Android device

### ISSUE THREAD

**Issue by sagargirme** [asus4/tf-lite-unity-sample#83]
Source code latest downloaded
Unity3d version : 2019.4.15f1
**Describe the bug**
Sample test apk is not working on Moto E6s device,while the same apk when tested on Nokia 6 plus its working fine and also detected objects.
please let me know if any additional settings are required to be done on unity3d while exporting the build

**Comment by asus4** [comment]
@sagargirme Could you attach the adb logcat log? These #77, #11 issues might be related.
