### ISSUE TITLE
Landmark output from hand tracking sample in 2d

### ISSUE THREAD

**Issue by cybergen** [asus4/tf-lite-unity-sample#84]
First off, thanks SO MUCH for putting this together. This is really helpful! 

I'm running on PC. I noticed your gif in the readme has 3d landmarks for hand tracking, but the sample is in 2d. Is there a way to get 3d data with the sample?

**Comment by asus4** [comment]
Thank you @cybergen, It was a bug. Fixed it to have the correct z scale. Please have a look.

**Comment by cybergen** [comment]
Works! Thanks again
