### ISSUE TITLE
Error with custom SSD TFlLite file : "Didn't find op for builtin opcode '%s' version '%d'"

### ISSUE THREAD

**Issue by ArnoBen** [asus4/tf-lite-unity-sample#87]
**Environment :**
 - Tensorflow 2.4.0
 - Unity Version: 2019.4.17

**Describe the bug**
When loading an SSD with a .tflite trained on a custom dataset, I get the error message "Didn't find op for builtin opcode '%s' version '%d'"

**To Reproduce**
1. From [this docker image](https://hub.docker.com/r/cheproximity/mobilenet-ssd), train a custom dataset and export the saved_model.pb file.
 
2. Convert the pb file to a TFLite file with the following script :
```
import tensorflow as tf

model = tf.saved_model.load(pb_dir_path)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 300, 300, 3])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.allow_custom_ops = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
    ]
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
with open('ssd_model.tflite', 'wb') as f:
    f.write(tflite_model)
```
    
3. Put the ssd_model.tflite file in Unity and select it from the SSD Inspector in the SSD scene.

4. Play and see error

**Expected behavior**
To have an SSD model working with my custom dataset.

**Additional context**

- The Dockerfile used to train the model uses the latest version of tensorflow so the whole pipeline is using 2.4.0.
- It is stated in the [tensorflow documentation](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md) that `allow_custom_ops` is necessary to allow TFLite_Detection_PostProcess operation.
- The error does not provide which opcode/version is causing an issue, it does say "%" and "%d".

Thank you for this very promising asset.

**Comment by asus4** [comment]
Hi @ArnoBen, 
I haven't tested the docker image, but the error message means that the specified op cannot be found in Select Ops. The select-ops library is not included In this repo at the moment. You need to remove select-ops and perhaps custom-ops as well. Or you can build the select-ops library.

(Additionally, the %s string is not parsed, need to fix it as well)

**Comment by ArnoBen** [comment]
Hello @asus4, thank you very much for your answer.
Do you know any SSD model that I could train myself and use in your asset without custom ops ? Or any model at all, I would be happy with YOLO tiny as well.
If I do have to build the library myself (which sounds tedious), [is this what I have to follow](https://www.tensorflow.org/lite/guide/ops_select) ?

**Comment by asus4** [comment]
@ArnoBen sorry for the late reply.

I haven't tried building the custom SSD models myself, but I think the [official TFLite tutorial](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md#custom-model-used) will work.

> building the library

Yes, you can use the link. If you wanted to build it for PC/macOS, I'm afraid that you need to check the bazel source code

**Comment by ArnoBen** [comment]
Thank you for your answer, I will try with their official tutorial.
