### ISSUE TITLE
Trying to use Unitask to put tflite processing in the background thread

### ISSUE THREAD

**Issue by TheBricktop** [asus4/tf-lite-unity-sample#88]
Hello
thank You for awesome library and examples.
Im trying to use Unitask to optimalise the performance of hand tracking example by putting the computationa heavy texture processing in background thread. Im having some problems with that (probably because threading is already a convoluted process).

my code so far:

    public async UniTask<Vector3[]> HandDetectTask()
    {
        await UniTask.SwitchToThreadPool();

        try
        {
            palmDetect.Invoke(webcamTexture);
            var palms = palmDetect.GetResults(0.7f, 0.3f);
            landmarkDetect.Invoke(webcamTexture, palms[0]);
            var landmarkResult = landmarkDetect.GetResult();
            Vector3[] m_worldJoints = ComputeWordJoints(landmarkResult.joints);
            return m_worldJoints;
        }
        finally
        {
            await UniTask.SwitchToMainThread();
        }
    }

Ive came up to an error 

> UnityException: get_videoRotationAngle can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
TensorFlowLite.TextureResizer+ResizeOptions.GetModifedForWebcam (UnityEngine.WebCamTexture texture) (at Assets/Samples/Common/TextureResizer.cs:29)
TensorFlowLite.TextureResizer.Resize (UnityEngine.Texture texture, TensorFlowLite.TextureResizer+ResizeOptions options) (at Assets/Samples/Common/TextureResizer.cs:103)
TensorFlowLite.BaseImagePredictor`1[T].ToTensor (UnityEngine.Texture inputTex, System.Single[,,] inputs) (at Assets/Samples/Common/BaseImagePredictor.cs:75)
TensorFlowLite.PalmDetect.Invoke (UnityEngine.Texture inputTex) (at Assets/Samples/HandTracking/PalmDetect.cs:66)
>

Does that mean that for full multithreading one does not only need to put all the relevant tf functions to another thread but also rewrite all of the initial code to split the parts that need to be run on main thread and multithread rest of the code ?

**Comment by mathtasatlime** [comment]
The problem here is that all function from the Unity API have to be called from the mainthread. eg the function get_videoRotationAngle is causing problems. 

I have fixed it by really only starting the interpreter.Invoke() inside a second thread and let the pro/post processing in the main thread. thus at least the inference of the model is done parallel. 
Though its not the most satisfying solution. If you got an idea, please let me know!

**Comment by mathtasatlime** [comment]
`public override void Invoke(Texture inputTex)
        {
            ToTensor(inputTex, input0);
           
            Thread invokeThread = new Thread(InvokeThread);
            invokeThread.Start();
        }

        void InvokeThread(){
            interpreter.SetInputTensorData(0, input0);
            interpreter.Invoke();

            interpreter.GetOutputTensorData(0, output0);
            interpreter.GetOutputTensorData(1, output1);

        }`

**Comment by asus4** [comment]
To use the bg thread, you need to modify the `BaseImagePredictor.cs` as well. I will add a UniTask example later :)

**Comment by asus4** [comment]
@TheBricktop  Added a `Run Background` option in the hand tracking sample. Hope it's helpful.

![Screen Shot 2021-01-15 at 23 38 33](https://user-images.githubusercontent.com/357497/104785472-e2605700-578a-11eb-9c10-410c2fb62df5.png)

**Comment by TheBricktop** [comment]
Wow, thank you, I'll try and test it how it performs. Also unitask is a very helpful library that makes threading a kinda painless experience.

**Comment by Sv9zIsT** [comment]
Hello
Thanks for awesome work!
I tried to use this example and stuck with issue 
option "run backround" not working on real android device (tested on Pixel 2xl, don't have another... last 10 android)
unity version 2019.4.23f1
in logcat from unity package manager it detects next issue:

2021.04.05 15:34:39.257 21092 21157 Error Unity Exception: TensorFlowLite operation failed.
2021.04.05 15:34:39.257 21092 21157 Error Unity   at TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at TensorFlowLite.Interpreter.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at TensorFlowLite.PalmDetect+<InvokeAsync>d__8.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at Cysharp.Threading.Tasks.SwitchToThreadPoolAwaitable+Awaiter.Callback (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.257 21092 21157 Error Unity   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <000000000
2021.04.05 15:34:39.268 21092 21157 Info chatty uid=10553(com.Sv9zIsT.handTracking) GC Finalizer identical 1 line
2021.04.05 15:34:39.275 21092 21157 Error Unity Exception: TensorFlowLite operation failed.
2021.04.05 15:34:39.275 21092 21157 Error Unity   at TensorFlowLite.Interpreter.ThrowIfError (TensorFlowLite.Interpreter+Status status) [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at TensorFlowLite.Interpreter.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at TensorFlowLite.PalmDetect+<InvokeAsync>d__8.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at Cysharp.Threading.Tasks.SwitchToThreadPoolAwaitable+Awaiter.Callback (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 
2021.04.05 15:34:39.275 21092 21157 Error Unity   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <000000000

this error appears like a spam in console only when it detects a hand
could you please advice me what I do wrong or how to fix it
thanks in advance!
