### ISSUE TITLE
Use for audio models

### ISSUE THREAD

**Issue by manena** [asus4/tf-lite-unity-sample#9]
Hello, this is a great project! thanks!
I don't have a lot of experience on deep learning. I would like to use a tflite speech command recognition model I downloaded with your example project, but I'm having trouble with the input shape.

I've been trying different things and I sometimes get:
- That the input must be an array of primitives
- TensorFlowLite operation failed
- Sometimes it just crashes and unity closes.

Have you tried any audio model on your project? Is there a known issue with it?

Any clue that helps me fix it will be more than welcome!

**Comment by manena** [comment]
The problem seems to be when calling TfLiteTensorCopyFromBuffer in the  SetInputTensorData method.

Thanks in advance

**Comment by asus4** [comment]
I've never tried any audio models with Unity. In general
- Use CPU mode, not GPU
- Please check whether the input type is correct. float array or quantized int16 array.  #7 this thread might be your help :)

**Comment by manena** [comment]
Netron was very useful! Thanks a lot for your prompt answer!
