### ISSUE TITLE
Show 3D model when object is detected

### ISSUE THREAD

**Issue by syedali1621** [asus4/tf-lite-unity-sample#90]
I am trying to show a 3D model in real world as an AR when any specified object is detected using tensorflowlite SSD scene.
Do you have any idea how to acheive it do i also need to use ARcore or ARKIT or AR foundation with tflite if yes then how to integrate their cameras?

**Comment by asus4** [comment]
To achieve this: I guess,
- Get input texture from ARCore / ARKit
  - There are different texture formats on each platform. Especially ARKit uses the YCbCr texture format. Maybe you need to write a new shader for AR.
- Should use a background thread for good performance.

Let me know if it works!
