### ISSUE TITLE
Example facial expression recognition

### ISSUE THREAD

**Issue by ZoofashanWaheed** [asus4/tf-lite-unity-sample#91]
Thankyou for this project. Can you please add an example for facial expression detection

**Comment by asus4** [comment]
@ZoofashanWaheed Do you know some good facial expression estimation example in TFLite?

**Comment by ZoofashanWaheed** [comment]
no, but I am training on fer2013 dataset and then converting it to tflite.

**Comment by ZoofashanWaheed** [comment]
actually thats my class project but as I am using unity and c# for the
first time, so I am facing difficulty and I don't know about image
processing in c# with unity
