### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object TensorFlowLite.PrimitiveDraw.Draw (TensorFlowLite.PrimitiveDraw+MeshBuffer mb, System.Boolean drawEditor) (at Assets/Scripts/Common/PrimitiveDraw.cs:195)

### ISSUE THREAD

**Issue by ZoofashanWaheed** [asus4/tf-lite-unity-sample#92]
When I run face mesh or posenet examples it gives error, I am unable to find whats the problem.
 
NullReferenceException: Object reference not set to an instance of an object
TensorFlowLite.PrimitiveDraw.Draw (TensorFlowLite.PrimitiveDraw+MeshBuffer mb, System.Boolean drawEditor) (at Assets/Scripts/Common/PrimitiveDraw.cs:195)

**Comment by asus4** [comment]
@ZoofashanWaheed  It has occurred if the scene view is not opened in the Unity Editor. Fixed it 👍
