### ISSUE TITLE
Can you please tell if i want to convert webcam image to grayscale and resize it to specific dimensions and then detect face from it, what changes should i make in face detection example script?

### ISSUE THREAD

**Issue by ZoofashanWaheed** [asus4/tf-lite-unity-sample#93]

**Comment by asus4** [comment]
The model in the [MediaPipe face detection sample](https://github.com/asus4/tf-lite-unity-sample/blob/master/Assets/Samples/FaceMesh/FaceDetectionSample.cs) only accepts float RGB inputs. You need to make a new model it has a grayscale input.
