### ISSUE TITLE
Gfx.ReadbackImage takes over 50ms in Profile mode

### ISSUE THREAD

**Issue by mathtasatlime** [asus4/tf-lite-unity-sample#96]
Hey, 
I noticed that the performance of my Unity project using the HandTracking has a weird looking profile:
![PVlEYMCPOV](https://user-images.githubusercontent.com/74551715/105208311-d852a580-5b48-11eb-949f-7b207f1650c8.png)

I tried to improve the performance by running the HandTracking in the background but I see that the function Texture2D.ReadPixels() is performed in the main thread and that it takes very long:
![xassv1nu5v](https://user-images.githubusercontent.com/74551715/105208308-d7ba0f00-5b48-11eb-86e6-d8dd901920cc.png)

So, I got three questions:
1. is it possible to perform ReadPixels() asynchronously? Or maybe split it in two following frames to reduce the blocking of the main thread?
2. I found out that the function ReadPixels() takes so long because it apparently has to wait for the function Gfx.PresentFrame to be finished until it can start to read the pixels from the GPU storage. Do you know any solution to shift the executing to a different time in the Unity lifecyle to prevent the thread blocking?
3. Is there any alternative to ReadPixels()?

Best wishes!

**Comment by asus4** [comment]
Hi @mathtasatlime, the best solution is to support passing the Unity texture directly to the TFLite GPU delegate. Please refer the issue #23. I think TFLite C API needs to be modified.

As a workaround, it might possible to replace with [AsyncGPUReadback](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.Request.html). You will have a few frames delay, but no main thread blocking.

**Comment by mathtasatlime** [comment]
@asus4 thanks for your answer! I will have a try.

Another thing I really wonder about. When I just run your handTracking sample on my mobile phone the ReadPixels() function only takes about 5-10 ms, whereas in my project it takes about 50ms... that's a huge difference I think. Do you have any clue for that difference? I have of course more models (nothing really special, mostly low poly) in my scene than there are in your sample scene but do they have such an impact?

**Comment by asus4** [comment]
@mathtasatlime There are some reasons, please check the settings:

Slow / Fast
- dev build / release build
- mono (also in unity editor) / il2cpp
- deep profile / normal profile

**Comment by mathtasatlime** [comment]
@asus4 yes, running it in release, il2cpp and normal profile mode did indeed reduce the blocking but it is still present. Still in a way that one can see the lacks repeatedly.

Has anybody already tested AsyncGPUReadback in the project? receiving the webcam picture with a bit delay is not that critical for a game than lacking frame rate...
