### ISSUE TITLE
SSD Sample Scene Fails To Create TensorFlowLite Interpreter On IOS & MacOS With The New 2.4.0 Update 

### ISSUE THREAD

**Issue by EraslankCmos** [asus4/tf-lite-unity-sample#97]
- OS/OS Version: MacOS 10.15.7 &  iOS 14.3
 - Source Version: master v2.4.0
 - Unity Version: Unity 2020.2.1f1

First of all thanks for this awesome repository. I know, i am not on the same version. I upgraded it to the closest Unity version I had at the moment. I was interested in SSD and tried the sample scene. It is working perfectly fine on Windows, both in editor and built version of it. But when it comes to the mac, it is failing to create TensorFlowLite Interpreter. Just to be sure I replaced /Plugins/macOS/libtensorflowlite_metal_delegate.dylib & /Plugins/macOS/libtensorflowlite_c.dylib with the older versions of them which were on the v2.3.0. And it was perfectly fine same goes for the IOS. It is crashing instantly when trying to create a new instance of SSD class. I also tried to replace /Plugins/iOS whole folder with the v2.3.0 and it was working perfectly fine yet again.

1. Open /Assets/Samples/SSD/SSD.unity
2. Hit play and check the console for the error.
No additional steps required for this to reproduce this error. No need for custom model or anything like that.

SSD from v2.3.0 was so good for me, i was so excited and curious to jump into the v2.4.0 to see what it brings to the table. Other than that thanks for this awesome repo again. Wish you the best!

**Comment by asus4** [comment]
I got the following errors: 

```
Interperter Warning: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
63 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
```
```
Interperter Warning: TfLiteMetalDelegate Prepare: 
```
```
Interperter Warning: Node number -481842560 ((null)) (null).
```
```
Interperter Warning: Restored original execution plan after delegate application failure.
```

The Metal GPU delegate in v2.4.0 might not support the SSD model anymore. I think the SSD's model input is quantized to uint8. I've checked the official [iOS example](https://github.com/tensorflow/examples/blob/0913b85a5f9c87fb9fc07e393ee5193c16cc0837/lite/examples/object_detection/ios/ObjectDetection/ModelDataHandler/ModelDataHandler.swift#L105-L106) and the metal delegate was not used. I will disable the GPU option in the SSD example.
