### ISSUE TITLE
MNIST output not update

### ISSUE THREAD

**Issue by leenguyenkim** [asus4/tf-lite-unity-sample#98]
**Environment (please complete the following information):**
 - OS/OS Version: [e.g. iOS 11.0/Andoroid 8.1/macOS 10.15.6]
 - Source Version: [e.g. master/v2.2.0]
 - Unity Version: [e.g. Unity 2019.4.5.f1]

**Describe the bug**
![Screen Shot 21-01-28 at 02 15 PM](https://user-images.githubusercontent.com/78132438/106093419-9abad180-6173-11eb-864f-377c46f85dce.PNG)

Hello

The output fixs and doesn't update

**To Reproduce**
1. run MNIST example

**Comment by asus4** [comment]
@leenguyenkim, It seems working on my end. Do you see any errors?

**Comment by pp2015jp** [comment]
Got the same problem
