### ISSUE TITLE
Using a different model for the MNIST scene

### ISSUE THREAD

**Issue by qsunhan** [asus4/tf-lite-unity-sample#99]
Hi, thanks for making a great project. It helped a lot.

I'm customizing the MNIST scene right now.

Unlike MNIST, I use a pretrained model which use a tensor shape of (1, 32, 32, 3).

in the TextureToBuffer.compute

`uint gid = (32 - tid.y) * 32 + tid.x;`

in the MnistSample.cs

I changed the input value accordingly,
   `float[,,] inputs = new float[32, 32, 3];` 

I also changed the resize value.
       ` interpreter.ResizeInputTensor(0, new int[] {1, 32, 32, 3 });`

But I'm not sure
  ` inputBuffer = new ComputeBuffer(28 * 28, sizeof(float));`      
   ` compute.Dispatch(0, 32/4, 32/4, 1);`     

I don't know which value has to be there.

I changed it with some values and I got an output value, but I can't trust the value. The result is very different from what I did in Jupyter notebook.

Can you help me it?

**Comment by asus4** [comment]
I think the code will be the following: 
```
inputBuffer = new ComputeBuffer(32 * 32 * 3, sizeof(float));
compute.Dispatch(0, 32/4, 32/4, 1);
```
Perhaps you need to change the render-texture-format as well.

---

The Compute Shader in the MNIST sample is just flipping Y-axis. You can remove it and rewrite it in C#.

https://github.com/asus4/tf-lite-unity-sample/blob/8f1fc1e3b9c39f7e8fc853da9d7837539c24bad6/Assets/Samples/MNIST/TextureToBuffer.compute#L11
